const fs = require('fs');
const path = require('path');

const DIR = path.join(__dirname, '..', 'assets', 'data', 'domains');

function addTreatments(filename, treatments) {
  const fp = path.join(DIR, filename);
  const data = JSON.parse(fs.readFileSync(fp, 'utf8'));

  // Verify 4 activations
  if (data.activations.length !== 4) {
    console.error(`ERROR: ${filename} has ${data.activations.length} activations, expected 4`);
    return false;
  }

  // Each activation group maps to a key in treatments object
  const groupOrder = ['diagnostics', 'practices', 'innovation', 'economics'];

  for (let i = 0; i < 4; i++) {
    const group = data.activations[i].group;
    if (!groupOrder.includes(group)) {
      console.error(`ERROR: ${filename} activation ${i} has unexpected group: ${group}`);
      return false;
    }
    const tx = treatments[group];
    if (!tx || tx.length !== 5) {
      console.error(`ERROR: ${filename} missing treatments for group ${group}`);
      return false;
    }
    // Validate each treatment has all 6 fields
    const types = tx.map(t => t.type).sort();
    const expected = ['COACHING', 'CULTURE', 'STRATEGY', 'STRUCTURAL', 'TOOLS'];
    if (JSON.stringify(types) !== JSON.stringify(expected)) {
      console.error(`ERROR: ${filename} group ${group} types mismatch: ${types}`);
      return false;
    }
    data.activations[i].treatments = tx;
  }

  fs.writeFileSync(fp, JSON.stringify(data, null, 2) + '\n');
  console.log(`OK: ${filename}`);
  return true;
}

// ── BATCH: passed via command line arg ──
const batch = process.argv[2];
let count = 0;

if (batch === 'easements') {
  // 1. Easement History
  count += addTreatments('p2_agri_landuse_easements_easementhistory.json', {
    diagnostics: [
      { label: "Baseline Easement Condition Documentation", type: "STRATEGY", evidence: "A", description: "Establish comprehensive photographic and written baseline documentation reports at the time of easement closing. Baseline reports serve as the legal benchmark for all future monitoring comparisons and enforcement actions.", cite: "Land Trust Alliance Standards and Practices, Standard 11, 2019", target: "Baseline gaps -> monitoring ambiguity -> enforcement failure" },
      { label: "Annual Stewardship Visit Training", type: "COACHING", evidence: "A", description: "Train staff and volunteers on standardized monitoring protocols including GPS waypoint collection, photo-point repetition, and violation identification. Consistent observer calibration reduces false positives and missed infractions.", cite: "Land Trust Alliance Accreditation Indicator Practices, 2017", target: "Observer variability -> inconsistent reporting -> legal vulnerability" },
      { label: "Dedicated Stewardship Endowment", type: "STRUCTURAL", evidence: "A", description: "Fund a per-easement stewardship endowment at closing sufficient to cover perpetual annual monitoring costs. Endowment shortfalls are the primary cause of deferred monitoring across land trusts.", cite: "Land Trust Alliance National Land Trust Census, 2020", target: "Funding gaps -> deferred visits -> undetected violations" },
      { label: "Community Monitoring Volunteer Program", type: "CULTURE", evidence: "B", description: "Recruit adjacent landowners and community members as volunteer monitors who report observable changes between formal annual visits. Community engagement creates social accountability reinforcing easement compliance.", cite: "Brewer, R., Conservancy: The Land Trust Movement in America, 2003", target: "Low visibility -> delayed detection -> escalated remediation costs" },
      { label: "Remote Sensing Change Detection Platform", type: "TOOLS", evidence: "B", description: "Deploy satellite or aerial imagery analysis tools to detect land-cover changes on eased parcels between field visits. Automated change-detection algorithms flag clearing, construction, or drainage alterations for priority investigation.", cite: "Dillon et al., Conservation Easement Monitoring Using Remote Sensing, Land Use Policy, 2022", target: "Infrequent visits -> missed changes -> perpetuity risk" }
    ],
    practices: [
      { label: "Standardized Monitoring Report Template", type: "STRATEGY", evidence: "A", description: "Adopt a uniform monitoring report template aligned with Land Trust Alliance standards that captures all required legal and ecological observations. Standardization reduces litigation exposure and ensures defensible records.", cite: "Land Trust Alliance Standards and Practices, Standard 11B, 2019", target: "Inconsistent records -> weak enforcement posture -> easement vulnerability" },
      { label: "Landowner Relationship Coaching", type: "COACHING", evidence: "B", description: "Coach stewardship staff on relationship-building techniques for annual landowner contacts, including active listening and collaborative problem-solving. Strong landowner relationships are the single best predictor of voluntary compliance.", cite: "Rissman, A., Conservation Easements and Landowner Trust, Conservation Biology, 2013", target: "Adversarial interactions -> non-cooperation -> costly enforcement" },
      { label: "Multi-Party Easement Tracking System", type: "STRUCTURAL", evidence: "B", description: "Implement a centralized database linking easement deed terms, amendment history, ownership transfers, and monitoring records across all holders and backup holders. Fragmented records across organizations create perpetuity gaps.", cite: "National Conservation Easement Database (NCED), 2023", target: "Fragmented records -> lost institutional memory -> perpetuity failure" },
      { label: "Easement Awareness Signage Program", type: "CULTURE", evidence: "C", description: "Install discreet boundary markers and informational signs on eased parcels to communicate protected status to subsequent owners and adjacent landowners. Visible demarcation reduces inadvertent encroachment by new owners unfamiliar with restrictions.", cite: "Pidot, J., Reinventing Conservation Easements, Lincoln Institute of Land Policy, 2005", target: "Owner turnover -> ignorance of restrictions -> inadvertent violations" },
      { label: "Mobile Field Data Collection App", type: "TOOLS", evidence: "A", description: "Equip monitors with GPS-enabled mobile applications that auto-populate photo metadata, location coordinates, and checklist items in real time. Digital field tools eliminate transcription errors and accelerate report generation.", cite: "Land Trust Alliance Technology Committee, Digital Monitoring Best Practices, 2021", target: "Paper-based records -> data entry lag -> incomplete documentation" }
    ],
    innovation: [
      { label: "Drone-Based Easement Surveillance", type: "STRATEGY", evidence: "B", description: "Integrate UAS drone flights into monitoring rotations for large or inaccessible easement parcels. Drones provide high-resolution orthomosaics that capture conditions impossible to observe from ground-level transects.", cite: "USDA-NRCS Conservation Innovation Grants, UAS Monitoring Projects, 2022", target: "Access limitations -> incomplete assessment -> blind spots" },
      { label: "GIS Analyst Skill Development", type: "COACHING", evidence: "B", description: "Provide GIS and remote sensing training for stewardship staff to enable in-house spatial analysis of easement parcels. Internal geospatial capacity reduces dependence on consultants and accelerates change detection workflows.", cite: "ESRI Conservation GIS Program, Training Resources, 2023", target: "External dependence -> slow analysis -> delayed response" },
      { label: "Blockchain Easement Registry Pilot", type: "STRUCTURAL", evidence: "C", description: "Pilot a distributed ledger system for recording easement deed restrictions, amendments, and ownership transfers in a tamper-proof format. Blockchain registries address the perpetuity challenge of maintaining records across centuries.", cite: "Hilty et al., Conservation Easement Monitoring and Enforcement, Conservation Biology, 2023", target: "Record fragility -> disputed terms -> legal challenges" },
      { label: "Inter-Organization Data Sharing Norms", type: "CULTURE", evidence: "B", description: "Establish data-sharing agreements among land trusts, government agencies, and backup holders to create regional easement monitoring networks. Collaborative monitoring culture prevents orphaned easements when organizations dissolve.", cite: "Land Trust Alliance State of Land Conservation, 2021", target: "Organizational silos -> orphaned easements -> enforcement gaps" },
      { label: "LiDAR Topographic Change Mapping", type: "TOOLS", evidence: "B", description: "Use repeat LiDAR surveys to detect topographic alterations such as fill, grading, or drainage modification on eased parcels. Sub-meter elevation change detection identifies violations invisible to optical imagery.", cite: "USGS 3D Elevation Program (3DEP), Applications in Land Conservation, 2022", target: "Subtle terrain changes -> undetected modifications -> easement degradation" }
    ],
    economics: [
      { label: "Endowment Investment Policy Optimization", type: "STRATEGY", evidence: "A", description: "Develop a formal investment policy statement for stewardship endowments balancing growth with liquidity requirements for annual monitoring draws. Proper endowment management ensures inflation-adjusted funding in perpetuity.", cite: "Land Trust Alliance Financial Standards Advisory Council, 2020", target: "Inflation erosion -> underfunded monitoring -> deferred stewardship" },
      { label: "Board Financial Literacy on Easement Costs", type: "COACHING", evidence: "B", description: "Train land trust board members on the full lifecycle costs of easement stewardship including monitoring, legal defense, and amendment processing. Financially literate boards make better acquisition decisions and set adequate endowment minimums.", cite: "Land Trust Alliance Accreditation Requirements, Indicator 6A, 2019", target: "Underestimated costs -> underfunded endowments -> organizational stress" },
      { label: "Legal Defense Fund Reserve Policy", type: "STRUCTURAL", evidence: "A", description: "Maintain a dedicated legal defense fund separate from stewardship endowments, sized to cover at least one major enforcement action. Legal defense costs can reach six figures per case and must not drain monitoring budgets.", cite: "Lindstrom, T., A Tax Guide to Conservation Easements, Island Press, 2008", target: "Unfunded legal risk -> inability to enforce -> precedent erosion" },
      { label: "Regional Cost-Sharing Consortium", type: "CULTURE", evidence: "B", description: "Form regional consortia of land trusts to share monitoring costs, legal defense expenses, and specialist staff across multiple organizations. Cost-sharing reduces per-organization burden and builds mutual defense capacity.", cite: "Merenlender et al., Land Trusts Can Help Address Monitoring Challenges, Frontiers in Ecology, 2004", target: "Isolated costs -> small-org vulnerability -> enforcement avoidance" },
      { label: "Stewardship Cost Tracking Dashboard", type: "TOOLS", evidence: "B", description: "Deploy accounting software dashboards that track per-easement stewardship costs against endowment draws and flag underfunded properties. Granular cost tracking enables data-driven endowment minimum recalibration.", cite: "Land Trust Alliance Financial Health Assessment Tool, 2021", target: "Opaque costs -> misallocated funds -> stewardship shortfalls" }
    ]
  }) ? 1 : 0;

  // 2. ACEP Programs
  count += addTreatments('p2_agri_landuse_easements_acepprograms.json', {
    diagnostics: [
      { label: "ACEP Eligibility Pre-Screening Protocol", type: "STRATEGY", evidence: "A", description: "Implement systematic pre-screening of candidate parcels against ACEP-ALE and ACEP-WRE eligibility criteria before investing in full applications. Pre-screening prevents wasted effort on ineligible tracts and prioritizes competitive submissions.", cite: "USDA-NRCS ACEP Program Manual, Title 440, Part 528, 2023", target: "Unscreened applications -> high rejection rate -> wasted resources" },
      { label: "NRCS Application Scoring Mentorship", type: "COACHING", evidence: "B", description: "Pair novice applicants with experienced ACEP participants to review ranking criteria and strengthen application narratives. Mentored applications score significantly higher on competitive ranking factors.", cite: "USDA-NRCS Conservation Programs Ranking Process Guidance, 2022", target: "Weak applications -> low ranking -> funding denial" },
      { label: "Dedicated ACEP Coordinator Position", type: "STRUCTURAL", evidence: "A", description: "Establish a staff position focused exclusively on federal easement program administration, compliance tracking, and reporting deadlines. Dedicated coordinators maintain institutional knowledge across multi-year funding cycles.", cite: "National Association of Conservation Districts, Capacity Assessment, 2021", target: "Diffused responsibility -> missed deadlines -> forfeited funding" },
      { label: "Landowner ACEP Information Workshops", type: "CULTURE", evidence: "B", description: "Host annual informational workshops explaining ACEP benefits, obligations, and application timelines to agricultural landowners. Community education builds a pipeline of willing participants and reduces misconceptions about perpetual restrictions.", cite: "USDA-NRCS Outreach and Education Strategy, 2022", target: "Low awareness -> thin applicant pool -> undersubscribed allocations" },
      { label: "ACEP Application Tracking Spreadsheet", type: "TOOLS", evidence: "B", description: "Maintain a comprehensive tracking system documenting all pending applications, ranking scores, funding cycles, and required documentation milestones. Systematic tracking prevents administrative lapses that disqualify otherwise competitive applications.", cite: "Land Trust Alliance ACEP Application Guidance, 2023", target: "Missed milestones -> incomplete packets -> disqualification" }
    ],
    practices: [
      { label: "Matching Fund Strategy Development", type: "STRATEGY", evidence: "A", description: "Develop a proactive matching-fund strategy leveraging state programs, private foundations, and landowner donations to meet ACEP cost-share requirements. Diversified match sources improve application competitiveness and reduce dependence on any single funder.", cite: "USDA-NRCS ACEP Fact Sheet, Match Requirements, 2023", target: "Single-source match -> funding fragility -> project cancellation" },
      { label: "Appraisal Standards Compliance Training", type: "COACHING", evidence: "A", description: "Train appraisers and staff on Uniform Appraisal Standards for Federal Land Acquisitions (Yellow Book) requirements specific to ACEP transactions. Non-compliant appraisals are the leading cause of ACEP closing delays.", cite: "Uniform Appraisal Standards for Federal Land Acquisitions (Yellow Book), 2016", target: "Non-compliant appraisals -> closing delays -> expired authorizations" },
      { label: "Title Clearance Pipeline Protocol", type: "STRUCTURAL", evidence: "A", description: "Establish a standardized title review pipeline that identifies and resolves liens, mineral rights reservations, and boundary disputes early in the ACEP process. Title defects discovered late in closing create costly delays and project failures.", cite: "USDA-NRCS ACEP Closing Procedures, Title 440-CPM-528, 2023", target: "Late title defects -> closing delays -> authorization expiration" },
      { label: "Cross-Entity ACEP Knowledge Network", type: "CULTURE", evidence: "B", description: "Facilitate regular knowledge exchanges among land trusts, SWCD offices, and NRCS field staff to share ACEP best practices and lessons learned. Cross-entity learning accelerates program adoption and reduces repeated mistakes.", cite: "National Association of Conservation Districts, Partnership Building Guide, 2021", target: "Knowledge silos -> repeated errors -> inefficient program delivery" },
      { label: "NRCS Protracts Mapping Integration", type: "TOOLS", evidence: "B", description: "Integrate NRCS Protracts GIS layers with parcel data to automatically identify ACEP-eligible lands based on soil quality, wetland status, and conservation priority rankings. Automated spatial screening accelerates candidate identification.", cite: "USDA-NRCS Geospatial Data Gateway, 2023", target: "Manual screening -> slow identification -> missed funding windows" }
    ],
    innovation: [
      { label: "Performance-Based Easement Valuation", type: "STRATEGY", evidence: "C", description: "Pilot ecosystem services quantification to supplement traditional appraisal methods for ACEP-WRE wetland easements. Performance-based valuation captures carbon sequestration, flood attenuation, and habitat values that traditional appraisals undercount.", cite: "Kroeger & Casey, An Assessment of Market-Based Approaches to Biodiversity Conservation, 2007", target: "Undervalued services -> insufficient compensation -> landowner reluctance" },
      { label: "Federal Program Navigation Coaching", type: "COACHING", evidence: "B", description: "Provide individualized coaching on navigating concurrent federal programs such as CRP-to-ACEP transitions and RCPP-ACEP combinations. Program stacking knowledge maximizes landowner financial benefit and conservation impact per dollar spent.", cite: "USDA-NRCS RCPP-ACEP Integration Guidance, 2023", target: "Program confusion -> missed combinations -> suboptimal outcomes" },
      { label: "Digital Deed Template Standardization", type: "STRUCTURAL", evidence: "B", description: "Develop standardized digital deed templates that auto-populate ACEP-required provisions, subordination language, and reserved rights clauses. Template standardization reduces legal review cycles and prevents missing required provisions.", cite: "USDA-OGC Model ACEP-ALE Deed Language, 2022", target: "Custom deed drafting -> OGC review delays -> extended closings" },
      { label: "ACEP Success Story Communication", type: "CULTURE", evidence: "B", description: "Publish and distribute ACEP success stories featuring local landowner testimonials to normalize perpetual easement participation in agricultural communities. Peer influence from respected community members is the strongest predictor of voluntary enrollment.", cite: "Sorice et al., Social Factors in Conservation Easement Adoption, Society & Natural Resources, 2013", target: "Stigma around easements -> low enrollment -> unprotected priority lands" },
      { label: "Automated Compliance Reporting Portal", type: "TOOLS", evidence: "B", description: "Deploy a web-based portal that automates annual ACEP compliance reporting to NRCS, pre-populating data from monitoring records and financial systems. Automated reporting reduces administrative burden and eliminates late-filing penalties.", cite: "USDA-NRCS Conservation Delivery Streamlining Initiative, 2023", target: "Manual reporting -> errors and delays -> compliance flags" }
    ],
    economics: [
      { label: "Multi-Year Funding Pipeline Planning", type: "STRATEGY", evidence: "A", description: "Develop rolling 3-5 year ACEP project pipelines aligned with Farm Bill authorization cycles and state matching fund availability. Pipeline planning ensures continuous project flow and prevents boom-bust enrollment patterns.", cite: "Congressional Research Service, Agricultural Conservation Easement Program, R43504, 2023", target: "Reactive applications -> funding gaps -> inconsistent protection" },
      { label: "Landowner Tax Benefit Counseling", type: "COACHING", evidence: "A", description: "Connect ACEP participants with qualified tax advisors to optimize the interaction between federal easement payments, charitable donation deductions, and state tax credits. Proper tax planning can significantly increase the net financial benefit to participating landowners.", cite: "IRC Section 170(h); Lindstrom, A Tax Guide to Conservation Easements, 2008", target: "Uninformed tax elections -> forfeited benefits -> landowner dissatisfaction" },
      { label: "Stewardship Endowment Requirement Integration", type: "STRUCTURAL", evidence: "A", description: "Integrate stewardship endowment contributions into ACEP project budgets at the application stage rather than as an afterthought at closing. Upfront endowment planning ensures perpetual monitoring capacity without post-closing fundraising pressure.", cite: "Land Trust Alliance Standards and Practices, Standard 11A, 2019", target: "Unfunded stewardship -> deferred monitoring -> easement degradation" },
      { label: "Agricultural Community ACEP Champions", type: "CULTURE", evidence: "B", description: "Identify and support influential agricultural producers who advocate for ACEP participation within their peer networks. Farmer-to-farmer endorsement overcomes skepticism about government programs more effectively than institutional outreach.", cite: "Reimer et al., Farmer Peer Networks and Conservation Decision-Making, J. Soil Water Conservation, 2014", target: "Institutional distrust -> low uptake -> unprotected farmland" },
      { label: "Cost-Benefit Analysis Calculator", type: "TOOLS", evidence: "B", description: "Provide landowners with a spreadsheet-based calculator comparing ACEP payment plus tax benefits against alternative land use scenarios over 20-year horizons. Quantified comparisons convert abstract easement concepts into concrete financial decisions.", cite: "Nickerson & Lynch, The Effect of Farmland Protection Programs on Farmland Prices, AJAE, 2001", target: "Uncertain value proposition -> decision paralysis -> missed enrollment" }
    ]
  }) ? 1 : 0;

  // 3. Easement Appraisal
  count += addTreatments('p2_agri_landuse_easements_easementappraisal.json', {
    diagnostics: [
      { label: "Before-and-After Valuation Framework", type: "STRATEGY", evidence: "A", description: "Implement the standard before-and-after appraisal methodology comparing unrestricted fair market value against restricted value to determine easement compensation. This IRS-accepted methodology provides the legally defensible basis for both purchased and donated easement valuations.", cite: "Uniform Standards of Professional Appraisal Practice (USPAP), Standards Rule 1-4, 2024", target: "Ad hoc valuation -> IRS challenge -> donor penalty or litigation" },
      { label: "Appraiser Qualification Verification", type: "COACHING", evidence: "A", description: "Coach land trust staff on verifying that hired appraisers hold MAI or equivalent credentials and have documented experience with conservation easement assignments. Unqualified appraisers produce reports that fail IRS scrutiny and NRCS review.", cite: "Appraisal Institute, Guide Note 12: Valuation of Conservation Easements, 2019", target: "Unqualified appraisers -> deficient reports -> rejected transactions" },
      { label: "Appraisal Review Committee Protocol", type: "STRUCTURAL", evidence: "A", description: "Establish a formal internal review committee that evaluates every easement appraisal for USPAP compliance, reasonable assumptions, and defensible comparable selection before submission. Internal review catches deficiencies before regulatory review.", cite: "Yellow Book (UASFLA), Section B-6 Review Appraisal Standards, 2016", target: "Unreviewed reports -> regulatory rejection -> closing delays" },
      { label: "Landowner Appraisal Process Education", type: "CULTURE", evidence: "B", description: "Educate landowners on the appraisal process timeline, cost responsibility, and the distinction between appraisal value and offering price before engagement. Transparent communication prevents unrealistic expectations that derail negotiations.", cite: "Land Trust Alliance, Conservation Easement Appraisal Best Practices, 2020", target: "Unrealistic expectations -> failed negotiations -> lost conservation opportunities" },
      { label: "Comparable Sales Database System", type: "TOOLS", evidence: "B", description: "Maintain an internal database of verified agricultural land sales, easement-encumbered sales, and development-rights transactions for appraiser reference. A curated comparable database improves appraisal accuracy in thin rural markets.", cite: "Appraisal Institute, The Appraisal of Real Estate, 15th Ed., 2020", target: "Sparse comparables -> unsupported values -> challenged appraisals" }
    ],
    practices: [
      { label: "Highest-and-Best-Use Analysis Rigor", type: "STRATEGY", evidence: "A", description: "Require appraisers to provide a thorough highest-and-best-use analysis documenting the legally permissible, physically possible, financially feasible, and maximally productive use of the unencumbered property. Weak HBU analysis is the most common IRS audit finding.", cite: "IRC Section 170(h); IRS Conservation Easement Audit Technique Guide, 2022", target: "Superficial HBU analysis -> inflated values -> IRS penalties" },
      { label: "Appraiser Engagement Scope Letter Training", type: "COACHING", evidence: "B", description: "Train staff on drafting precise engagement letters that specify appraisal purpose, intended use, client identity, and applicable standards without influencing the appraiser's conclusions. Proper engagement documentation is a USPAP Ethics Rule requirement.", cite: "USPAP Ethics Rule, Appraisal Foundation, 2024", target: "Vague engagement -> scope misunderstandings -> non-compliant reports" },
      { label: "Tri-Party Appraisal Cost Sharing", type: "STRUCTURAL", evidence: "B", description: "Establish cost-sharing protocols among landowner, land trust, and funding agency for appraisal and review appraisal expenses, documented in writing before engagement. Clear cost allocation prevents disputes that delay transactions.", cite: "USDA-NRCS ACEP-ALE Appraisal Cost Guidance, 2023", target: "Cost disputes -> delayed engagement -> missed funding windows" },
      { label: "Appraiser Agricultural Literacy Standard", type: "CULTURE", evidence: "B", description: "Cultivate a network of appraisers with demonstrated agricultural knowledge including crop productivity, irrigation value, and farm infrastructure assessment. Agricultural illiteracy among appraisers leads to systematic misvaluation of farming operations.", cite: "American Society of Farm Managers and Rural Appraisers, Accreditation Standards, 2023", target: "Agricultural ignorance -> misvalued farmland -> inaccurate easement values" },
      { label: "Automated Appraisal Checklist Validator", type: "TOOLS", evidence: "B", description: "Deploy a digital checklist tool that validates appraisal reports against USPAP, Yellow Book, and IRS requirements before submission. Automated compliance checking catches missing elements that trigger regulatory rejection.", cite: "Appraisal Foundation, USPAP Compliance Checklist, 2024", target: "Missing elements -> regulatory rejection -> re-engagement costs" }
    ],
    innovation: [
      { label: "Spatial Hedonic Modeling Integration", type: "STRATEGY", evidence: "B", description: "Incorporate spatial hedonic regression models that account for proximity, soil quality, water access, and development pressure into easement valuation support. Statistical modeling supplements traditional comparable analysis in data-sparse rural markets.", cite: "Nickerson & Lynch, The Effect of Farmland Protection Programs on Farmland Prices, AJAE, 2001", target: "Comparable scarcity -> unsupported adjustments -> vulnerable valuations" },
      { label: "Advanced Valuation Methods Workshop", type: "COACHING", evidence: "B", description: "Host workshops training appraisers on advanced techniques including subdivision development analysis, discounted cash flow for agricultural income, and paired-sales extraction for easement discounts. Advanced methods strengthen valuations in complex assignments.", cite: "Appraisal Institute, Advanced Conservation Easement Valuation Course, 2023", target: "Limited methodology -> one-dimensional analysis -> weak reports" },
      { label: "Automated Valuation Model Screening", type: "STRUCTURAL", evidence: "C", description: "Use automated valuation models as preliminary screening tools to flag outlier appraisals before formal review. AVM benchmarks provide an objective reference point for identifying potentially inflated or deflated valuations.", cite: "Brookings Institution, Automated Valuation Models in Real Estate, 2021", target: "Undetected outliers -> regulatory challenge -> organizational liability" },
      { label: "Appraisal Transparency Standards", type: "CULTURE", evidence: "B", description: "Adopt and promote transparency standards requiring full disclosure of assumptions, limitations, and extraordinary assumptions in all easement appraisals. Transparency culture deters the inflated valuations that have triggered IRS enforcement actions industrywide.", cite: "IRS Notice 2017-10; Treasury OIG Report on Conservation Easement Abuses, 2020", target: "Opaque assumptions -> inflated values -> industry credibility erosion" },
      { label: "GIS-Based Comparable Mapping Tool", type: "TOOLS", evidence: "B", description: "Provide appraisers with GIS tools that spatially map verified comparable sales relative to the subject property, adjusting for distance, soil class, and land use. Spatial visualization improves comparable selection defensibility.", cite: "ESRI ArcGIS for Real Estate Valuation, Application Guide, 2022", target: "Poor comparable selection -> unsupported adjustments -> audit vulnerability" }
    ],
    economics: [
      { label: "Appraisal Contingency Budget Reserve", type: "STRATEGY", evidence: "A", description: "Budget for appraisal contingencies including supplemental reports, review appraisals, and update appraisals within every easement project pro forma. Appraisal cost overruns are common and can stall transactions when unbudgeted.", cite: "USDA-NRCS ACEP Financial Management Guidance, 2023", target: "Unbudgeted overruns -> stalled transactions -> lost funding" },
      { label: "IRS Audit Defense Preparedness", type: "COACHING", evidence: "A", description: "Coach land trust staff and participating landowners on IRS audit procedures, documentation retention requirements, and the importance of contemporaneous written acknowledgment. Audit preparedness is essential given increased IRS scrutiny of conservation easement deductions.", cite: "IRS Conservation Easement Audit Technique Guide, 2022", target: "Unprepared participants -> costly audits -> deterred future donors" },
      { label: "Appraisal Fee Schedule Standardization", type: "STRUCTURAL", evidence: "B", description: "Negotiate standardized fee schedules with qualified appraiser panels to ensure cost predictability across multiple projects. Fee standardization enables accurate project budgeting and prevents price gouging in tight appraiser markets.", cite: "Appraisal Institute, Engagement Practices and Fee Guidelines, 2023", target: "Unpredictable fees -> budget overruns -> project scope reduction" },
      { label: "Charitable Deduction Best Practices Norm", type: "CULTURE", evidence: "A", description: "Promote community norms around conservative, defensible easement valuations rather than maximizing charitable deduction amounts. The IRS has disallowed billions in inflated easement deductions, creating reputational damage for the entire conservation easement field.", cite: "IRS News Release IR-2022-189; Treasury Inspector General Report, 2020", target: "Aggressive valuations -> enforcement actions -> public trust erosion" },
      { label: "Appraisal Timeline Gantt Chart Template", type: "TOOLS", evidence: "B", description: "Use project management timeline templates tracking appraisal milestones from engagement through delivery, review, and submission against funding deadlines. Timeline visualization identifies critical path bottlenecks before they cause missed deadlines.", cite: "Land Trust Alliance, Transaction Efficiency Toolkit, 2021", target: "Untracked milestones -> deadline surprises -> expired authorizations" }
    ]
  }) ? 1 : 0;

  // 4. Tax Deductions (Easements)
  count += addTreatments('p2_agri_landuse_easements_taxdeductions.json', {
    diagnostics: [
      { label: "Deduction Eligibility Diagnostic Checklist", type: "STRATEGY", evidence: "A", description: "Apply a structured diagnostic checklist verifying all IRC Section 170(h) qualified conservation purpose requirements before a landowner commits to a donated easement. Early eligibility screening prevents costly investments in non-qualifying transactions.", cite: "IRC Section 170(h); Treasury Regulation 1.170A-14, 2023", target: "Unverified eligibility -> denied deductions -> landowner financial harm" },
      { label: "Tax Advisor Coordination Training", type: "COACHING", evidence: "A", description: "Train land trust staff to coordinate effectively with landowners' CPAs and tax attorneys on documentation requirements, contemporaneous written acknowledgment, and Form 8283 preparation. Poor coordination between land trusts and tax advisors is a primary source of deduction challenges.", cite: "IRS Form 8283 Instructions; IRC Section 170(f)(8), 2023", target: "Miscommunication -> documentation gaps -> deduction denial" },
      { label: "Contemporaneous Acknowledgment Protocol", type: "STRUCTURAL", evidence: "A", description: "Implement a mandatory protocol ensuring contemporaneous written acknowledgment letters meeting IRS requirements are delivered to donors before tax filing deadlines. Courts have denied multi-million dollar deductions solely for defective acknowledgment letters.", cite: "IRS Pub 1771, Charitable Contributions Substantiation, 2023", target: "Defective acknowledgment -> denied deduction -> litigation" },
      { label: "Donor Intent Documentation Norm", type: "CULTURE", evidence: "B", description: "Establish organizational norms requiring thorough documentation of donor conservation intent and motivation independent of tax benefits. IRS challenges often focus on whether tax benefits were the primary motivation, and intent documentation supports qualified purpose.", cite: "Treasury Regulation 1.170A-14(h)(3); Kiva Dunes Conservation case, 2009", target: "Undocumented intent -> quid pro quo allegations -> deduction disallowance" },
      { label: "Form 8283 Automated Preparation Tool", type: "TOOLS", evidence: "B", description: "Deploy software that auto-populates Form 8283 (Noncash Charitable Contributions) from appraisal data and transaction records, flagging incomplete fields. Automated preparation reduces the filing errors that trigger IRS correspondence audits.", cite: "IRS Form 8283 and Instructions, 2023", target: "Manual preparation -> filing errors -> audit triggers" }
    ],
    practices: [
      { label: "Enhanced Conservation Purpose Documentation", type: "STRATEGY", evidence: "A", description: "Develop comprehensive conservation purpose narratives in deed language that document specific scenic, ecological, agricultural, or historic values protected. Enhanced purpose documentation strengthens the legal foundation against IRS challenges to qualified conservation purpose.", cite: "IRC Section 170(h)(4); Treasury Regulation 1.170A-14(d), 2023", target: "Generic purpose language -> IRS challenge -> deduction denial" },
      { label: "Carryforward Period Planning Guidance", type: "COACHING", evidence: "A", description: "Coach donors on the 15-year carryforward period for qualified farmer and rancher donations and the 5-year carryforward for other donors, including AGI limitation planning. Strategic carryforward planning maximizes the usable tax benefit of large easement donations.", cite: "IRC Section 170(b)(1)(E); Enhanced Deduction for Qualified Farmers, 2023", target: "Carryforward ignorance -> expired deductions -> lost tax benefit" },
      { label: "State Tax Credit Integration Process", type: "STRUCTURAL", evidence: "A", description: "Build a standardized process for coordinating federal deductions with state conservation tax credits where available, including transferable credit markets. State credits can provide additional 10-75% of easement value depending on jurisdiction.", cite: "Virginia Land Conservation Incentives Act; Colorado Conservation Easement Tax Credit, 2023", target: "Uncoordinated credits -> missed state benefits -> suboptimal landowner return" },
      { label: "Ethical Valuation Culture Reinforcement", type: "CULTURE", evidence: "A", description: "Reinforce organizational commitment to conservative, defensible valuations by declining to participate in transactions where appraisals appear inflated. Syndicated conservation easement abuses have prompted IRS to list certain transactions as abusive tax shelters.", cite: "IRS Notice 2017-10; Listed Transaction Designation, 2022", target: "Inflated valuations -> listed transaction designation -> industry damage" },
      { label: "Tax Benefit Projection Spreadsheet", type: "TOOLS", evidence: "B", description: "Provide donors with a spreadsheet model projecting after-tax benefit across multiple scenarios including varying AGI levels, carryforward utilization, and state credit interaction. Quantified projections enable informed donor decision-making.", cite: "Lindstrom, A Tax Guide to Conservation Easements, Island Press, 2008", target: "Uncertain tax benefit -> donor hesitation -> missed conservation opportunity" }
    ],
    innovation: [
      { label: "Post-TCJA Deduction Strategy Adaptation", type: "STRATEGY", evidence: "B", description: "Adapt easement donation strategies to account for Tax Cuts and Jobs Act provisions including increased standard deduction thresholds that reduce itemizer populations. TCJA nearly doubled the standard deduction, requiring new approaches to reach potential donors.", cite: "Tax Cuts and Jobs Act of 2017, Section 11021; JCT Revenue Estimates, 2018", target: "Reduced itemizers -> smaller donor pool -> fewer easement donations" },
      { label: "Syndicated Easement Risk Education", type: "COACHING", evidence: "A", description: "Educate landowners and advisors about IRS enforcement actions against syndicated conservation easement transactions, including listed transaction reporting requirements. Informed participants avoid arrangements that carry severe penalty exposure.", cite: "IRS Notice 2017-10; IRS IR-2022-189, Syndicated Conservation Easement Enforcement, 2022", target: "Syndication participation -> penalties and interest -> financial devastation" },
      { label: "Perpetuity Extinguishment Proceeds Clause", type: "STRUCTURAL", evidence: "A", description: "Ensure all donated easement deeds contain legally compliant extinguishment proceeds clauses meeting Treasury Regulation requirements for division of proceeds on judicial extinguishment. Missing or non-compliant proceeds clauses can invalidate the entire deduction.", cite: "Treasury Regulation 1.170A-14(g)(6); Coal Property Holdings case, 2023", target: "Non-compliant clause -> full deduction denial -> catastrophic donor loss" },
      { label: "Professional Advisor Certification Network", type: "CULTURE", evidence: "B", description: "Build a vetted network of CPAs, tax attorneys, and financial advisors with demonstrated conservation easement expertise who commit to ethical practice standards. Quality advisor networks protect landowners from incompetent or unethical tax advice.", cite: "AICPA Conservation Easement Practice Standards, 2022", target: "Unvetted advisors -> aggressive positions -> audit exposure" },
      { label: "IRS Guidance Monitoring Alert System", type: "TOOLS", evidence: "B", description: "Subscribe to automated monitoring services tracking IRS notices, revenue rulings, Tax Court decisions, and legislative proposals affecting conservation easement deductions. Real-time guidance tracking enables proactive strategy adjustment.", cite: "IRS Priority Guidance Plan, 2023-2024; Tax Court Conservation Easement Case Docket", target: "Outdated strategies -> non-compliance -> unexpected liability" }
    ],
    economics: [
      { label: "Donation vs. Sale Economic Analysis", type: "STRATEGY", evidence: "A", description: "Conduct formal economic analysis comparing full donation deduction value against bargain-sale combinations and full purchase scenarios for each prospective easement. Optimal structure depends on the landowner's specific tax situation, basis, and liquidity needs.", cite: "IRC Section 1011(b); Bargain Sale Rules; Lindstrom, Tax Guide to Conservation Easements, 2008", target: "Suboptimal structure -> reduced landowner benefit -> fewer easements" },
      { label: "Estate Planning Integration Coaching", type: "COACHING", evidence: "A", description: "Coach landowners on integrating easement donations into comprehensive estate plans, including IRC Section 2031(c) estate tax exclusion for land subject to qualified conservation easements. Easement-estate integration can reduce estate tax liability by up to 40% of protected land value.", cite: "IRC Section 2031(c); Estate Tax Exclusion for Conservation Easement Land, 2023", target: "Isolated planning -> missed estate benefits -> unnecessary tax burden" },
      { label: "Charitable Deduction Cap Tracking System", type: "STRUCTURAL", evidence: "A", description: "Implement a tracking system that monitors AGI-based deduction caps across donor portfolios to optimize timing and sizing of easement donations. Cap management prevents donors from losing deduction value to expired carryforwards.", cite: "IRC Section 170(b)(1)(E); 50% AGI limit for qualified farmers and ranchers", target: "Untracked caps -> expired carryforwards -> lost deduction value" },
      { label: "Post-Donation Stewardship Commitment Culture", type: "CULTURE", evidence: "B", description: "Cultivate donor understanding that tax deductions create a public investment requiring perpetual stewardship commitment. Donors who understand the public trust dimension of their deduction become long-term stewardship partners rather than one-time transactors.", cite: "McLaughlin, N., Conservation Easements: Perpetuity and Beyond, Ecology Law Quarterly, 2007", target: "Transactional mindset -> disengaged donors -> unfunded stewardship" },
      { label: "After-Tax Benefit Visualization Dashboard", type: "TOOLS", evidence: "B", description: "Deploy interactive dashboards that visualize cumulative after-tax benefit over the carryforward period under various income scenarios. Visual benefit modeling converts complex tax calculations into intuitive donor decision support.", cite: "Land Trust Alliance, Donor Communication Toolkit, 2021", target: "Abstract tax math -> donor confusion -> stalled decisions" }
    ]
  }) ? 1 : 0;

  console.log(`\nEasements batch: ${count}/4 files processed`);
}

if (batch === 'leasing') {
  // 5. Cash Rent
  count += addTreatments('p2_agri_landuse_leasing_cashrent.json', {
    diagnostics: [
      { label: "Annual Cash Rent Benchmarking Survey", type: "STRATEGY", evidence: "A", description: "Conduct annual surveys comparing local cash rent rates against USDA-NASS county-level averages and university extension published rates. Benchmarking prevents both over- and under-pricing that erodes tenant profitability or landlord returns.", cite: "USDA-NASS Cash Rents Survey, Annual Release; Iowa State Extension Ag Decision Maker, 2023", target: "Uninformed pricing -> suboptimal rates -> tenant loss or landlord shortfall" },
      { label: "Tenant Financial Health Assessment Training", type: "COACHING", evidence: "B", description: "Train landlords on reviewing tenant financial indicators including working capital ratios, debt-to-asset ratios, and crop insurance coverage as predictors of rent payment reliability. Financial assessment skills prevent leasing to operators at high default risk.", cite: "Langemeier, M., Financial Benchmarking, Purdue Center for Commercial Agriculture, 2023", target: "Unvetted tenants -> payment defaults -> income disruption" },
      { label: "Written Lease Requirement Policy", type: "STRUCTURAL", evidence: "A", description: "Require all cash rent arrangements to be documented in written leases specifying payment terms, maintenance obligations, conservation compliance, and termination provisions. Oral leases expose both parties to legal ambiguity and are unenforceable in many jurisdictions for terms exceeding one year.", cite: "Uniform Commercial Code; State Statute of Frauds provisions; ISU Extension FM 1564, 2022", target: "Oral agreements -> disputed terms -> costly litigation" },
      { label: "Landlord-Tenant Communication Norms", type: "CULTURE", evidence: "B", description: "Establish regular communication expectations between landlords and tenants including pre-season planning meetings and post-harvest financial reviews. Open communication culture prevents relationship deterioration that leads to lease non-renewals.", cite: "Duffy, M., Farmland Ownership and Tenure in Iowa, ISU Extension, 2022", target: "Poor communication -> relationship erosion -> tenant turnover" },
      { label: "USDA-NASS Rent Data Dashboard", type: "TOOLS", evidence: "A", description: "Deploy a dashboard integrating USDA-NASS Cash Rents Survey data with local soil productivity ratings and county-level commodity price projections. Data-driven rent analysis replaces anecdotal pricing with defensible market-based rates.", cite: "USDA-NASS Cash Rents Survey; USDA-NRCS Web Soil Survey, 2023", target: "Anecdotal pricing -> market misalignment -> competitive disadvantage" }
    ],
    practices: [
      { label: "Soil Productivity-Indexed Rent Pricing", type: "STRATEGY", evidence: "A", description: "Index cash rent rates to soil productivity indices such as CSR2 (Corn Suitability Rating) or PI (Productivity Index) to ensure rent reflects actual yield capacity of each field. Productivity-based pricing eliminates cross-subsidization between high and low quality fields within a farm.", cite: "Iowa State Extension, ISU Farmland Value Survey; CSR2 Rating System, 2023", target: "Flat-rate pricing -> quality misalignment -> tenant dissatisfaction" },
      { label: "Lease Negotiation Skills Workshop", type: "COACHING", evidence: "B", description: "Provide landlords and tenants with structured negotiation training covering interest-based bargaining, BATNA analysis, and creative deal structuring. Skilled negotiation produces durable lease agreements that survive commodity price volatility.", cite: "ASFMRA, Lease Negotiation Best Practices, Journal of ASFMRA, 2021", target: "Positional bargaining -> impasse -> relationship damage" },
      { label: "Automatic Escalation Clause Framework", type: "STRUCTURAL", evidence: "B", description: "Incorporate lease escalation clauses tied to objective indices such as USDA-NASS published county averages or university extension recommended rates. Automatic escalation prevents the negotiation fatigue that leads to stale rents below market value.", cite: "ISU Extension FM 1811, Cash Rent with Bonus, 2022", target: "Static rates -> inflation erosion -> landlord wealth loss" },
      { label: "Conservation Compliance Lease Culture", type: "CULTURE", evidence: "A", description: "Embed conservation compliance expectations directly into cash rent lease terms, making conservation plan adherence a condition of lease renewal. Conservation-linked leases align tenant practices with landlord stewardship goals and USDA program eligibility.", cite: "USDA-FSA Conservation Compliance Requirements, 7 CFR Part 12, 2023", target: "Misaligned incentives -> soil degradation -> FSA eligibility loss" },
      { label: "Lease Comparison Calculator Tool", type: "TOOLS", evidence: "A", description: "Provide a spreadsheet calculator comparing net returns across cash rent, crop share, flex lease, and custom farming arrangements for specific soil types and commodity price scenarios. Side-by-side comparison tools enable evidence-based lease structure selection.", cite: "Purdue Extension, Farmland Lease Comparison Worksheet, EC-715, 2023", target: "Default lease choice -> suboptimal structure -> forgone income" }
    ],
    innovation: [
      { label: "Variable Rate Rent Pilot Program", type: "STRATEGY", evidence: "B", description: "Pilot variable-rate cash rent structures that adjust payment based on realized county yield or commodity price triggers, sharing production risk between landlord and tenant. Variable-rate designs retain cash rent simplicity while adding downside protection for tenants.", cite: "Plastina, A., Variable Cash Rent Leases, ISU Extension, 2023", target: "Fixed rent rigidity -> tenant financial stress -> default risk" },
      { label: "Precision Agriculture Data Integration Coaching", type: "COACHING", evidence: "B", description: "Coach landlords on interpreting precision agriculture data including yield maps, satellite imagery, and variable-rate application records to inform rent negotiations. Data-literate landlords make better decisions about field-specific rent adjustments.", cite: "Schnitkey, G., Precision Agriculture and Farm Leasing, UIUC farmdoc, 2022", target: "Data illiteracy -> uninformed negotiations -> value loss" },
      { label: "Online Lease Auction Platform Integration", type: "STRUCTURAL", evidence: "C", description: "Evaluate online farmland lease auction platforms as price-discovery mechanisms for competitive cash rent determination. Auction platforms provide transparent market clearing prices but may damage long-term landlord-tenant relationships.", cite: "Kirwan, B., The Incidence of US Agricultural Subsidies on Farmland Rental Rates, JPE, 2009", target: "Opaque pricing -> disputed fair value -> relationship strain" },
      { label: "Tenant Stewardship Recognition Program", type: "CULTURE", evidence: "B", description: "Create recognition programs rewarding tenants who demonstrate exceptional soil health improvement, conservation practice adoption, or land stewardship on rented ground. Public recognition motivates stewardship behavior that benefits both parties long-term.", cite: "SARE, Building Soils for Better Crops, Sustainable Agriculture Network, 2021", target: "Undervalued stewardship -> short-term extraction -> declining productivity" },
      { label: "Real-Time Market Price Alert System", type: "TOOLS", evidence: "B", description: "Deploy commodity price and basis monitoring tools that alert landlords and tenants when trigger prices in variable-rate lease provisions are approached. Automated alerts enable timely rent adjustment decisions without constant market monitoring.", cite: "CME Group, Agricultural Commodity Price Data; USDA-AMS Market News, 2023", target: "Missed triggers -> incorrect payments -> lease disputes" }
    ],
    economics: [
      { label: "Cash Rent-to-Revenue Ratio Analysis", type: "STRATEGY", evidence: "A", description: "Calculate rent-to-gross-revenue ratios for each field to ensure rents remain within the 30-40% range that research identifies as sustainable for both parties. Ratios above 40% indicate unsustainable tenant cost structures; below 25% suggest landlord underpricing.", cite: "Schnitkey & Sherrick, Cash Rent-to-Revenue Ratios, UIUC farmdoc daily, 2023", target: "Unsustainable ratios -> tenant bankruptcy or landlord loss -> lease failure" },
      { label: "Landlord Tax Optimization Coaching", type: "COACHING", evidence: "A", description: "Coach landlords on distinguishing material participation from passive rental income for self-employment tax purposes and the implications for QBI deductions under IRC Section 199A. Proper tax classification can save thousands annually on rental income.", cite: "IRC Section 199A; IRS Publication 225, Farmer's Tax Guide, 2023", target: "Incorrect classification -> overpaid taxes -> reduced net return" },
      { label: "Multi-Year Lease Stability Framework", type: "STRUCTURAL", evidence: "B", description: "Design 3-5 year lease frameworks with annual rent resets based on published indices to provide tenant operational stability while protecting landlord market-rate returns. Multi-year terms reduce transaction costs and encourage tenant investment in soil health.", cite: "ASFMRA, Multi-Year Lease Design Guide, 2022", target: "Annual churn -> high transaction costs -> underinvestment" },
      { label: "Absentee Landlord Engagement Initiative", type: "CULTURE", evidence: "B", description: "Develop outreach programs targeting absentee landlords who control over 50% of rented cropland, providing education on market rates, conservation obligations, and management options. Engaged absentee owners make better leasing decisions than disengaged inheritors relying on outdated arrangements.", cite: "Bigelow et al., USDA-ERS Farmland Ownership, Tenure, and Transfer, EIB-161, 2016", target: "Disengaged owners -> below-market rents -> mismanaged land" },
      { label: "Net Return Scenario Modeling Spreadsheet", type: "TOOLS", evidence: "A", description: "Deploy spreadsheet models projecting landlord net returns after taxes, insurance, and maintenance under varying rent levels and commodity price scenarios. Scenario modeling enables informed decisions about rent levels and lease structure alternatives.", cite: "University of Illinois farmdoc, Annual Cash Rent Analysis Tools, 2023", target: "Single-scenario thinking -> surprise losses -> reactive adjustments" }
    ]
  }) ? 1 : 0;

  // 6. Crop Share
  count += addTreatments('p2_agri_landuse_leasing_cropshare.json', {
    diagnostics: [
      { label: "Input Cost Sharing Ratio Audit", type: "STRATEGY", evidence: "A", description: "Conduct annual audits of landlord-tenant input cost sharing ratios against published extension guidelines to ensure equitable distribution relative to crop share percentages. Misaligned cost shares create economic friction that destabilizes long-term lease relationships.", cite: "Edwards, W., Crop-Share Lease Provisions, ISU Extension FM 1813, 2023", target: "Inequitable cost shares -> partner resentment -> lease dissolution" },
      { label: "Crop Share vs Cash Rent Decision Coaching", type: "COACHING", evidence: "A", description: "Coach landowners on the risk-return tradeoffs between crop share and cash rent arrangements using historical yield and price data for their specific county. Informed structure selection aligns lease type with each party's risk tolerance and financial capacity.", cite: "Schnitkey, G., Crop Share vs Cash Rent Returns, UIUC farmdoc, 2023", target: "Mismatched risk preference -> financial stress -> lease abandonment" },
      { label: "Shared Expense Documentation System", type: "STRUCTURAL", evidence: "A", description: "Implement a formalized documentation system for all shared input costs including seed, fertilizer, chemical, and crop insurance premium allocations. Written expense records prevent end-of-season disputes that poison landlord-tenant relationships.", cite: "ASFMRA, Crop Share Lease Documentation Standards, 2022", target: "Undocumented expenses -> disputed allocations -> legal conflict" },
      { label: "Pre-Season Planning Meeting Tradition", type: "CULTURE", evidence: "B", description: "Establish a cultural expectation of annual pre-season planning meetings where landlord and tenant jointly review input plans, marketing strategies, and expense budgets before planting. Joint planning meetings build trust and prevent unilateral decisions that surprise the other party.", cite: "Duffy, M., Improving Landlord-Tenant Relations, ISU Extension, 2022", target: "Unilateral decisions -> partner distrust -> adversarial relationship" },
      { label: "Crop Share Equity Calculator", type: "TOOLS", evidence: "A", description: "Deploy a calculator that computes the implied return-on-investment for both landlord and tenant under various share and cost-sharing scenarios. Equity analysis ensures neither party subsidizes the other beyond their proportionate share contribution.", cite: "Purdue Extension, Crop Share Lease Analysis Tool, EC-713, 2023", target: "Hidden subsidies -> inequitable returns -> unsustainable arrangement" }
    ],
    practices: [
      { label: "Standard Share Rate Calibration", type: "STRATEGY", evidence: "A", description: "Calibrate crop share percentages to local norms and land quality using the contributions-based approach where each party's share reflects their proportionate resource contribution. The standard 50-50 or 60-40 splits should be adjusted based on actual landlord contributions to inputs.", cite: "ISU Extension FM 1813; USDA-ERS Farmland Tenure Publications, 2023", target: "Default splits -> misaligned contributions -> partner inequity" },
      { label: "Marketing Decision Protocol Training", type: "COACHING", evidence: "B", description: "Train both parties on grain marketing decision protocols including who has authority to price the landlord's share, delivery timing, and basis risk allocation. Marketing miscommunication is a leading source of crop share disputes.", cite: "Edwards, W., Marketing the Landlord's Share, ISU Extension AG Decision Maker, 2022", target: "Unclear marketing authority -> pricing disputes -> financial loss" },
      { label: "Government Payment Allocation Framework", type: "STRUCTURAL", evidence: "A", description: "Establish clear written provisions for dividing ARC/PLC payments, ad hoc disaster payments, and crop insurance indemnities between landlord and tenant. Government payment allocation must align with the crop share split to prevent windfall disputes.", cite: "USDA-FSA ARC/PLC Payment Division Guidance; 7 CFR Part 1412, 2023", target: "Ambiguous payment allocation -> windfall disputes -> legal action" },
      { label: "Transparent Yield Reporting Culture", type: "CULTURE", evidence: "B", description: "Build a culture of transparent yield reporting using calibrated yield monitors, scale tickets, and third-party verification when disputes arise. Trust in yield accounting is the foundation of every crop share arrangement.", cite: "ASFMRA, Ethical Standards for Farm Managers, 2023", target: "Yield disputes -> trust breakdown -> lease termination" },
      { label: "Split-Payment Accounting Software", type: "TOOLS", evidence: "B", description: "Deploy farm accounting software that automatically calculates landlord and tenant shares of revenue, expenses, and government payments based on lease terms. Automated split accounting eliminates manual calculation errors and provides audit-ready documentation.", cite: "Farm Bureau Financial Services, Farm Lease Accounting Guide, 2022", target: "Manual calculations -> accounting errors -> disputed settlements" }
    ],
    innovation: [
      { label: "Precision Yield-Based Share Adjustment", type: "STRATEGY", evidence: "C", description: "Pilot share percentage adjustments based on precision agriculture yield data for individual fields rather than whole-farm averages. Field-specific shares align incentives with actual productivity variation across the leased operation.", cite: "Schnitkey, G., Precision Agriculture and Lease Design, UIUC farmdoc, 2022", target: "Whole-farm averaging -> cross-subsidized fields -> misaligned incentives" },
      { label: "Variable Input Technology Decision Coaching", type: "COACHING", evidence: "B", description: "Coach landlords on evaluating tenant variable-rate technology investments and their impact on shared input costs and yields. Precision technology costs must be fairly allocated when they benefit both parties through increased shared revenue.", cite: "Plastina & Johanns, Precision Ag and Farm Leases, ISU Extension, 2023", target: "Technology cost disputes -> adoption resistance -> forgone yield gains" },
      { label: "Hybrid Share-Flex Lease Design", type: "STRUCTURAL", evidence: "B", description: "Design hybrid lease structures combining base crop share with flex bonus provisions triggered by commodity prices exceeding specified thresholds. Hybrid designs balance the risk-sharing of crop share with the upside protection tenants value in high-price environments.", cite: "Langemeier, M., Hybrid Lease Arrangements, Purdue Center for Commercial Agriculture, 2023", target: "Rigid structures -> missed optimization -> suboptimal risk allocation" },
      { label: "Regenerative Practice Cost Sharing Norms", type: "CULTURE", evidence: "B", description: "Develop cost-sharing norms for cover crops, reduced tillage, and other regenerative practices that build long-term soil value on shared land. Landlords who share regenerative practice costs signal commitment to the partnership and the land's future productivity.", cite: "SARE, Cover Crop Economics, National Cover Crop Survey, 2023", target: "Unshared practice costs -> tenant resistance -> soil degradation" },
      { label: "Cloud-Based Grain Marketing Platform", type: "TOOLS", evidence: "B", description: "Adopt cloud-based grain marketing platforms that give both parties real-time visibility into pricing decisions, storage costs, and delivery schedules for the shared crop. Platform transparency prevents marketing disputes that arise from information asymmetry.", cite: "Grain Bridge/Bushel, Grain Marketing Technology Platforms, 2023", target: "Information asymmetry -> marketing disputes -> relationship damage" }
    ],
    economics: [
      { label: "Break-Even Yield Analysis Per Share", type: "STRATEGY", evidence: "A", description: "Calculate break-even yields for both landlord and tenant under current input costs and commodity price assumptions to identify the sustainability floor for the arrangement. Break-even analysis reveals whether current shares are viable before financial stress triggers default.", cite: "Schnitkey & Lattz, Break-Even Analysis for Crop Share Leases, UIUC farmdoc, 2023", target: "Unknown break-even -> surprise losses -> forced restructuring" },
      { label: "Self-Employment Tax Implications Coaching", type: "COACHING", evidence: "A", description: "Coach landlords on self-employment tax liability under crop share arrangements where material participation creates SE tax obligations not present under cash rent. SE tax exposure can add 15.3% to the landlord's tax burden and should factor into structure selection.", cite: "IRC Section 1402; IRS Publication 225, 2023", target: "SE tax surprise -> unexpected liability -> structure regret" },
      { label: "Annual Settlement Reconciliation Process", type: "STRUCTURAL", evidence: "A", description: "Establish a formalized annual settlement reconciliation process with documented input invoices, yield records, and payment calculations reviewed by both parties. Systematic reconciliation prevents cumulative accounting errors that compound over multi-year leases.", cite: "ASFMRA, Farm Lease Settlement Best Practices, 2022", target: "Unreconciled accounts -> accumulated errors -> disputed settlements" },
      { label: "Intergenerational Share Transition Planning", type: "CULTURE", evidence: "B", description: "Promote cultural norms around proactive communication when either the landlord or tenant family is undergoing generational transition. Crop share leases are highly relationship-dependent, and generational transitions are the most common termination trigger.", cite: "Duffy, M., Farm Succession and Lease Continuity, ISU Extension, 2022", target: "Surprise transitions -> lease disruption -> operational chaos" },
      { label: "Historical Return Comparison Dashboard", type: "TOOLS", evidence: "B", description: "Build a dashboard comparing realized crop share returns against hypothetical cash rent returns over 10+ year periods to evaluate long-term structure performance. Historical comparison identifies whether crop share is actually delivering superior risk-adjusted returns.", cite: "UIUC farmdoc, Historical Cash Rent vs Crop Share Return Analysis, 2023", target: "Untested assumptions -> suboptimal structure persistence -> opportunity cost" }
    ]
  }) ? 1 : 0;

  // 7. Flexible Leases
  count += addTreatments('p2_agri_landuse_leasing_flexibleleases.json', {
    diagnostics: [
      { label: "Base Rent Floor Calibration", type: "STRATEGY", evidence: "A", description: "Calibrate the guaranteed base rent floor at 70-80% of prevailing cash rent to provide landlord income security while leaving room for upside bonus triggers. Properly calibrated floors protect landlords during low-price years without eliminating tenant participation in upside.", cite: "Plastina, A., Flexible Farm Lease Design, ISU Extension PM 1995, 2023", target: "Poorly set floor -> landlord under-protection or tenant over-burden -> lease failure" },
      { label: "Trigger Mechanism Selection Coaching", type: "COACHING", evidence: "A", description: "Coach parties on selecting appropriate flex lease trigger variables comparing county yield, farm yield, commodity price, and gross revenue triggers. Each trigger type allocates different risk components and must match the parties' risk preferences.", cite: "Schnitkey, G., Selecting Flex Lease Triggers, UIUC farmdoc daily, 2023", target: "Mismatched triggers -> unintended risk allocation -> partner dissatisfaction" },
      { label: "Written Flex Provision Specification", type: "STRUCTURAL", evidence: "A", description: "Require all flex lease trigger formulas, data sources, calculation methods, and payment timing to be specified in writing with worked examples. Ambiguous flex provisions generate disputes when trigger conditions are met and parties disagree on calculations.", cite: "ISU Extension FM 1811, Cash Rent with Bonus Provisions, 2022", target: "Vague provisions -> calculation disputes -> relationship damage" },
      { label: "Transparent Data Source Agreement", type: "CULTURE", evidence: "A", description: "Establish mutual agreement on objective third-party data sources for trigger variables such as USDA-NASS county yields and CME settlement prices. Data source agreement eliminates subjective disputes when calculating bonus or adjustment payments.", cite: "Edwards, W., Flex Lease Data Sources, ISU Extension AG Decision Maker, 2022", target: "Disputed data -> contested calculations -> adversarial relationship" },
      { label: "Flex Lease Scenario Modeling Tool", type: "TOOLS", evidence: "A", description: "Deploy a spreadsheet tool that models flex lease payments across a matrix of yield and price scenarios showing outcomes for both parties. Visual scenario modeling reveals how the flex formula behaves across the full range of market conditions before signing.", cite: "Purdue Extension, Flex Lease Calculator, EC-718, 2023", target: "Untested formulas -> surprise outcomes -> post-signing disputes" }
    ],
    practices: [
      { label: "Bonus Cap and Floor Guardrails", type: "STRATEGY", evidence: "A", description: "Incorporate maximum bonus caps and minimum payment floors into flex lease formulas to bound outcomes within acceptable ranges for both parties. Guardrails prevent extreme outcomes that create financial hardship for either landlord or tenant.", cite: "Plastina & Edwards, Bounded Flex Lease Design, ISU Extension, 2023", target: "Unbounded formulas -> extreme outcomes -> partner financial stress" },
      { label: "Annual Flex Formula Review Protocol", type: "COACHING", evidence: "B", description: "Coach parties on conducting annual reviews of flex formula parameters against current market conditions and adjusting base rates or trigger thresholds as needed. Static formulas designed for one market environment become misaligned as conditions shift.", cite: "Schnitkey, G., Annual Flex Lease Calibration, UIUC farmdoc, 2023", target: "Stale parameters -> misaligned incentives -> lease abandonment" },
      { label: "Settlement Date Calendar System", type: "STRUCTURAL", evidence: "A", description: "Establish fixed settlement dates when trigger data becomes available and bonus calculations are due, with written notification requirements. Missing settlement dates creates cash flow uncertainty and administrative disputes.", cite: "ASFMRA, Lease Administration Calendar Standards, 2022", target: "Missed deadlines -> payment uncertainty -> cash flow disruption" },
      { label: "Yield Data Transparency Expectations", type: "CULTURE", evidence: "B", description: "Build cultural expectations that tenants share yield monitor data and scale tickets openly with landlords when farm-level yield triggers are used. Opacity around farm-level yield data breeds landlord suspicion and undermines the trust required for flex arrangements.", cite: "Duffy, M., Trust in Farm Lease Relationships, ISU Extension, 2022", target: "Hidden yield data -> landlord suspicion -> relationship deterioration" },
      { label: "USDA County Yield Data Access Tool", type: "TOOLS", evidence: "A", description: "Provide both parties with direct access to USDA-NASS Quick Stats and RMA county yield databases for verifying trigger calculations. Independent data access ensures both parties can verify calculations without relying on the other's reporting.", cite: "USDA-NASS Quick Stats; USDA-RMA County Yield Data, 2023", target: "Unverifiable triggers -> contested payments -> legal disputes" }
    ],
    innovation: [
      { label: "Revenue-Based Flex Formula Design", type: "STRATEGY", evidence: "B", description: "Design flex formulas based on gross revenue (yield times price) rather than single-variable triggers to capture the natural hedge between yield and price. Revenue-based triggers smooth outcomes better than single-variable formulas because low yields often coincide with high prices.", cite: "Langemeier, M., Revenue-Based Flex Leases, Purdue Center for Commercial Agriculture, 2023", target: "Single-variable triggers -> volatile outcomes -> partner dissatisfaction" },
      { label: "Risk Management Integration Coaching", type: "COACHING", evidence: "B", description: "Coach tenants on integrating flex lease obligations into crop insurance and forward contracting strategies to manage total risk exposure. Flex lease payments interact with insurance indemnities and forward contract obligations in ways tenants must understand.", cite: "Schnitkey, G., Risk Management and Flex Leases, UIUC farmdoc, 2022", target: "Uncoordinated risk tools -> unexpected net positions -> financial stress" },
      { label: "Multi-Tier Bonus Structure Framework", type: "STRUCTURAL", evidence: "B", description: "Design multi-tier bonus structures with escalating payment percentages at successive yield or price thresholds. Tiered structures allow modest sharing at moderate outcomes while increasing landlord participation during exceptional years.", cite: "Plastina, A., Tiered Flex Lease Structures, ISU Extension, 2023", target: "Flat-rate bonuses -> poor incentive alignment -> suboptimal sharing" },
      { label: "Peer Flex Lease Benchmarking Groups", type: "CULTURE", evidence: "B", description: "Organize confidential peer groups where landlords compare flex lease outcomes and formula designs to identify best practices. Peer benchmarking accelerates the adoption of superior flex designs while maintaining individual confidentiality.", cite: "Farm Financial Standards Council, Peer Benchmarking Best Practices, 2022", target: "Isolated design -> suboptimal formulas -> missed improvement opportunity" },
      { label: "Automated Trigger Monitoring Dashboard", type: "TOOLS", evidence: "B", description: "Deploy automated monitoring tools that track commodity prices and yield estimates against flex lease trigger thresholds in real time. Real-time monitoring helps both parties anticipate bonus payment obligations for cash flow planning.", cite: "DTN/Progressive Farmer, Market Data Tools; USDA Crop Progress Reports, 2023", target: "Surprise triggers -> cash flow disruption -> payment delays" }
    ],
    economics: [
      { label: "Risk Premium Quantification Analysis", type: "STRATEGY", evidence: "A", description: "Quantify the implied risk premium landlords sacrifice by accepting flex lease base rents below straight cash rent levels, comparing expected value of bonus payments against the guaranteed income reduction. Risk premium analysis ensures the flex structure offers adequate expected compensation for the landlord's shared risk.", cite: "Schnitkey & Sherrick, Risk Premium in Flex Leases, UIUC farmdoc, 2023", target: "Unquantified risk transfer -> landlord undercompensation -> structure abandonment" },
      { label: "Tax Treatment of Bonus Payments", type: "COACHING", evidence: "A", description: "Coach both parties on the tax treatment of flex lease bonus payments, including timing recognition and self-employment tax implications. Bonus payment timing creates tax planning opportunities and obligations that both parties must understand.", cite: "IRC Section 61; IRS Publication 225, Farmer's Tax Guide, 2023", target: "Incorrect tax treatment -> IRS adjustment -> unexpected liability" },
      { label: "Escrow Account for Bonus Payments", type: "STRUCTURAL", evidence: "B", description: "Establish escrow accounts for bonus payment accrual when settlement timing differs from the crop marketing period. Escrow arrangements prevent cash flow mismatches when bonus payments are owed before or after the tenant has monetized the crop.", cite: "ASFMRA, Lease Financial Administration Standards, 2022", target: "Cash flow mismatch -> delayed payments -> trust erosion" },
      { label: "Flex Lease Innovation Adoption Norm", type: "CULTURE", evidence: "B", description: "Promote cultural acceptance of flex lease innovation as a risk management tool rather than a gamble, emphasizing the structural advantages over rigid cash rent during volatile commodity cycles. Reframing flex leases as prudent risk management overcomes landlord resistance rooted in income certainty preference.", cite: "Kirwan, B., Agricultural Risk and Farmland Leasing, JPE, 2009", target: "Risk aversion stigma -> low adoption -> missed risk-sharing benefits" },
      { label: "Historical Flex vs Cash Rent Comparison Tool", type: "TOOLS", evidence: "A", description: "Build comparison tools showing hypothetical flex lease outcomes against actual cash rent payments over 10-20 year periods using local yield and price history. Historical backtesting demonstrates whether flex structures would have outperformed cash rent for the specific location.", cite: "UIUC farmdoc, Historical Lease Structure Comparison Database, 2023", target: "Theoretical arguments -> unconvincing -> evidence-based adoption" }
    ]
  }) ? 1 : 0;

  // 8. Lease Terms
  count += addTreatments('p2_agri_landuse_leasing_leaseterms.json', {
    diagnostics: [
      { label: "Lease Term Completeness Audit", type: "STRATEGY", evidence: "A", description: "Audit existing leases against a comprehensive checklist of essential provisions including payment terms, maintenance obligations, conservation requirements, sublease restrictions, and termination procedures. Incomplete leases create legal ambiguity that breeds disputes during changing circumstances.", cite: "ISU Extension, Iowa Farm Lease Form, FM 1564 Checklist, 2023", target: "Missing provisions -> ambiguity -> costly disputes" },
      { label: "State-Specific Lease Law Training", type: "COACHING", evidence: "A", description: "Train landlords and tenants on state-specific agricultural lease statutes including notice requirements, holdover provisions, default remedies, and right-of-first-refusal obligations. State lease law varies significantly and ignorance creates unintentional violations with costly consequences.", cite: "National Agricultural Law Center, State Agricultural Lease Law Compendium, 2023", target: "Legal ignorance -> statutory violations -> unenforceable provisions" },
      { label: "Standard Lease Template Library", type: "STRUCTURAL", evidence: "A", description: "Maintain a library of attorney-reviewed, state-specific lease templates covering cash rent, crop share, flex, and custom arrangements with optional conservation addenda. Standardized templates ensure legal compliance while reducing drafting costs.", cite: "North Central Farm Management Extension Committee, Lease Templates, 2023", target: "Custom drafting -> inconsistent quality -> legal vulnerability" },
      { label: "Timely Notice Compliance Culture", type: "CULTURE", evidence: "A", description: "Instill a culture of strict compliance with statutory notice deadlines for lease termination, modification, and renewal communications. Missed notice deadlines can create automatic holdover tenancies lasting an additional full crop year.", cite: "State Notice Statutes; Iowa Code Section 562.6; Illinois 735 ILCS 5/9-206, 2023", target: "Missed notice -> holdover tenancy -> lost flexibility" },
      { label: "Lease Expiration Tracking Calendar", type: "TOOLS", evidence: "A", description: "Deploy a calendar system that generates advance alerts for lease notice deadlines, renewal dates, payment due dates, and conservation compliance review periods. Automated deadline tracking prevents the most common and costly lease administration errors.", cite: "ASFMRA, Farm Management Best Practices, Lease Administration, 2023", target: "Manual tracking -> missed deadlines -> forced holdover or default" }
    ],
    practices: [
      { label: "Conservation Addendum Integration", type: "STRATEGY", evidence: "A", description: "Incorporate conservation practice addenda into all lease agreements specifying soil health requirements, cover crop expectations, waterway maintenance, and USDA conservation compliance obligations. Lease-based conservation requirements are the most effective tool for protecting rented land from extractive management.", cite: "AFT, Conservation Lease Toolkit, American Farmland Trust, 2023", target: "Absent conservation terms -> extractive practices -> soil degradation" },
      { label: "Right-of-First-Refusal Counseling", type: "COACHING", evidence: "B", description: "Counsel both parties on the implications of right-of-first-refusal provisions, including valuation mechanics, exercise timelines, and financing contingencies. ROFR provisions are widely misunderstood and create disputes when triggered by actual sale events.", cite: "National Agricultural Law Center, Right of First Refusal in Farm Leases, 2022", target: "Misunderstood ROFR -> sale obstruction -> litigation" },
      { label: "Improvement and Fixture Ownership Clause", type: "STRUCTURAL", evidence: "A", description: "Include explicit provisions addressing ownership of tenant-installed improvements, fixtures, and infrastructure at lease termination, including removal rights and compensation formulas. Fixture disputes at lease termination are among the most contentious and costly agricultural lease conflicts.", cite: "Uniform Commercial Code Article 2A; State Fixture Law Summaries, 2023", target: "Ambiguous fixture ownership -> termination disputes -> court intervention" },
      { label: "Mutual Respect and Good Faith Norms", type: "CULTURE", evidence: "B", description: "Embed good faith dealing expectations in lease preambles and reinforce them through regular communication. Agricultural leases are long-term relationships where good faith norms reduce transaction costs more effectively than exhaustive legal provisions.", cite: "Restatement (Second) of Contracts, Section 205; ASFMRA Ethics Standards, 2023", target: "Adversarial stance -> excessive legalism -> relationship erosion" },
      { label: "Side-by-Side Lease Comparison Matrix", type: "TOOLS", evidence: "B", description: "Provide a matrix tool comparing key provisions across multiple lease offers or structures, highlighting differences in payment terms, conservation requirements, and termination provisions. Structured comparison supports informed decision-making when evaluating competing lease options.", cite: "Purdue Extension, Lease Evaluation Framework, EC-714, 2023", target: "Unstructured comparison -> overlooked terms -> suboptimal lease selection" }
    ],
    innovation: [
      { label: "Soil Health Outcome Lease Provisions", type: "STRATEGY", evidence: "B", description: "Pilot lease provisions that tie rent adjustments to measurable soil health outcomes such as organic matter percentage, aggregate stability, or infiltration rates. Outcome-based provisions create direct financial incentives for soil building rather than prescriptive practice requirements.", cite: "Soil Health Institute, Soil Health Measurement Framework, 2023", target: "Practice-based terms -> compliance without outcomes -> continued degradation" },
      { label: "Mediation Clause Inclusion Coaching", type: "COACHING", evidence: "B", description: "Coach parties on the benefits of including agricultural mediation clauses as a prerequisite to litigation for lease disputes. Mediation resolves lease disputes faster, cheaper, and with higher satisfaction rates than court proceedings.", cite: "USDA Certified Agricultural Mediation Programs, 7 USC 5101, 2023", target: "Direct-to-litigation -> high costs -> relationship destruction" },
      { label: "Digital Lease Execution and Storage", type: "STRUCTURAL", evidence: "B", description: "Adopt digital lease execution platforms with electronic signatures and cloud-based document storage for permanent accessibility. Digital systems eliminate lost lease documents and provide instant access during disputes or ownership transitions.", cite: "ESIGN Act; State Uniform Electronic Transactions Acts, 2023", target: "Paper-only records -> lost documents -> unverifiable terms" },
      { label: "Next-Generation Farmer Lease Mentorship", type: "CULTURE", evidence: "B", description: "Create mentorship programs pairing experienced farm operators with beginning farmers navigating their first lease negotiations. Beginning farmers lack negotiating experience and institutional knowledge about fair lease terms, making them vulnerable to disadvantageous agreements.", cite: "USDA Beginning Farmer and Rancher Development Program, 2023", target: "Inexperienced negotiators -> unfavorable terms -> early business failure" },
      { label: "Lease Document Assembly Software", type: "TOOLS", evidence: "B", description: "Deploy document assembly software that generates customized lease agreements from standardized clause libraries based on user-selected options. Assembly tools combine standardization benefits with customization flexibility while maintaining legal compliance.", cite: "American Bar Association, Document Assembly Technology Guide, 2022", target: "Manual drafting -> inconsistency and errors -> legal risk" }
    ],
    economics: [
      { label: "Lease Term Length Optimization", type: "STRATEGY", evidence: "A", description: "Analyze optimal lease term length balancing landlord flexibility against tenant investment incentives, considering that tenants on short-term leases systematically underinvest in soil conservation. Research shows 3-5 year terms with renewal options optimize both parties' interests.", cite: "Soule et al., Lease Tenure and Conservation Practice Adoption, AJAE, 1999", target: "Year-to-year terms -> tenant underinvestment -> declining productivity" },
      { label: "Lease Termination Cost Analysis", type: "COACHING", evidence: "B", description: "Coach landlords on the full costs of tenant turnover including search costs, transition-year yield depression, relationship building time, and potential conservation plan disruption. Turnover cost awareness encourages landlords to invest in relationship maintenance over marginal rent increases.", cite: "Bigelow et al., Tenant Turnover and Farmland Productivity, USDA-ERS, 2016", target: "Underestimated turnover costs -> excessive churning -> net value destruction" },
      { label: "Inflation Adjustment Mechanism Design", type: "STRUCTURAL", evidence: "B", description: "Build inflation adjustment mechanisms into multi-year leases tied to published agricultural indices rather than general CPI. Agricultural input cost inflation frequently diverges from general inflation, and inappropriate indices create systematic mispricing.", cite: "USDA-ERS Prices Paid by Farmers Index; ISU Extension Lease Adjustment Guide, 2023", target: "General CPI adjustment -> agricultural cost divergence -> inequitable outcomes" },
      { label: "Fair Lease Practices Community Standard", type: "CULTURE", evidence: "B", description: "Promote community standards for fair lease practices through extension workshops, farm bureau programs, and peer networks. Community-enforced fairness norms reduce exploitative lease terms that extract short-term value at the expense of long-term land and community health.", cite: "Ranjan et al., Social Norms and Agricultural Leasing, J. Soil Water Conservation, 2020", target: "Exploitative terms -> community degradation -> long-term value loss" },
      { label: "Lease Payment Schedule Optimizer", type: "TOOLS", evidence: "B", description: "Provide a tool for designing payment schedules aligned with tenant cash flow from grain marketing, including split-payment options and deferred payment arrangements. Payment schedule optimization reduces tenant cash flow stress during input-heavy pre-harvest months.", cite: "Purdue Extension, Farm Cash Flow Management, EC-720, 2023", target: "Misaligned payment timing -> cash flow stress -> default risk" }
    ]
  }) ? 1 : 0;

  console.log(`\nLeasing batch: ${count}/4 files processed`);
}

console.log('Done with batch:', batch);
