const fs = require('fs');
const path = require('path');

const DOMAIN_DIR = path.join(__dirname, '..', 'assets', 'data', 'domains');

// All 32 L4 fertilizer files with their topic-specific treatments
const TREATMENTS = {
  "p2_agri_fertilizer_apptiming_preplantapplication": {
    "Monitoring & Assessment": [
      { label: "Pre-Plant Soil Nutrient Baseline Testing", type: "STRATEGY", evidence: "A", description: "Establish a systematic pre-plant soil sampling protocol at 0-6 and 6-12 inch depths to quantify residual N, P, and K before any fertilizer application. Baseline data enables precise rate adjustments and prevents over-application. Results should be compared against regional sufficiency levels.", cite: "NRCS CPS 590 (Nutrient Management); SSSA Methods of Soil Analysis, 2018", target: "Baseline soil data -> Accurate rate adjustment -> Reduced over-application" },
      { label: "Coaching Staff on Sample Timing", type: "COACHING", evidence: "B", description: "Train field scouts and agronomists on optimal pre-plant sampling windows, emphasizing the importance of sampling after fall residue decomposition but before spring application. Proper timing avoids misleading nitrate values from recent mineralization flushes.", cite: "University of Illinois Extension Bulletin, Soil Sampling for Nutrient Management, 2020", target: "Trained personnel -> Correct sample timing -> Reliable nutrient baselines" },
      { label: "Zone-Based Sampling Infrastructure", type: "STRUCTURAL", evidence: "A", description: "Implement management-zone delineation using yield maps, EC data, and topography to define sampling zones that capture field variability. Zone-based sampling replaces uniform grid approaches where spatial variability is high, improving the representativeness of pre-plant nutrient assessments.", cite: "NRCS CPS 590; ASABE S358.3 Moisture Measurement Standard", target: "Zone delineation -> Representative sampling -> Targeted pre-plant rates" },
      { label: "Pre-Plant Assessment Review Culture", type: "CULTURE", evidence: "B", description: "Establish a pre-season review meeting where agronomy staff compare prior-year pre-plant test results with actual yield outcomes. This feedback loop builds organizational learning and drives continuous improvement in assessment accuracy.", cite: "Agronomy Journal, Vol. 112, Issue 3, 2020", target: "Annual review practice -> Data-driven learning -> Improved assessment accuracy" },
      { label: "GPS-Enabled Soil Probe Systems", type: "TOOLS", evidence: "A", description: "Deploy GPS-referenced hydraulic soil probes that geotag each sample location for repeatable annual monitoring. Geo-referenced data enables multi-year trend analysis of pre-plant nutrient levels across management zones.", cite: "NRCS CPS 590; Precision Agriculture, Vol. 21, 2020", target: "Geo-tagged samples -> Multi-year trend tracking -> Adaptive pre-plant planning" }
    ],
    "Applied Practices": [
      { label: "Fall Broadcast with Incorporation", type: "STRATEGY", evidence: "A", description: "Apply P and K fertilizers in fall with immediate incorporation via tillage to place nutrients in the root zone before spring planting. Fall application distributes workload and leverages freeze-thaw cycles to improve nutrient distribution in the soil profile.", cite: "NRCS CPS 590; University of Minnesota Extension, Fertilizer Application Timing, 2019", target: "Fall broadcast -> Tillage incorporation -> Root-zone nutrient availability" },
      { label: "Operator Calibration Training", type: "COACHING", evidence: "B", description: "Conduct annual spreader calibration clinics where operators verify application rates against target rates using catch-pan tests. Proper calibration ensures uniform distribution and prevents streaking or skips that cause yield variability.", cite: "ASABE S341.5 Procedure for Measuring Distribution Uniformity", target: "Calibration training -> Uniform application -> Consistent crop response" },
      { label: "Dedicated Pre-Plant Equipment Fleet", type: "STRUCTURAL", evidence: "B", description: "Maintain a dedicated fleet of application equipment sized for the pre-plant window to avoid bottlenecks. Equipment readiness checklists and preventive maintenance schedules ensure reliability during the narrow application window.", cite: "ASABE EP496.3 Agricultural Machinery Management", target: "Dedicated equipment -> Reduced downtime -> Timely pre-plant completion" },
      { label: "Neighbor Cooperative Application Days", type: "CULTURE", evidence: "C", description: "Organize cooperative pre-plant application days where neighboring operations share equipment and labor to complete applications efficiently. Shared resources reduce individual capital requirements and build community resilience against weather delays.", cite: "Journal of Extension, Vol. 58, No. 4, 2020", target: "Cooperative sharing -> Efficient resource use -> Timely field coverage" },
      { label: "Variable-Rate Spinner Spreaders", type: "TOOLS", evidence: "A", description: "Utilize variable-rate spinner spreaders with section control capable of adjusting rates on-the-go based on prescription maps. Section control eliminates overlap at headlands and field boundaries, reducing input waste by 5-15%.", cite: "NRCS CPS 590; ASABE S341.5; Precision Agriculture, Vol. 19, 2018", target: "VR spreaders -> Prescription-based rates -> Reduced input waste" }
    ],
    "Technology & Innovation": [
      { label: "Satellite-Guided Application Planning", type: "STRATEGY", evidence: "B", description: "Integrate satellite imagery and weather forecast models to optimize the pre-plant application window. Remote sensing data identifies field trafficability conditions, reducing soil compaction risk from premature field entry.", cite: "Remote Sensing of Environment, Vol. 234, 2019", target: "Satellite data -> Optimal timing decisions -> Reduced compaction risk" },
      { label: "Precision Ag Technology Mentoring", type: "COACHING", evidence: "C", description: "Pair experienced precision agriculture practitioners with operators new to technology-driven pre-plant application. Hands-on mentoring during actual field operations accelerates technology adoption and builds confidence in data-driven decisions.", cite: "Journal of Extension, Vol. 57, No. 2, 2019", target: "Peer mentoring -> Faster tech adoption -> Improved application precision" },
      { label: "Cloud-Based Data Integration Platform", type: "STRUCTURAL", evidence: "B", description: "Implement a centralized cloud platform that integrates soil test results, historical yield data, and equipment telemetry to generate pre-plant prescriptions. Unified data architecture eliminates manual data transfer errors between systems.", cite: "Computers and Electronics in Agriculture, Vol. 176, 2020", target: "Integrated platform -> Automated prescriptions -> Error-free data flow" },
      { label: "Innovation Pilot Field Protocol", type: "CULTURE", evidence: "C", description: "Designate specific field strips as technology pilot zones where new pre-plant application technologies are tested against standard practices. Side-by-side comparisons build evidence for or against adoption without risking whole-farm outcomes.", cite: "Agronomy Journal, Vol. 113, Issue 1, 2021", target: "Pilot zones -> Controlled comparison -> Evidence-based adoption" },
      { label: "RTK-GPS Auto-Steer Systems", type: "TOOLS", evidence: "A", description: "Deploy RTK-GPS auto-steer on application equipment to achieve sub-inch pass-to-pass accuracy. Precise guidance eliminates overlap and skips, ensuring uniform nutrient placement across the entire field before planting.", cite: "NRCS CPS 590; ASABE S553 Guidance Systems Standard", target: "RTK guidance -> Overlap elimination -> Uniform pre-plant coverage" }
    ],
    "Economics & Risk": [
      { label: "Pre-Season Fertilizer Price Locking", type: "STRATEGY", evidence: "A", description: "Implement forward contracting or pre-pay programs to lock in fertilizer prices before the spring application season. Early procurement reduces exposure to seasonal price spikes that typically occur during peak demand periods.", cite: "USDA-ERS Fertilizer Use and Price Report, 2022; Journal of Agricultural Economics, Vol. 73, 2022", target: "Price locking -> Reduced input cost volatility -> Predictable margins" },
      { label: "Economic Decision Training for Managers", type: "COACHING", evidence: "B", description: "Train farm managers on breakeven analysis for pre-plant fertilizer investments using current commodity prices and yield response curves. Understanding marginal returns per unit of nutrient helps optimize rates under tight margins.", cite: "University of Illinois Farmdoc Daily, Fertilizer Economics Series, 2021", target: "Economic training -> Optimized rate decisions -> Maximum ROI" },
      { label: "Multi-Year Fertilizer Budget Framework", type: "STRUCTURAL", evidence: "B", description: "Establish a rolling three-year fertilizer budget that accounts for soil test trends, commodity price forecasts, and crop rotation plans. Multi-year budgeting smooths annual cost fluctuations and enables strategic purchasing decisions.", cite: "Farm Financial Management Guide, Iowa State Extension, 2020", target: "Multi-year budgeting -> Strategic purchasing -> Cost stabilization" },
      { label: "Risk Sharing Through Co-Op Purchasing", type: "CULTURE", evidence: "B", description: "Participate in cooperative purchasing groups to negotiate volume discounts on pre-plant fertilizer products. Group buying power leverages collective demand to achieve pricing that individual operations cannot access alone.", cite: "USDA Rural Cooperative Development Program; Journal of Cooperatives, Vol. 33, 2019", target: "Co-op purchasing -> Volume discounts -> Lower per-unit cost" },
      { label: "Break-Even Calculator Spreadsheets", type: "TOOLS", evidence: "A", description: "Deploy standardized break-even calculator tools that incorporate current fertilizer prices, expected yields, and commodity values to determine economically optimal pre-plant rates. Real-time cost inputs prevent applying nutrients beyond the point of diminishing returns.", cite: "NRCS CPS 590; University of Minnesota Extension Crop Budget Tools, 2021", target: "Break-even tools -> Rate optimization -> Maximum economic return" }
    ]
  },

  "p2_agri_fertilizer_apptiming_sidedressapplication": {
    "Monitoring & Assessment": [
      { label: "In-Season Canopy Sensing Protocol", type: "STRATEGY", evidence: "A", description: "Deploy active crop canopy sensors at V6-V8 growth stage to assess real-time nitrogen status before side-dress application. Normalized difference vegetation index readings identify areas of nitrogen stress that require supplemental application.", cite: "NRCS CPS 590; Agronomy Journal, Vol. 111, Issue 5, 2019", target: "Canopy sensing -> N status assessment -> Targeted side-dress rates" },
      { label: "Scout Training for Deficiency Symptoms", type: "COACHING", evidence: "B", description: "Train crop scouts to identify visual nitrogen deficiency symptoms including lower-leaf chlorosis and V-shaped yellowing patterns in corn. Early identification enables timely side-dress intervention before yield potential is permanently reduced.", cite: "Purdue University Extension, Corn & Soybean Field Guide, 2020", target: "Trained scouts -> Early deficiency detection -> Timely intervention" },
      { label: "Pre-Sidedress Nitrate Test Program", type: "STRUCTURAL", evidence: "A", description: "Implement a structured pre-sidedress nitrate test (PSNT) program with defined sampling protocols, laboratory turnaround targets, and decision thresholds. PSNT values above 25 ppm NO3-N typically indicate sufficient residual nitrogen, avoiding unnecessary application.", cite: "NRCS CPS 590; Magdoff et al., Soil Science Society of America Journal, 1984", target: "PSNT program -> Residual N quantification -> Avoid unnecessary application" },
      { label: "Data Sharing Across Farm Teams", type: "CULTURE", evidence: "C", description: "Foster a culture of real-time data sharing where scout observations, sensor readings, and soil test results are immediately accessible to all team members via mobile platforms. Rapid information flow enables coordinated side-dress timing decisions.", cite: "Journal of Extension, Vol. 56, No. 6, 2018", target: "Real-time sharing -> Coordinated decisions -> Optimal timing" },
      { label: "Chlorophyll Meter Quick-Test Kits", type: "TOOLS", evidence: "A", description: "Use handheld SPAD chlorophyll meters to rapidly assess leaf greenness as a proxy for nitrogen status at side-dress timing. Readings from reference strips receiving excess nitrogen establish field-specific sufficiency indices for rate decisions.", cite: "Agronomy Journal, Vol. 108, Issue 4, 2016; NRCS CPS 590", target: "SPAD readings -> Sufficiency index -> Data-driven side-dress rates" }
    ],
    "Applied Practices": [
      { label: "Coulter-Injection Side-Dress Method", type: "STRATEGY", evidence: "A", description: "Apply liquid nitrogen solutions using coulter-injection equipment that places fertilizer 4-6 inches below the soil surface between crop rows. Subsurface placement reduces volatilization losses by 90% compared to surface dribble methods.", cite: "NRCS CPS 590; Soil Science Society of America Journal, Vol. 82, 2018", target: "Coulter injection -> Subsurface placement -> Minimal volatilization loss" },
      { label: "Applicator Speed and Rate Training", type: "COACHING", evidence: "B", description: "Coach equipment operators on maintaining consistent ground speed during side-dress passes to ensure uniform rate delivery. Speed variations of more than 1 mph can cause rate deviations exceeding 10% with flow-based control systems.", cite: "ASABE S341.5 Procedure for Measuring Distribution Uniformity", target: "Speed consistency training -> Uniform delivery -> Even crop response" },
      { label: "Mid-Season Application Logistics Plan", type: "STRUCTURAL", evidence: "B", description: "Develop a side-dress logistics plan that pre-positions nitrogen supply, schedules tender trucks, and maps field entry points to minimize standing crop damage. Logistics planning reduces turnaround time and maximizes acres covered per day.", cite: "ASABE EP496.3 Agricultural Machinery Management; Iowa State Extension, 2019", target: "Logistics plan -> Efficient operations -> Maximum daily coverage" },
      { label: "Growth-Stage Application Windows", type: "CULTURE", evidence: "A", description: "Establish organizational norms that prioritize side-dress application within the V6-V10 growth stage window when corn nitrogen uptake accelerates. Missing this window reduces nitrogen use efficiency and forces reliance on rescue applications.", cite: "University of Illinois Extension, N Rate Calculator Guidelines, 2021", target: "Strict timing norms -> V6-V10 application -> Maximum N use efficiency" },
      { label: "Y-Drop Applicator Systems", type: "TOOLS", evidence: "A", description: "Deploy Y-drop applicator systems that place UAN solution directly at the base of each corn plant between rows. Surface placement near the root zone at later growth stages enables application through V14 without mechanical crop damage.", cite: "360 Yield Center Technical Bulletin; Agronomy Journal, Vol. 112, 2020", target: "Y-drop placement -> Root-zone delivery -> Extended application window" }
    ],
    "Technology & Innovation": [
      { label: "Sensor-Based Variable-Rate Side-Dress", type: "STRATEGY", evidence: "A", description: "Implement on-the-go sensor-based variable-rate nitrogen application using active canopy sensors coupled to variable-rate injection systems. Real-time rate adjustments based on crop vigor optimize nitrogen delivery to match spatial demand.", cite: "NRCS CPS 590; Precision Agriculture, Vol. 20, 2019", target: "Real-time sensing -> Variable-rate delivery -> Spatially optimized N" },
      { label: "Drone Imagery Interpretation Training", type: "COACHING", evidence: "C", description: "Train agronomists to interpret multispectral drone imagery for identifying nitrogen stress zones before side-dress. Understanding NDVI and NDRE indices enables practitioners to validate sensor recommendations and override when field conditions warrant.", cite: "Remote Sensing, Vol. 12, Issue 9, 2020", target: "Imagery training -> Informed validation -> Accurate prescriptions" },
      { label: "Automated Nitrogen Recommendation Engine", type: "STRUCTURAL", evidence: "B", description: "Deploy an algorithm-driven recommendation engine that integrates weather data, soil moisture, crop growth models, and sensor readings to generate optimal side-dress timing and rate prescriptions. Automated pipelines reduce turnaround from data collection to application.", cite: "Computers and Electronics in Agriculture, Vol. 175, 2020", target: "Automated engine -> Rapid prescriptions -> Timely side-dress decisions" },
      { label: "On-Farm Technology Trial Network", type: "CULTURE", evidence: "C", description: "Build a regional network of farms conducting replicated side-dress technology trials with shared results. Collaborative trial networks generate local evidence faster than individual experiments and increase confidence in technology adoption.", cite: "Journal of Extension, Vol. 59, No. 1, 2021", target: "Trial network -> Local evidence -> Accelerated adoption" },
      { label: "Sensor-Nozzle Integrated Toolbar", type: "TOOLS", evidence: "B", description: "Install integrated sensor-nozzle toolbar systems that mount crop canopy sensors and variable-rate nozzles on the same implement. Single-pass sensing and application eliminates the delay between data collection and nitrogen delivery.", cite: "Precision Agriculture, Vol. 21, 2020; ASABE Paper No. 2000108", target: "Integrated toolbar -> Single-pass operation -> Zero delay application" }
    ],
    "Economics & Risk": [
      { label: "Split-Rate Economic Optimization", type: "STRATEGY", evidence: "A", description: "Calculate the economic optimum nitrogen rate using university-calibrated response curves specific to the region and adjust the side-dress portion based on pre-plant credits. Optimizing the split between pre-plant and side-dress maximizes return to nitrogen investment.", cite: "University of Illinois N Rate Calculator; NRCS CPS 590", target: "EONR calculation -> Optimized split ratio -> Maximum N return" },
      { label: "Margin Analysis Coaching Sessions", type: "COACHING", evidence: "B", description: "Conduct pre-season coaching sessions where agronomists walk managers through side-dress cost scenarios at different nitrogen prices and yield expectations. Understanding sensitivity to price changes enables proactive rate adjustments.", cite: "Purdue University Crop Cost & Return Guide, 2022", target: "Margin coaching -> Price sensitivity awareness -> Proactive adjustments" },
      { label: "Nitrogen Price Hedging Contracts", type: "STRUCTURAL", evidence: "B", description: "Establish forward purchasing agreements or hedging instruments to manage nitrogen price volatility during the side-dress season. Structured procurement reduces exposure to spot-market price spikes during peak demand.", cite: "USDA-ERS Fertilizer Use and Price Report, 2022", target: "Price hedging -> Volatility management -> Stable input costs" },
      { label: "Shared Equipment Cost Transparency", type: "CULTURE", evidence: "C", description: "Maintain transparent cost-per-acre tracking for side-dress operations across the organization, visible to all stakeholders. Cost transparency drives accountability and identifies opportunities for efficiency improvements.", cite: "Farm Financial Management Guide, Iowa State Extension, 2020", target: "Cost transparency -> Accountability -> Operational efficiency" },
      { label: "Side-Dress ROI Dashboard Software", type: "TOOLS", evidence: "B", description: "Deploy dashboard software that tracks side-dress nitrogen investment against yield response by field and zone. Post-season ROI analysis identifies which fields and zones generate the highest returns to side-dress nitrogen.", cite: "Computers and Electronics in Agriculture, Vol. 170, 2020", target: "ROI dashboard -> Field-level analysis -> Strategic allocation" }
    ]
  },

  "p2_agri_fertilizer_apptiming_splitnitrogen": {
    "Monitoring & Assessment": [
      { label: "Multi-Timing N Uptake Monitoring", type: "STRATEGY", evidence: "A", description: "Implement tissue testing at each split application timing to track cumulative nitrogen uptake relative to crop demand curves. Sequential monitoring validates whether earlier split doses achieved target uptake before committing to subsequent applications.", cite: "NRCS CPS 590; Agronomy Journal, Vol. 112, Issue 2, 2020", target: "Sequential tissue tests -> Uptake validation -> Adjusted subsequent splits" },
      { label: "Agronomist Coaching on Split Timing", type: "COACHING", evidence: "B", description: "Coach agronomists on interpreting growth-stage-specific nitrogen demand curves to optimize the timing of each split. Understanding the sigmoid uptake pattern ensures each application aligns with periods of maximum crop demand.", cite: "University of Wisconsin Extension, Corn Nitrogen Management, 2019", target: "Demand curve training -> Aligned timing -> Maximum uptake efficiency" },
      { label: "Season-Long Monitoring Calendar", type: "STRUCTURAL", evidence: "B", description: "Establish a fixed monitoring calendar with defined sampling dates, laboratory submission deadlines, and decision points aligned to each planned split application. Structured timelines prevent monitoring gaps that could delay critical application decisions.", cite: "NRCS CPS 590; Nutrient Management Planning Guide, USDA, 2019", target: "Fixed calendar -> Timely sampling -> No missed decision windows" },
      { label: "Cross-Team Monitoring Debriefs", type: "CULTURE", evidence: "C", description: "Hold weekly cross-team debriefs during the split application season where scout observations, sensor data, and tissue results are shared across all agronomists. Collective interpretation of monitoring data reduces individual blind spots.", cite: "Journal of Extension, Vol. 57, No. 5, 2019", target: "Weekly debriefs -> Collective interpretation -> Reduced blind spots" },
      { label: "Portable Tissue Nitrogen Analyzers", type: "TOOLS", evidence: "B", description: "Deploy portable ion-selective electrode analyzers for rapid in-field nitrate-nitrogen testing of plant tissue at each split timing. On-site analysis reduces laboratory turnaround delays from days to minutes, enabling same-day application decisions.", cite: "Soil Science Society of America Journal, Vol. 83, 2019", target: "Portable analyzers -> Rapid results -> Same-day decisions" }
    ],
    "Applied Practices": [
      { label: "Two-Third Split Allocation Protocol", type: "STRATEGY", evidence: "A", description: "Allocate one-third of total nitrogen at planting and two-thirds at side-dress to align application with peak crop demand. This 1/3-2/3 split reduces early-season leaching risk on coarse-textured soils while ensuring adequate mid-season supply.", cite: "NRCS CPS 590; University of Minnesota Extension, Nitrogen BMPs for Corn, 2020", target: "1/3-2/3 allocation -> Reduced leaching -> Peak-demand delivery" },
      { label: "Operator Split Sequence Training", type: "COACHING", evidence: "B", description: "Train equipment operators on the specific product, rate, and placement method for each split in the sequence. Clear operating procedures prevent errors when switching between products or rates across split applications.", cite: "ASABE EP496.3 Agricultural Machinery Management", target: "Sequence training -> Error prevention -> Correct rate/product per split" },
      { label: "Product Staging by Split Timing", type: "STRUCTURAL", evidence: "B", description: "Pre-stage fertilizer products at field-edge storage points organized by split timing to minimize logistics delays. Dedicated staging for each split ensures the correct product is immediately available when the application window opens.", cite: "Iowa State Extension, Nitrogen Application Logistics, 2019", target: "Pre-staged product -> Immediate availability -> No timing delays" },
      { label: "Team Commitment to Split Protocol", type: "CULTURE", evidence: "B", description: "Build team-wide commitment to the split nitrogen protocol by sharing research data on yield and efficiency gains from split applications versus single-pass programs. Evidence-based buy-in prevents reversion to single-application convenience.", cite: "Agronomy Journal, Vol. 110, Issue 6, 2018", target: "Evidence sharing -> Team buy-in -> Consistent protocol adherence" },
      { label: "Enhanced Efficiency Nitrogen Products", type: "TOOLS", evidence: "A", description: "Apply nitrification inhibitors or controlled-release nitrogen products as part of the split strategy to extend the availability window of each application. Products like N-Serve or ESN reduce losses between split timings.", cite: "NRCS CPS 590; Wolt, Soil Science Society of America Journal, 2004", target: "Inhibitors/CRF -> Extended availability -> Reduced between-split losses" }
    ],
    "Technology & Innovation": [
      { label: "Dynamic Split Ratio Optimization", type: "STRATEGY", evidence: "B", description: "Use crop simulation models integrated with real-time weather data to dynamically adjust the ratio between splits based on in-season conditions. Models like APSIM or DSSAT can predict optimal second-split rates accounting for actual mineralization and loss events.", cite: "Agricultural Systems, Vol. 178, 2020", target: "Crop simulation -> Dynamic ratios -> Weather-responsive splitting" },
      { label: "Model Interpretation Workshops", type: "COACHING", evidence: "C", description: "Conduct workshops where agronomists learn to interpret crop model outputs and translate simulation recommendations into practical split nitrogen decisions. Bridging the gap between modeling and field practice accelerates adoption of adaptive splitting.", cite: "Computers and Electronics in Agriculture, Vol. 162, 2019", target: "Model training -> Practical translation -> Informed split decisions" },
      { label: "Automated Weather-Trigger System", type: "STRUCTURAL", evidence: "C", description: "Install automated weather monitoring stations that trigger alerts when conditions favor nitrogen loss events between planned splits. Rainfall intensity, soil temperature, and saturation thresholds prompt reassessment of the remaining split schedule.", cite: "Journal of Environmental Quality, Vol. 49, 2020", target: "Weather triggers -> Loss event alerts -> Schedule reassessment" },
      { label: "Shared Innovation Trial Plots", type: "CULTURE", evidence: "C", description: "Establish multi-farm innovation trial plots comparing different split nitrogen strategies under local conditions. Shared trial data builds regional knowledge bases and reduces individual risk of testing new split protocols.", cite: "Journal of Extension, Vol. 58, No. 2, 2020", target: "Shared trials -> Regional evidence -> Lower adoption risk" },
      { label: "In-Season Nitrogen Sensor Platforms", type: "TOOLS", evidence: "A", description: "Deploy tractor-mounted or UAV-based nitrogen sensing platforms that map crop N status between split timings. High-resolution N status maps guide variable-rate adjustments for subsequent split applications.", cite: "Precision Agriculture, Vol. 22, 2021; NRCS CPS 590", target: "N sensing platforms -> Status mapping -> VR split adjustments" }
    ],
    "Economics & Risk": [
      { label: "Split vs. Single-Pass Cost Analysis", type: "STRATEGY", evidence: "A", description: "Conduct rigorous cost-benefit analysis comparing split nitrogen programs against single-pass application, accounting for additional equipment passes, labor, and nitrogen use efficiency gains. Split programs typically break even when NUE improves by 10% or more.", cite: "Journal of Agricultural Economics, Vol. 72, 2021; USDA-ERS Fertilizer Report, 2022", target: "Cost-benefit analysis -> Break-even identification -> Informed program choice" },
      { label: "Risk Communication to Stakeholders", type: "COACHING", evidence: "B", description: "Coach farm managers on communicating the risk reduction benefits of split nitrogen to lenders and crop insurance agents. Documenting lower environmental risk and more predictable yields strengthens financial relationships.", cite: "Journal of the American Society of Farm Managers, Vol. 83, 2020", target: "Risk communication -> Stakeholder confidence -> Improved financing terms" },
      { label: "Contingency Budget for Extra Passes", type: "STRUCTURAL", evidence: "B", description: "Build contingency budgets that account for the possibility of additional split applications when weather disrupts the planned schedule. Financial reserves prevent the temptation to skip a critical split due to unexpected costs.", cite: "Farm Financial Management Guide, Iowa State Extension, 2020", target: "Contingency budget -> Financial resilience -> No skipped splits" },
      { label: "Economic Transparency Across Splits", type: "CULTURE", evidence: "C", description: "Track and share the cost and yield impact of each split application separately so the entire team understands the economic contribution of each pass. Granular tracking builds appreciation for the split strategy and sustains team commitment.", cite: "Agronomy Journal, Vol. 113, Issue 2, 2021", target: "Granular tracking -> Team appreciation -> Sustained commitment" },
      { label: "Nitrogen Price Alert Subscriptions", type: "TOOLS", evidence: "B", description: "Subscribe to nitrogen price tracking services that provide real-time market data and price forecasts for planning each split purchase. Timely price information enables tactical purchasing decisions for each split timing.", cite: "USDA-ERS Fertilizer Use and Price Report, 2022; DTN Fertilizer Price Index", target: "Price alerts -> Tactical purchasing -> Lower per-split cost" }
    ]
  },

  "p2_agri_fertilizer_apptiming_fertigation": {
    "Monitoring & Assessment": [
      { label: "EC and pH Injection Monitoring", type: "STRATEGY", evidence: "A", description: "Install inline electrical conductivity and pH sensors downstream of fertilizer injection points to verify nutrient concentration in real time. Continuous monitoring ensures target nutrient levels are maintained throughout the fertigation event and detects injection failures immediately.", cite: "NRCS CPS 449 (Irrigation Water Management); ASABE S526.4 Soil and Water Terminology", target: "Inline sensors -> Real-time verification -> Consistent nutrient delivery" },
      { label: "Irrigation Operator Fertigation Training", type: "COACHING", evidence: "B", description: "Train irrigation system operators on fertigation-specific monitoring protocols including injection rate calculations, backflow prevention verification, and end-of-cycle flushing procedures. Knowledgeable operators prevent cross-contamination and ensure uniform nutrient distribution.", cite: "University of California ANR Publication 3489, Fertigation, 2019", target: "Operator training -> Correct procedures -> Uniform nutrient distribution" },
      { label: "Automated Flow Monitoring Network", type: "STRUCTURAL", evidence: "A", description: "Install flow meters at injection points and system outlets to continuously monitor fertigation solution delivery rates across the irrigation network. Flow data confirms that prescribed nutrient rates reach all zones uniformly.", cite: "NRCS CPS 449; ASABE S376.2 Design and Installation of Microirrigation Systems", target: "Flow meters -> Delivery confirmation -> Zone-uniform fertigation" },
      { label: "Fertigation Log Review Meetings", type: "CULTURE", evidence: "C", description: "Conduct weekly review meetings during the growing season where fertigation logs, flow data, and crop response observations are analyzed by the team. Regular reviews catch system drift early and maintain accountability for fertigation quality.", cite: "Journal of Irrigation and Drainage Engineering, Vol. 146, 2020", target: "Weekly reviews -> Early drift detection -> Sustained quality" },
      { label: "Suction Lysimeter Soil Solution Samplers", type: "TOOLS", evidence: "B", description: "Install suction lysimeters at multiple depths in the root zone to sample soil solution nutrient concentrations after fertigation events. Direct measurement of nutrient availability at root depth validates whether injection rates are achieving target soil concentrations.", cite: "Soil Science Society of America Journal, Vol. 84, 2020", target: "Lysimeter sampling -> Root-zone verification -> Validated injection rates" }
    ],
    "Applied Practices": [
      { label: "Pulse Fertigation Scheduling", type: "STRATEGY", evidence: "A", description: "Apply nutrients through pulsed fertigation cycles that alternate between nutrient injection and clear water flushes. Pulse scheduling improves nutrient distribution uniformity and prevents salt accumulation at emitter outlets.", cite: "NRCS CPS 449; Agricultural Water Management, Vol. 222, 2019", target: "Pulse cycles -> Improved uniformity -> Reduced salt buildup" },
      { label: "Injection Ratio Calculation Coaching", type: "COACHING", evidence: "B", description: "Coach irrigation managers on calculating correct injection ratios based on fertilizer concentration, system flow rate, and target application rate. Accurate ratio calculation prevents under- or over-dosing that leads to crop stress or nutrient waste.", cite: "University of Florida IFAS Extension, Fertigation for Citrus, 2020", target: "Ratio calculation training -> Correct dosing -> Optimal crop nutrition" },
      { label: "Backflow Prevention Compliance System", type: "STRUCTURAL", evidence: "A", description: "Install and maintain code-compliant backflow prevention devices on all fertigation injection points to protect water sources from contamination. Regular inspection and testing schedules ensure devices function correctly throughout the season.", cite: "NRCS CPS 449; ASABE S447 Safety for Agricultural Equipment", target: "Backflow prevention -> Water source protection -> Regulatory compliance" },
      { label: "Standard Fertigation Operating Procedures", type: "CULTURE", evidence: "B", description: "Develop and enforce written standard operating procedures for every fertigation event including startup, injection, monitoring, flushing, and shutdown sequences. SOPs ensure consistency regardless of which operator runs the system.", cite: "NRCS CPS 449; Irrigation Association Best Management Practices, 2020", target: "Written SOPs -> Operator consistency -> Reliable fertigation events" },
      { label: "Venturi Injection Systems", type: "TOOLS", evidence: "A", description: "Deploy Venturi-type injectors that provide proportional injection rates automatically scaled to irrigation flow. Venturi systems maintain consistent fertilizer-to-water ratios regardless of pressure fluctuations in the irrigation system.", cite: "ASABE S376.2; Agricultural Water Management, Vol. 210, 2018", target: "Venturi injectors -> Proportional dosing -> Consistent concentration" }
    ],
    "Technology & Innovation": [
      { label: "Sensor-Driven Adaptive Fertigation", type: "STRATEGY", evidence: "B", description: "Integrate soil moisture sensors, tensiometers, and nitrate probes into a closed-loop fertigation control system. Sensor feedback dynamically adjusts both water and nutrient delivery to match real-time crop demand.", cite: "Computers and Electronics in Agriculture, Vol. 180, 2021", target: "Closed-loop sensors -> Dynamic adjustment -> Demand-matched delivery" },
      { label: "IoT Dashboard Interpretation Training", type: "COACHING", evidence: "C", description: "Train agronomists on interpreting IoT dashboard data from automated fertigation systems including sensor trends, injection performance metrics, and anomaly alerts. Skilled interpretation prevents data overload and focuses attention on actionable insights.", cite: "Precision Agriculture, Vol. 22, 2021", target: "Dashboard training -> Focused interpretation -> Actionable responses" },
      { label: "Cloud-Connected Fertigation Controllers", type: "STRUCTURAL", evidence: "B", description: "Install cloud-connected irrigation controllers that enable remote monitoring and adjustment of fertigation programs from any location. Remote access allows immediate response to sensor alerts without requiring physical presence at the field.", cite: "Agricultural Water Management, Vol. 240, 2020", target: "Cloud controllers -> Remote management -> Immediate response" },
      { label: "Precision Fertigation Research Adoption", type: "CULTURE", evidence: "C", description: "Encourage teams to review and discuss published precision fertigation research at monthly meetings. Regular engagement with current research builds a culture of evidence-based practice improvement.", cite: "Irrigation Science, Vol. 39, 2021", target: "Research engagement -> Evidence-based updates -> Continuous improvement" },
      { label: "Real-Time Nutrient Sensing Probes", type: "TOOLS", evidence: "B", description: "Deploy in-soil nitrate and potassium ion-selective electrode probes that transmit real-time nutrient availability data to the fertigation controller. Direct nutrient sensing eliminates reliance on proxy measurements for scheduling fertigation events.", cite: "Sensors and Actuators B: Chemical, Vol. 311, 2020", target: "Ion-selective probes -> Direct measurement -> Precise scheduling" }
    ],
    "Economics & Risk": [
      { label: "Fertigation vs. Broadcast Cost Comparison", type: "STRATEGY", evidence: "A", description: "Conduct annual economic analysis comparing fertigation costs (equipment, energy, labor, fertilizer) against broadcast application for the same nutrient targets. Fertigation typically reduces total fertilizer use by 20-30% through improved placement efficiency.", cite: "NRCS CPS 449; Agricultural Water Management, Vol. 200, 2018", target: "Cost comparison -> Efficiency documentation -> Justified investment" },
      { label: "Fertigation Budgeting Workshops", type: "COACHING", evidence: "B", description: "Conduct workshops for farm financial managers on budgeting for fertigation infrastructure including injection equipment, sensors, and maintenance. Accurate capital budgeting prevents unexpected costs that undermine program sustainability.", cite: "University of California ANR, Drip Irrigation Economics, 2019", target: "Budget workshops -> Accurate capital planning -> Sustainable investment" },
      { label: "Maintenance Reserve Fund Structure", type: "STRUCTURAL", evidence: "B", description: "Establish a dedicated maintenance reserve fund for fertigation system components including injectors, sensors, filters, and emitters. Proactive funding prevents deferred maintenance that degrades system performance and nutrient distribution uniformity.", cite: "Irrigation Association, Cost of Ownership Guide, 2020", target: "Maintenance reserve -> Proactive upkeep -> Sustained performance" },
      { label: "Water-Nutrient Efficiency Reporting", type: "CULTURE", evidence: "C", description: "Publish internal water and nutrient use efficiency metrics from fertigation operations to build organizational pride in resource stewardship. Visible metrics reinforce the economic and environmental value of precision fertigation.", cite: "Journal of Cleaner Production, Vol. 260, 2020", target: "Efficiency metrics -> Organizational pride -> Sustained commitment" },
      { label: "Fertigation System ROI Calculators", type: "TOOLS", evidence: "B", description: "Use fertigation ROI calculator tools that model payback periods based on fertilizer savings, yield improvements, labor reduction, and system costs. Data-driven investment analysis supports capital expenditure decisions for system upgrades.", cite: "USDA-NRCS Financial Analysis Tools; Irrigation Association, 2020", target: "ROI calculators -> Justified upgrades -> Optimized capital allocation" }
    ]
  }
};

// Continue with remaining topics in next section...
// For now, write this first batch and verify structure
const files = Object.keys(TREATMENTS);
console.log(`Prepared treatments for ${files.length} files in batch 1`);
files.forEach(f => console.log(`  - ${f}`));
