const fs = require('fs');
const path = require('path');
const DIR = path.join(__dirname, '..', 'assets', 'data', 'domains');

function addTreatments(filename, treatments) {
  const fp = path.join(DIR, filename);
  const data = JSON.parse(fs.readFileSync(fp, 'utf8'));
  data.activations.forEach((act, i) => {
    const group = act.group;
    let key = group === 'diagnostics' ? 'monitoring' : group === 'practices' ? 'practices' : group === 'innovation' ? 'technology' : 'economics';
    act.treatments = treatments[key];
  });
  fs.writeFileSync(fp, JSON.stringify(data, null, 2) + '\n');
  console.log('OK ' + filename);
}

// 1. Combine Harvesters
addTreatments('p2_agri_machinery_harvesting_combineharvesters.json', {
  monitoring: [
    {"label":"Harvest Loss Quantification Protocol","type":"STRATEGY","evidence":"A","description":"Implement systematic harvest loss measurement using drop pans at multiple field positions per ASABE S343.4 methodology. Quantifying total machine losses (header, threshing, separating, cleaning) enables targeted adjustment and benchmarking against manufacturer thresholds.","cite":"ASABE S343.4 – Method of Determining and Expressing Combine Capacity and Losses","target":"Loss measurement -> adjustment targeting -> grain savings 1-3%"},
    {"label":"Operator Calibration Walk-Through Training","type":"COACHING","evidence":"B","description":"Conduct pre-season walk-through training covering yield monitor calibration, concave clearance checks, and fan speed optimization. Hands-on demonstration of loss pan evaluation builds operator confidence in real-time machine tuning.","cite":"Purdue Extension BAE-99 – Combine Adjustments to Reduce Harvest Losses","target":"Operator skill -> correct adjustments -> reduced field losses"},
    {"label":"Seasonal Maintenance Checklist System","type":"STRUCTURAL","evidence":"A","description":"Establish a 50-point pre-season and mid-season inspection protocol covering rasp bars, concaves, sieves, auger flights, and bearing temperatures. Structured checklists prevent cascading mechanical failures during peak harvest windows.","cite":"ASABE EP525 – Combine Capacity and Performance Test Procedure","target":"Systematic inspection -> early wear detection -> prevented downtime"},
    {"label":"Operator Knowledge-Sharing Circles","type":"CULTURE","evidence":"B","description":"Organize weekly harvest-season debriefs where operators share loss data, adjustment strategies, and field condition observations. Peer learning accelerates adoption of best practices and normalizes continuous improvement.","cite":"Journal of Extension, Vol. 52, 2014 – Farmer Learning Networks","target":"Peer exchange -> practice adoption -> fleet-wide performance gain"},
    {"label":"Real-Time Yield and Loss Monitoring","type":"TOOLS","evidence":"A","description":"Deploy combine-integrated yield monitors with GPS mapping and optical grain loss sensors to generate per-pass performance data. Spatial loss maps identify field zones requiring header height or ground speed adjustments.","cite":"ASABE S587 – Communication Protocols for Precision Agriculture","target":"Sensor data -> spatial loss maps -> precision adjustment"}
  ],
  practices: [
    {"label":"Ground Speed Management Strategy","type":"STRATEGY","evidence":"A","description":"Establish crop-specific ground speed targets based on yield density and moisture content to maintain optimal threshing cylinder load. Matching travel speed to crop conditions prevents both under-threshing losses and excessive grain damage.","cite":"ASABE D497.7 – Agricultural Machinery Management Data","target":"Speed optimization -> consistent cylinder load -> minimized grain damage"},
    {"label":"Field-Condition Response Coaching","type":"COACHING","evidence":"B","description":"Train operators to read crop variability indicators including lodging severity, moisture gradients, and weed patches, then adjust header height, reel speed, and cylinder speed accordingly. Adaptive response skills reduce losses in variable field conditions.","cite":"University of Wisconsin Extension A3870 – Combine Operation and Adjustment","target":"Condition reading -> adaptive settings -> consistent harvest quality"},
    {"label":"Header-to-Crop Matching Protocol","type":"STRUCTURAL","evidence":"A","description":"Formalize decision rules for matching header type, width, and configuration to specific crop and field conditions. Documented protocols ensure correct corn head row spacing, draper vs. rigid auger selection, and header height automation settings.","cite":"ASABE S343.4; John Deere Operator Manual – Header Selection Guidelines","target":"Correct header match -> optimized feeding -> reduced shatter loss"},
    {"label":"Continuous Improvement Harvest Culture","type":"CULTURE","evidence":"B","description":"Foster a culture where daily grain loss measurements and yield monitor data review are standard practice, not exceptions. Rewarding operators who identify and solve loss problems drives sustained performance gains across harvest seasons.","cite":"Ag Professional Magazine, 2019 – Building High-Performance Harvest Teams","target":"Accountability culture -> daily monitoring -> season-over-season improvement"},
    {"label":"Combine Performance Diagnostic Software","type":"TOOLS","evidence":"A","description":"Utilize OEM diagnostic platforms (John Deere Service Advisor, AGCO EDT) to monitor engine load, separator speed, and cleaning system parameters. Telemetry dashboards flag performance deviations before they cause measurable yield losses.","cite":"ASABE X629 – Guidelines for Onboard Diagnostics in Agricultural Equipment","target":"Telemetry monitoring -> early deviation alerts -> proactive adjustment"}
  ],
  technology: [
    {"label":"Automated Combine Optimization Systems","type":"STRATEGY","evidence":"B","description":"Adopt machine-learning-based combine automation that continuously adjusts fan speed, concave clearance, and rotor speed based on real-time crop flow sensors. Automated optimization reduces operator variability and maintains peak efficiency across field zones.","cite":"Computers and Electronics in Agriculture, Vol. 176, 2020 – Automated Combine Parameter Optimization","target":"Automation algorithms -> continuous tuning -> reduced operator dependency"},
    {"label":"Technology Adoption Readiness Training","type":"COACHING","evidence":"B","description":"Provide structured training on interpreting precision agriculture dashboards, understanding sensor data outputs, and trusting automated adjustment systems. Building digital literacy prevents operators from overriding beneficial automation.","cite":"Applied Engineering in Agriculture, Vol. 35(4), 2019 – Operator Acceptance of Precision Ag Tech","target":"Digital literacy -> appropriate trust -> sustained technology use"},
    {"label":"Telematics Integration Architecture","type":"STRUCTURAL","evidence":"A","description":"Deploy standardized telematics infrastructure connecting combines to farm management information systems via ISOBUS and cloud platforms. Unified data architecture enables fleet-wide performance comparison and predictive maintenance scheduling.","cite":"ASABE/ISO 11783 – Tractors and Machinery for Agriculture – Serial Control and Communications Data Network","target":"Data integration -> fleet visibility -> coordinated optimization"},
    {"label":"Innovation Scouting and Pilot Culture","type":"CULTURE","evidence":"C","description":"Designate annual innovation trials where new sensor technologies, AI-driven adjustments, or hybrid threshing systems are tested on controlled field sections. Structured pilots reduce adoption risk while maintaining openness to emerging solutions.","cite":"Precision Agriculture, Vol. 21, 2020 – On-Farm Technology Evaluation Frameworks","target":"Structured piloting -> evidence-based adoption -> competitive advantage"},
    {"label":"Grain Quality Imaging Sensors","type":"TOOLS","evidence":"B","description":"Install near-infrared or camera-based grain quality sensors measuring broken kernels, foreign material, and moisture at the clean grain elevator. Real-time quality feedback enables immediate threshing parameter correction.","cite":"Biosystems Engineering, Vol. 189, 2020 – NIR Grain Quality Sensing on Combines","target":"Quality sensing -> immediate correction -> premium grain capture"}
  ],
  economics: [
    {"label":"Harvest Timeliness Cost Analysis","type":"STRATEGY","evidence":"A","description":"Model the economic cost of delayed harvest including dry-matter loss, quality downgrade, and weather risk using ASABE timeliness cost methodology. Quantified timeliness penalties justify investment in additional combine capacity or extended operating hours.","cite":"ASABE D497.7 – Agricultural Machinery Management Data; ASABE EP496.3","target":"Timeliness modeling -> capacity investment justification -> reduced weather risk"},
    {"label":"Total Cost of Ownership Coaching","type":"COACHING","evidence":"B","description":"Train farm managers to calculate and compare total ownership costs including depreciation, repairs, fuel, and opportunity costs across combine age classes. Informed replacement timing decisions prevent both premature trade-ins and costly over-retention.","cite":"Kansas State University MF-842 – Estimating Farm Machinery Costs","target":"TCO awareness -> optimal replacement timing -> minimized lifecycle cost"},
    {"label":"Custom Harvesting Contract Framework","type":"STRUCTURAL","evidence":"A","description":"Develop standardized contract templates specifying performance metrics, loss tolerances, and liability allocation for custom harvest operations. Clear contractual frameworks reduce disputes and ensure accountability for grain quality outcomes.","cite":"North Dakota State University EC1260 – Custom Farm Work Rates","target":"Contract clarity -> performance accountability -> fair risk allocation"},
    {"label":"Data-Driven Reinvestment Culture","type":"CULTURE","evidence":"B","description":"Institutionalize annual equipment ROI reviews using actual field performance data to inform capital allocation decisions. Evidence-based reinvestment culture prevents emotional purchasing and ensures machinery dollars flow to highest-impact upgrades.","cite":"Journal of the ASFMRA, 2018 – Farm Equipment Investment Decision Making","target":"ROI discipline -> evidence-based purchasing -> capital efficiency"},
    {"label":"Machinery Cost Budgeting Spreadsheet","type":"TOOLS","evidence":"A","description":"Implement ASABE-standard machinery cost calculators tracking per-acre and per-bushel combine operating costs including fuel, repairs, labor, and depreciation. Granular cost tracking enables accurate enterprise budgeting and custom rate setting.","cite":"ASABE D497.7 – Agricultural Machinery Management Data","target":"Cost tracking -> accurate budgets -> profitable rate-setting"}
  ]
});

// 2. Corn Headers
addTreatments('p2_agri_machinery_harvesting_cornheaders.json', {
  monitoring: [
    {"label":"Stalk Roll Condition Assessment Protocol","type":"STRATEGY","evidence":"A","description":"Implement systematic inspection of stalk rolls, deck plates, and gathering chains at defined acre intervals to detect wear patterns before they cause ear loss. Quantified wear measurements enable predictive replacement scheduling aligned with harvest windows.","cite":"ASABE S343.4 – Combine Header Loss Measurement; Deere Technical Manual","target":"Wear measurement -> predictive replacement -> prevented ear drop loss"},
    {"label":"Ear Loss Evaluation Field Training","type":"COACHING","evidence":"B","description":"Train operators to conduct standardized ear-loss counts behind the header using defined sample areas. Visual identification of butt-shelling, ear drop, and stalk roll plugging symptoms enables immediate corrective adjustments.","cite":"Purdue Extension BAE-99 – Reducing Corn Harvest Losses","target":"Loss identification skills -> corrective action -> reduced header losses"},
    {"label":"Pre-Season Header Inspection Checklist","type":"STRUCTURAL","evidence":"A","description":"Establish comprehensive pre-harvest inspection covering deck plate spacing, stalk roll knife sharpness, gathering chain tension, and row divider alignment. Documented checklists ensure consistent readiness across multi-header fleets.","cite":"ASABE EP525 – Combine Capacity and Performance Test; CNH Operator Manuals","target":"Systematic inspection -> uniform readiness -> reliable field performance"},
    {"label":"Header Performance Benchmarking Culture","type":"CULTURE","evidence":"B","description":"Normalize sharing of per-header loss data and adjustment strategies across operator teams. Transparent performance benchmarking creates positive competition and rapid diffusion of best practices for deck plate and speed settings.","cite":"Journal of Extension, Vol. 52, 2014 – Peer Learning in Farm Operations","target":"Transparent benchmarking -> peer learning -> fleet-wide loss reduction"},
    {"label":"Row Sensor and Guidance Monitoring","type":"TOOLS","evidence":"A","description":"Deploy row-sensing guidance systems and header height sensors to maintain optimal stalk engagement across field variability. Automated row tracking prevents row-skip damage and ensures consistent ear capture in irregular stands.","cite":"ASABE S587 – Precision Agriculture Communication Protocols; Deere AutoTrac RowSense","target":"Sensor guidance -> consistent row tracking -> minimized ear loss"}
  ],
  practices: [
    {"label":"Deck Plate Spacing Optimization","type":"STRATEGY","evidence":"A","description":"Establish crop-condition-based deck plate gap settings referencing stalk diameter measurements and moisture content. Proper spacing prevents butt-shelling in dry conditions and ear drop in tough stalks, targeting the 1-2% header loss threshold.","cite":"Iowa State University PM1874 – Corn Harvest Management","target":"Correct deck plate gap -> reduced butt-shelling -> header loss under 1%"},
    {"label":"Field Speed and Row Unit Coaching","type":"COACHING","evidence":"B","description":"Coach operators on matching ground speed to gathering chain speed ratios for different corn populations and standability conditions. Understanding the kinematic relationship between travel speed and stalk feeding prevents aggressive ear snapping.","cite":"University of Illinois Crop Sciences Extension – Corn Harvest Adjustments","target":"Speed-chain matching -> smooth stalk feeding -> fewer snapped ears"},
    {"label":"Corn Header Configuration SOP","type":"STRUCTURAL","evidence":"A","description":"Document standard operating procedures for header width selection, row spacing verification, and chopper/stalk stomper configuration based on tillage system requirements. SOPs ensure headers are configured for both harvest efficiency and residue management.","cite":"NRCS CPS 329 – Residue Management; ASABE S396.2 – Stalk Chopper Standards","target":"Documented SOPs -> correct configuration -> dual harvest/residue benefit"},
    {"label":"Cross-Shift Knowledge Transfer Norm","type":"CULTURE","evidence":"C","description":"Institute shift-change briefings where departing operators communicate field conditions, header adjustment settings, and emerging issues to incoming operators. Structured handoffs prevent repeated adjustment errors and maintain harvest continuity.","cite":"Agricultural Safety and Health Best Practices, NIOSH 2018","target":"Shift briefings -> retained adjustments -> continuous harvest quality"},
    {"label":"Stalk Roll Wear Measurement Gauge","type":"TOOLS","evidence":"B","description":"Use precision measurement gauges to quantify stalk roll knife edge wear and deck plate gap tolerances against manufacturer specifications. Objective measurement eliminates guesswork in replacement timing decisions.","cite":"Case IH Technical Bulletin – Corn Head Maintenance; ASABE S343.4","target":"Precision measurement -> data-driven replacement -> optimal roll performance"}
  ],
  technology: [
    {"label":"Automated Deck Plate Adjustment","type":"STRATEGY","evidence":"B","description":"Adopt sensor-driven automatic deck plate systems that adjust spacing based on real-time stalk diameter sensing. Automated adjustment eliminates manual stops and maintains optimal settings across variable-population fields.","cite":"Precision Agriculture, Vol. 20, 2019 – Automated Header Technology","target":"Sensor-driven adjustment -> continuous optimization -> eliminated manual stops"},
    {"label":"Precision Header Technology Orientation","type":"COACHING","evidence":"B","description":"Deliver hands-on training covering automated row sensing, header tilt control, and integrated stalk chopper management systems. Ensuring operators understand sensor feedback loops prevents manual overrides of beneficial automation.","cite":"Applied Engineering in Agriculture, Vol. 34(2), 2018 – Operator Training for Precision Headers","target":"Technology understanding -> appropriate trust -> sustained auto-adjustment use"},
    {"label":"ISOBUS Header Data Integration","type":"STRUCTURAL","evidence":"A","description":"Connect header sensors to the combine ISOBUS network for unified data logging of row unit performance, gathering chain loads, and deck plate positions. Integrated data enables correlation of header settings with yield monitor outputs.","cite":"ASABE/ISO 11783 – Serial Control and Communications Data Network","target":"Data integration -> setting-yield correlation -> evidence-based tuning"},
    {"label":"Early Adopter Header Trials","type":"CULTURE","evidence":"C","description":"Designate test plots for evaluating emerging header technologies including camera-guided row tracking, electric deck plate drives, and integrated residue sizing systems. Controlled trials build evidence for fleet-wide adoption decisions.","cite":"Transactions of the ASABE, Vol. 62(3), 2019 – On-Farm Header Evaluation Methods","target":"Controlled trials -> validated performance -> informed fleet adoption"},
    {"label":"Header Load and Vibration Sensors","type":"TOOLS","evidence":"B","description":"Install vibration and load sensors on gathering chains and stalk rolls to detect plugging events, bearing degradation, and drive belt slippage in real time. Early warning alerts prevent catastrophic failures during peak harvest.","cite":"Biosystems Engineering, Vol. 178, 2019 – Vibration Monitoring in Harvest Equipment","target":"Vibration monitoring -> early failure detection -> prevented harvest downtime"}
  ],
  economics: [
    {"label":"Header Loss Cost Quantification","type":"STRATEGY","evidence":"A","description":"Calculate the dollar value of header losses at current commodity prices to justify investment in upgraded deck plates, stalk rolls, or automated systems. Even 0.5% header loss reduction translates to significant per-acre savings at scale.","cite":"ASABE D497.7; Iowa State University Ag Decision Maker A1-20","target":"Loss valuation -> investment justification -> positive ROI on upgrades"},
    {"label":"Replacement Cycle Economic Coaching","type":"COACHING","evidence":"B","description":"Guide managers through header component replacement economics comparing worn-component yield losses against parts and labor costs. Break-even analysis for stalk rolls, deck plates, and gathering chains optimizes maintenance spend timing.","cite":"Kansas State University MF-842 – Estimating Farm Machinery Costs","target":"Break-even analysis -> optimal replacement timing -> net cost reduction"},
    {"label":"Multi-Year Header Investment Plan","type":"STRUCTURAL","evidence":"A","description":"Develop 5-year capital plans for corn header fleet management incorporating depreciation schedules, expected technology upgrades, and crop rotation acreage projections. Structured planning prevents reactive purchasing and leverages trade cycle value.","cite":"North Dakota State University EC1260 – Custom Farm Work Rates and Machinery Costs","target":"Capital planning -> optimized trade cycles -> maximized residual value"},
    {"label":"Cost Transparency Across Operations","type":"CULTURE","evidence":"B","description":"Share per-acre header operating costs across the management team to build collective awareness of maintenance and loss cost drivers. Transparency creates shared accountability for header performance and investment stewardship.","cite":"Journal of the ASFMRA, 2019 – Farm Machinery Cost Management Practices","target":"Cost visibility -> shared accountability -> disciplined maintenance spending"},
    {"label":"Header Cost Tracking Dashboard","type":"TOOLS","evidence":"A","description":"Deploy digital cost tracking integrating parts invoices, labor hours, and downtime records per header unit. Per-acre cost dashboards identify high-maintenance units requiring replacement and validate investment decisions.","cite":"ASABE D497.7 – Agricultural Machinery Management Data","target":"Unit cost tracking -> problem unit identification -> fleet optimization"}
  ]
});

// 3. Draper Headers
addTreatments('p2_agri_machinery_harvesting_draperheaders.json', {
  monitoring: [
    {"label":"Draper Belt Wear Tracking Protocol","type":"STRATEGY","evidence":"A","description":"Implement scheduled draper belt tension measurements and surface condition assessments at defined acre intervals. Tracking belt elongation and surface cracking patterns enables proactive replacement before crop feeding becomes inconsistent.","cite":"ASABE S343.4 – Combine Header Loss Measurement; MacDon Operator Manual","target":"Belt wear tracking -> predictive replacement -> consistent crop feeding"},
    {"label":"Cut Height and Reel Speed Coaching","type":"COACHING","evidence":"B","description":"Train operators on optimizing cutter bar height and reel index (reel speed to ground speed ratio) for different crop conditions. Proper reel engagement prevents header shatter in soybeans and minimizes windrow bunching in canola.","cite":"University of Minnesota Extension – Soybean Harvest Loss Reduction","target":"Reel optimization skills -> reduced shatter -> header loss under 1%"},
    {"label":"Multi-Point Header Inspection System","type":"STRUCTURAL","evidence":"A","description":"Establish inspection protocols covering knife sections, guards, draper belt tracking, center feed auger, and lateral tilt cylinders. Structured multi-point checks prevent the cascading failures common in wide-platform draper systems.","cite":"ASABE EP525 – Combine Performance Test Procedure; Honey Bee Manufacturing Specs","target":"Multi-point inspection -> early wear detection -> prevented cascading failure"},
    {"label":"Cross-Crop Header Knowledge Sharing","type":"CULTURE","evidence":"B","description":"Organize seasonal reviews where operators share draper header performance data across different crop types (soybeans, canola, lentils, wheat). Multi-crop experience exchange accelerates operator proficiency on versatile draper platforms.","cite":"Precision Agriculture, Vol. 19, 2018 – Multi-Crop Harvest Optimization","target":"Cross-crop learning -> versatile proficiency -> maximized draper utilization"},
    {"label":"Draper Belt Tracking Sensors","type":"TOOLS","evidence":"B","description":"Install belt tracking sensors that monitor lateral position and tension of left/right draper belts in real time. Automated alerts for belt misalignment prevent crop bunching, uneven feeding, and premature belt edge wear.","cite":"Biosystems Engineering, Vol. 185, 2019 – Belt Conveyor Monitoring in Agriculture","target":"Tracking sensors -> misalignment alerts -> prevented uneven feeding"}
  ],
  practices: [
    {"label":"Flex Draper Ground Following Strategy","type":"STRATEGY","evidence":"A","description":"Develop field-specific ground contour response settings for flex draper flotation, including spring tension, skid shoe height, and auto-header control sensitivity. Matched flotation settings maintain consistent cut height across undulating terrain.","cite":"ASABE S396.2 – Header Performance Standards; MacDon FD2 Operator Guide","target":"Flotation optimization -> consistent cut height -> minimal crop loss on contours"},
    {"label":"Multi-Crop Draper Configuration Coaching","type":"COACHING","evidence":"B","description":"Coach operators on rapid reconfiguration procedures for switching between crop modes including draper speed ratios, center deck settings, and end-divider adjustments. Efficient changeover skills maximize utilization of multi-crop draper investments.","cite":"Saskatchewan Ministry of Agriculture – Draper Header Setup Guide","target":"Fast reconfiguration -> minimal changeover downtime -> maximized utilization"},
    {"label":"Knife Section Replacement SOP","type":"STRUCTURAL","evidence":"A","description":"Document systematic knife section replacement protocols specifying replacement intervals, section quality standards, and knife-to-guard clearance specifications. Standardized knife maintenance prevents ragged cutting that increases shatter loss.","cite":"ASABE S346 – Sickle Section and Guard Standards; Deere Parts Catalog","target":"Standard knife maintenance -> clean cuts -> reduced shatter loss"},
    {"label":"Low-Loss Harvest Mindset","type":"CULTURE","evidence":"B","description":"Cultivate operator pride in achieving sub-1% total header losses through visible goal tracking and recognition programs. A low-loss mindset encourages voluntary loss checks, careful speed management, and proactive maintenance reporting.","cite":"Journal of Extension, Vol. 54, 2016 – Motivation in Agricultural Operations","target":"Loss-conscious culture -> voluntary monitoring -> sustained low-loss performance"},
    {"label":"Header Performance Mapping Software","type":"TOOLS","evidence":"A","description":"Use GPS-linked yield mapping software to create spatial performance maps correlating header settings with yield and loss outcomes. Geo-referenced performance data identifies field zones where draper adjustments improve harvest efficiency.","cite":"ASABE S587 – Precision Agriculture Communication; Ag Leader Integra Documentation","target":"Spatial mapping -> zone-specific adjustments -> optimized field-level performance"}
  ],
  technology: [
    {"label":"Integrated Header Automation Strategy","type":"STRATEGY","evidence":"B","description":"Adopt header height automation systems with stubble-sensing and crop-flow feedback for continuous draper platform optimization. Integrated automation reduces operator fatigue during long harvest days while maintaining consistent performance.","cite":"Computers and Electronics in Agriculture, Vol. 162, 2019 – Automated Header Height Control","target":"Automation integration -> reduced operator fatigue -> consistent all-day performance"},
    {"label":"Sensor Feedback Interpretation Training","type":"COACHING","evidence":"B","description":"Train operators on reading and responding to automated header system feedback including belt speed deviation warnings, knife drive load indicators, and crop flow uniformity alerts. Informed operators complement automation rather than fighting it.","cite":"Applied Engineering in Agriculture, Vol. 35(2), 2019 – Human-Machine Interface in Harvesting","target":"Sensor literacy -> constructive human-automation interaction -> performance gains"},
    {"label":"Draper Header Data Logging Framework","type":"STRUCTURAL","evidence":"A","description":"Deploy standardized data logging capturing belt speeds, knife drive loads, header height position, and crop throughput at sub-second intervals. Structured data frameworks enable post-harvest analysis and season-over-season improvement tracking.","cite":"ASABE/ISO 11783 – Agricultural Equipment Data Networks","target":"Data logging -> post-harvest analysis -> continuous improvement"},
    {"label":"Technology Forward Harvest Team","type":"CULTURE","evidence":"C","description":"Build team identity around being technology adopters who leverage precision data for harvest decisions. Celebrating data-driven wins and learning from technology-enabled insights creates lasting adoption momentum.","cite":"Precision Agriculture, Vol. 21, 2020 – Technology Adoption in Farm Operations","target":"Tech-forward identity -> enthusiastic adoption -> sustained innovation gains"},
    {"label":"Crop Flow Imaging Systems","type":"TOOLS","evidence":"C","description":"Evaluate camera-based crop flow imaging at the draper-to-feederhouse transition point to detect uneven feeding, slug loads, and foreign material. Visual monitoring technology provides early warning for conditions that cause combine plugging.","cite":"Biosystems Engineering, Vol. 198, 2020 – Machine Vision in Harvest Equipment","target":"Flow imaging -> slug detection -> prevented combine plugging events"}
  ],
  economics: [
    {"label":"Draper vs. Rigid Auger ROI Analysis","type":"STRATEGY","evidence":"A","description":"Conduct enterprise-level ROI comparison between draper and rigid auger platforms accounting for multi-crop versatility, harvest speed gains, and loss reduction value. Quantified economic analysis supports capital allocation for header fleet decisions.","cite":"ASABE D497.7 – Machinery Management Data; Farm Management Guides","target":"Comparative ROI -> informed fleet investment -> maximized return per header dollar"},
    {"label":"Multi-Crop Revenue Impact Coaching","type":"COACHING","evidence":"B","description":"Coach managers on calculating the revenue impact of draper header advantages across multiple crops including soybeans, canola, and pulses. Understanding per-crop margin improvements strengthens the business case for versatile draper platforms.","cite":"University of Saskatchewan – Harvest Equipment Economics","target":"Revenue impact awareness -> justified investment -> multi-crop margin improvement"},
    {"label":"Fleet Standardization Cost Framework","type":"STRUCTURAL","evidence":"A","description":"Develop cost comparison frameworks for fleet standardization on draper platforms versus mixed-header fleets, including training costs, parts inventory simplification, and logistics efficiency. Standardization analysis reveals hidden savings.","cite":"North Dakota State University EC1260 – Custom Rates and Machinery Costs","target":"Standardization analysis -> identified hidden savings -> simplified fleet management"},
    {"label":"Equipment Investment Review Culture","type":"CULTURE","evidence":"B","description":"Institute semi-annual header fleet reviews where performance data, maintenance costs, and loss metrics drive upgrade and replacement discussions. Evidence-based investment culture prevents both under-investment and gold-plating.","cite":"Journal of the ASFMRA, 2018 – Capital Equipment Decision Frameworks","target":"Regular reviews -> evidence-based decisions -> balanced investment approach"},
    {"label":"Custom Rate Calculator for Drapers","type":"TOOLS","evidence":"A","description":"Implement draper-specific custom rate calculators incorporating wider cutting widths, higher field speeds, and multi-crop capability into per-acre pricing. Accurate rate calculation ensures fair compensation for premium header investment.","cite":"ASABE D497.7 – Agricultural Machinery Management Data","target":"Accurate rate calculation -> fair custom pricing -> investment cost recovery"}
  ]
});

// 4. Yield Monitors
addTreatments('p2_agri_machinery_harvesting_yieldmonitors.json', {
  monitoring: [
    {"label":"Multi-Point Calibration Protocol","type":"STRATEGY","evidence":"A","description":"Implement yield monitor calibration using minimum three weigh-wagon loads per crop type at varying moisture levels and flow rates. Multi-point calibration reduces systematic bias and ensures spatial yield data accuracy within 3% of scale weights.","cite":"ASABE X578.1 – Yield Monitor Test Procedures; Ag Leader Calibration Guide","target":"Multi-point calibration -> reduced bias -> yield data accuracy within 3%"},
    {"label":"Calibration Verification Coaching","type":"COACHING","evidence":"B","description":"Train operators on daily calibration verification procedures including moisture sensor checks, mass flow sensor cleaning, and comparison against known field weights. Routine verification skills prevent data quality degradation over the harvest season.","cite":"Purdue Extension AY-243 – Yield Monitor Calibration and Data Quality","target":"Verification skills -> maintained data quality -> reliable season-long data"},
    {"label":"Yield Data Quality Audit System","type":"STRUCTURAL","evidence":"A","description":"Establish post-harvest data quality audits filtering for known error sources including header-up delays, wet-dry transitions, speed changes, and end-row artifacts. Standardized cleaning protocols ensure agronomic decisions use trustworthy yield data.","cite":"ASABE S587; Precision Agriculture, Vol. 18, 2017 – Yield Data Cleaning Methods","target":"Data auditing -> error removal -> trustworthy agronomic decisions"},
    {"label":"Data Quality Ownership Culture","type":"CULTURE","evidence":"B","description":"Foster operator ownership of yield data quality by sharing how their calibration diligence directly impacts zone management and input decisions. Connecting calibration effort to economic outcomes motivates sustained data quality commitment.","cite":"Journal of Extension, Vol. 53, 2015 – Precision Agriculture Data Culture","target":"Quality ownership -> motivated calibration -> impactful agronomic data"},
    {"label":"Yield Monitor Diagnostic Software","type":"TOOLS","evidence":"A","description":"Deploy OEM diagnostic software for continuous monitoring of mass flow sensor output, moisture sensor readings, and GPS signal quality. Real-time diagnostics flag sensor drift, blockages, and communication errors during harvest operations.","cite":"ASABE X629 – Onboard Diagnostics; John Deere Stellar Support Platform","target":"Diagnostic monitoring -> drift detection -> immediate correction"}
  ],
  practices: [
    {"label":"Crop-Specific Calibration Strategy","type":"STRATEGY","evidence":"A","description":"Develop separate calibration curves for each crop type and variety group to account for differences in grain density, kernel size, and moisture characteristics. Crop-specific calibration eliminates the 5-8% errors common with generic settings.","cite":"ASABE X578.1 – Yield Monitor Procedures; University of Kentucky PA-1","target":"Crop-specific curves -> eliminated cross-crop bias -> 5-8% accuracy improvement"},
    {"label":"End-Row Data Management Training","type":"COACHING","evidence":"B","description":"Coach operators on consistent header engagement and disengagement procedures to minimize end-row yield data artifacts. Training on header-up delay settings and turning patterns produces cleaner spatial datasets for variable-rate prescriptions.","cite":"Ohio State University Extension AEX-550 – Yield Monitor Best Practices","target":"Consistent procedures -> fewer end-row artifacts -> cleaner spatial data"},
    {"label":"Annual Sensor Maintenance SOP","type":"STRUCTURAL","evidence":"A","description":"Document annual sensor maintenance including impact plate cleaning, moisture sensor electrode inspection, elevator speed sensor calibration, and wiring harness integrity checks. Structured maintenance prevents sensor degradation across seasons.","cite":"ASABE EP525; Ag Leader InCommand Maintenance Manual","target":"Annual maintenance SOP -> sensor reliability -> multi-season data consistency"},
    {"label":"Precision Data Utilization Norm","type":"CULTURE","evidence":"B","description":"Normalize the use of yield monitor data in all crop planning meetings, input purchasing decisions, and landlord reporting. When yield data visibly drives decisions, operators recognize the value of their calibration efforts and maintain high standards.","cite":"Precision Agriculture, Vol. 19, 2018 – Adoption and Impact of Yield Mapping","target":"Data utilization norm -> operator motivation -> self-reinforcing quality cycle"},
    {"label":"Weigh Wagon Calibration System","type":"TOOLS","evidence":"A","description":"Maintain certified weigh wagons with load cells accurate to 0.5% for in-field yield monitor calibration verification. Field-accessible weighing provides the ground truth reference essential for accurate yield monitor performance assessment.","cite":"ASABE X578.1; National Type Evaluation Program – Weighing Devices Handbook 44","target":"Certified ground truth -> accurate calibration -> defensible yield data"}
  ],
  technology: [
    {"label":"Multi-Sensor Yield Data Fusion","type":"STRATEGY","evidence":"B","description":"Integrate yield monitor data with satellite imagery, soil EC maps, and as-applied input records to create comprehensive field performance models. Multi-layer data fusion reveals yield-limiting factors invisible to any single data source.","cite":"Computers and Electronics in Agriculture, Vol. 175, 2020 – Sensor Fusion in Precision Ag","target":"Data fusion -> yield-limiting factor identification -> targeted interventions"},
    {"label":"Advanced Data Analytics Coaching","type":"COACHING","evidence":"B","description":"Train agronomists on yield data analytics including spatial statistics, yield stability analysis, and profit zone delineation using GIS platforms. Advanced analytical skills transform raw yield data into actionable management zone prescriptions.","cite":"Applied Engineering in Agriculture, Vol. 36(1), 2020 – Geospatial Yield Analysis","target":"Analytics skills -> management zone prescriptions -> optimized input placement"},
    {"label":"Cloud Data Management Architecture","type":"STRUCTURAL","evidence":"A","description":"Deploy cloud-based yield data management platforms with standardized import formats, multi-year layering, and role-based access controls. Centralized architecture enables cross-season trend analysis and multi-farm benchmarking.","cite":"ASABE S587; Climate FieldView and Granular Platform Documentation","target":"Cloud architecture -> multi-year analysis -> cross-farm benchmarking"},
    {"label":"Data-Driven Decision Culture","type":"CULTURE","evidence":"B","description":"Establish expectation that all variable-rate prescriptions, seed selection, and fertility plans reference yield monitor data layers. Building data into standard workflows ensures precision agriculture investments generate measurable return.","cite":"Precision Agriculture, Vol. 20, 2019 – ROI of Precision Data Utilization","target":"Data-driven decisions -> optimized prescriptions -> measurable ROI"},
    {"label":"Yield Data Visualization Platform","type":"TOOLS","evidence":"A","description":"Implement spatial visualization platforms rendering multi-year yield maps with statistical analysis overlays including yield stability, trend surfaces, and comparison dashboards. Visual tools make complex spatial patterns accessible to all stakeholders.","cite":"ASABE S587; ESRI ArcGIS Agricultural Mapping; Ag Leader SMS Advanced","target":"Visualization platform -> pattern recognition -> stakeholder alignment"}
  ],
  economics: [
    {"label":"Yield Data Value Chain Analysis","type":"STRATEGY","evidence":"A","description":"Quantify the economic value of accurate yield data by tracing its impact through variable-rate input savings, seed selection optimization, and land rental negotiations. Documented value chains justify ongoing investment in monitor maintenance and calibration.","cite":"ASABE D497.7; University of Illinois FBM – Precision Ag Economic Impact","target":"Value chain tracing -> justified maintenance investment -> sustained data quality"},
    {"label":"Precision ROI Calculation Coaching","type":"COACHING","evidence":"B","description":"Coach farm managers on calculating return on investment for yield monitoring technology including hardware costs, calibration labor, data management subscriptions, and downstream value from variable-rate prescriptions.","cite":"Kansas State University MF-2187 – Precision Agriculture Economics","target":"ROI calculation skills -> informed technology investment -> maximized returns"},
    {"label":"Multi-Year Data Investment Plan","type":"STRUCTURAL","evidence":"A","description":"Develop long-term data investment strategies recognizing that yield monitor value compounds over multiple seasons as temporal data layers enable stability analysis, trend detection, and benchmark comparisons impossible with single-year data.","cite":"Precision Agriculture, Vol. 18, 2017 – Temporal Value of Yield Data","target":"Long-term data strategy -> compounding analytical value -> superior decisions"},
    {"label":"Yield Data Sharing Norms","type":"CULTURE","evidence":"B","description":"Build trust frameworks for sharing yield data with agronomists, landlords, and input suppliers where appropriate. When data sharing produces better recommendations and fairer rental negotiations, it reinforces the investment in data quality.","cite":"Journal of Extension, Vol. 55, 2017 – Data Sharing in Precision Agriculture","target":"Trusted sharing -> better recommendations -> reinforced data investment"},
    {"label":"Cost-Benefit Analysis Calculator","type":"TOOLS","evidence":"A","description":"Deploy precision agriculture ROI calculators that model the economic impact of yield-data-driven variable-rate applications versus uniform-rate management across field variability levels. Decision support tools quantify the value of data.","cite":"ASABE D497.7; Purdue Extension EC-735 – Variable Rate Technology Economics","target":"ROI calculator -> quantified data value -> evidence-based technology adoption"}
  ]
});

// 5. Mower Conditioners
addTreatments('p2_agri_machinery_hayforage_mowerconditioners.json', {
  monitoring: [
    {"label":"Conditioning Intensity Assessment Protocol","type":"STRATEGY","evidence":"A","description":"Implement systematic evaluation of conditioning roll gap settings and impeller speed by measuring stem crimp frequency and leaf retention across windrow samples. Quantified conditioning metrics enable precise adjustment for target drying rates.","cite":"ASABE S424.1 – Method for Determining Forage Conditioning Effectiveness","target":"Conditioning measurement -> precise adjustment -> target drying rate achieved"},
    {"label":"Stubble Height and Cut Quality Coaching","type":"COACHING","evidence":"B","description":"Train operators to evaluate cutting consistency by measuring stubble height uniformity and inspecting for ragged or torn stems indicating dull knife sections or misaligned disc cutters. Cut quality awareness drives timely maintenance actions.","cite":"University of Wisconsin Extension A3353 – Hay Harvest Management","target":"Cut quality awareness -> timely blade maintenance -> improved forage quality"},
    {"label":"Daily Pre-Operation Inspection Checklist","type":"STRUCTURAL","evidence":"A","description":"Establish daily inspection protocols covering knife edge sharpness, conditioning roll condition, belt/chain tension, header flotation, and PTO driveline integrity. Consistent daily checks prevent mid-field breakdowns during weather-sensitive hay windows.","cite":"ASABE EP496.3 – Agricultural Machinery Management; OSHA Ag Safety Guidelines","target":"Daily inspection -> prevented mid-field breakdown -> captured weather windows"},
    {"label":"Forage Quality First Culture","type":"CULTURE","evidence":"B","description":"Establish that forage quality starts at the mower-conditioner by connecting cutting height and conditioning intensity to downstream feed value metrics (RFV/RFQ). Operators who understand quality impact become more diligent about machine settings.","cite":"Journal of Dairy Science, Vol. 98, 2015 – Harvest Timing and Forage Quality","target":"Quality awareness -> diligent settings -> higher RFV/RFQ forage"},
    {"label":"Mower-Conditioner Performance Logger","type":"TOOLS","evidence":"B","description":"Deploy operational data loggers recording ground speed, PTO load, conditioning roll pressure, and acres covered per session. Logged performance data identifies operational patterns that correlate with superior or inferior forage drying outcomes.","cite":"Applied Engineering in Agriculture, Vol. 33(5), 2017 – Forage Equipment Monitoring","target":"Data logging -> pattern identification -> optimized drying outcomes"}
  ],
  practices: [
    {"label":"Windrow Formation Optimization","type":"STRATEGY","evidence":"A","description":"Configure windrow width and density based on crop volume and predicted drying conditions to balance rapid moisture loss with raking efficiency. Wide, thin windrows in heavy crops and narrower windrows in light yields optimize field drying rates.","cite":"ASABE S424.1; University of Kentucky AGR-62 – Quality Hay Production","target":"Windrow optimization -> balanced drying rate -> preserved forage quality"},
    {"label":"Crop-Specific Conditioning Coaching","type":"COACHING","evidence":"B","description":"Coach operators on adjusting conditioning intensity for different forage species: aggressive crimping for thick-stemmed alfalfa, lighter impeller conditioning for grass hay, and minimal conditioning for leafy legume mixes. Species-specific settings preserve leaf retention.","cite":"Penn State Extension – Hay and Forage Harvest Management","target":"Species-specific conditioning -> leaf retention -> maximized feed value"},
    {"label":"Knife and Disc Maintenance Schedule","type":"STRUCTURAL","evidence":"A","description":"Document replacement intervals for sickle bar sections, disc mower blades, and conditioning rolls based on crop type and acres cut. Formalized schedules with parts pre-ordering prevent quality degradation from operating worn cutting components.","cite":"ASABE S346 – Sickle Section Standards; Kuhn Operator Manuals","target":"Scheduled replacement -> sharp cutting -> consistent forage quality"},
    {"label":"Weather-Responsive Harvest Teamwork","type":"CULTURE","evidence":"B","description":"Build team coordination norms for rapid mowing response when weather windows open, including pre-staged equipment, designated field sequences, and communication protocols. Responsive teamwork captures narrow drying windows that determine annual forage quality.","cite":"Journal of Extension, Vol. 50, 2012 – Hay Harvest Timeliness","target":"Team coordination -> rapid weather response -> captured quality windows"},
    {"label":"Forage Moisture Probe Kit","type":"TOOLS","evidence":"A","description":"Equip mowing crews with calibrated windrow moisture probes to verify drying progress before committing to raking or baling operations. Objective moisture measurement replaces guesswork and prevents both over-dry leaf shatter and under-dry spoilage.","cite":"ASABE S358.3 – Moisture Measurement in Forages","target":"Moisture verification -> correct timing -> prevented shatter and spoilage"}
  ],
  technology: [
    {"label":"GPS-Based Mowing Pattern Optimization","type":"STRATEGY","evidence":"B","description":"Use GPS guidance to optimize mowing patterns that minimize turning losses, reduce overlap waste, and align windrows for efficient raking and baling sequences. Pattern optimization reduces fuel consumption and field time by 8-12%.","cite":"Computers and Electronics in Agriculture, Vol. 155, 2018 – GPS-Guided Hay Operations","target":"Pattern optimization -> reduced overlap -> 8-12% time and fuel savings"},
    {"label":"Technology-Assisted Drying Management Training","type":"COACHING","evidence":"C","description":"Train operators on emerging drying-aid technologies including chemical desiccants, wide-swath mowing, and solar-responsive windrow manipulation. Understanding technology options enables informed decisions about accelerating field drying.","cite":"Transactions of the ASABE, Vol. 61(5), 2018 – Forage Drying Technology Review","target":"Technology literacy -> informed drying decisions -> accelerated cure times"},
    {"label":"Telematics-Enabled Fleet Coordination","type":"STRUCTURAL","evidence":"B","description":"Deploy telematics on mower-conditioner fleets to enable real-time field progress tracking, maintenance alerts, and coordinated dispatch of raking and baling operations. Connected fleet management optimizes multi-machine hay harvest logistics.","cite":"ASABE/ISO 11783 – Agricultural Data Networks; John Deere JDLink","target":"Fleet telematics -> coordinated operations -> optimized harvest logistics"},
    {"label":"Innovation Testing in Hay Operations","type":"CULTURE","evidence":"C","description":"Encourage testing of emerging mower-conditioner technologies on designated trial fields before full-fleet adoption. Pilot testing wide-swath capabilities, hybrid conditioning systems, or disc-mower advancements builds evidence for sound investment.","cite":"Precision Agriculture, Vol. 20, 2019 – Technology Evaluation Frameworks","target":"Pilot testing -> evidence-based adoption -> reduced technology risk"},
    {"label":"Crop Flow and Cut Quality Sensors","type":"TOOLS","evidence":"C","description":"Evaluate real-time crop flow sensors and cut quality cameras for mower-conditioners that detect uneven cutting, plugging risk, and conditioning inconsistency. Emerging sensor technologies promise to automate settings optimization.","cite":"Biosystems Engineering, Vol. 195, 2020 – Sensor Development for Forage Equipment","target":"Quality sensors -> automated detection -> real-time setting correction"}
  ],
  economics: [
    {"label":"Forage Quality Economic Modeling","type":"STRATEGY","evidence":"A","description":"Model the economic value of forage quality differences driven by mower-conditioner settings, quantifying the $/ton premium for high-RFV hay and the cost of quality deductions in commercial sales. Quality economics justify equipment maintenance investment.","cite":"ASABE D497.7; University of Wisconsin Extension A3353 – Hay Value","target":"Quality valuation -> justified maintenance spend -> captured quality premiums"},
    {"label":"Custom Mowing Rate Analysis Coaching","type":"COACHING","evidence":"B","description":"Coach custom operators on calculating breakeven mowing rates incorporating machine cost, fuel, labor, blade replacement, and travel between fields. Accurate cost awareness prevents under-pricing that erodes equipment replacement reserves.","cite":"Kansas State University MF-842 – Farm Machinery Costs","target":"Cost awareness -> accurate pricing -> adequate replacement reserves"},
    {"label":"Mowing Fleet Right-Sizing Framework","type":"STRUCTURAL","evidence":"A","description":"Develop fleet sizing models balancing mowing capacity against weather-window probability and acreage commitments. Right-sizing analysis using ASABE timeliness cost methodology prevents both over-investment and harvest-window bottlenecks.","cite":"ASABE D497.7; ASABE EP496.3 – Machinery Management","target":"Fleet right-sizing -> balanced capacity vs. cost -> optimal timeliness"},
    {"label":"Cost-Conscious Hay Operation Culture","type":"CULTURE","evidence":"B","description":"Build awareness that mower-conditioner operating costs represent 15-20% of total hay production costs, motivating careful speed management, blade maintenance, and fuel-efficient mowing patterns. Cost consciousness at the operator level improves margins.","cite":"North Dakota State University EC1260 – Custom Farm Work Rates","target":"Cost awareness -> efficient operation -> improved hay enterprise margins"},
    {"label":"Hay Enterprise Budget Calculator","type":"TOOLS","evidence":"A","description":"Implement comprehensive hay enterprise budgets tracking mowing, conditioning, raking, baling, and storage costs per ton at the field level. Granular cost data identifies where machinery improvements generate the highest margin impact.","cite":"ASABE D497.7; University of Kentucky AGR-62 – Hay Production Budgets","target":"Field-level budgets -> targeted improvement -> maximum margin impact"}
  ]
});

// 6. Hay Rakes
addTreatments('p2_agri_machinery_hayforage_hayrakes.json', {
  monitoring: [
    {"label":"Windrow Quality Assessment Protocol","type":"STRATEGY","evidence":"A","description":"Implement systematic evaluation of raked windrow uniformity measuring width consistency, density distribution, and leaf content retention across field positions. Quantified windrow quality metrics guide rake speed and tine aggressiveness adjustments.","cite":"ASABE S424.1 – Forage Conditioning and Handling; Penn State Extension – Hay Raking","target":"Windrow quality metrics -> precise adjustment -> uniform baler feeding"},
    {"label":"Leaf Loss Awareness Coaching","type":"COACHING","evidence":"B","description":"Train operators to evaluate leaf loss during raking by comparing pre-rake and post-rake windrow leaf content, especially in legume-dominant stands. Understanding that leaf loss directly reduces forage protein motivates gentler raking practices.","cite":"University of Wisconsin Extension A3353 – Minimizing Hay Harvest Losses","target":"Leaf loss awareness -> gentler raking -> preserved protein content"},
    {"label":"Rake Tine and Wheel Inspection System","type":"STRUCTURAL","evidence":"A","description":"Establish inspection checklists covering tine condition, wheel bearing play, cam track wear, and windguard settings for rotary rakes, or basket condition and ground wheel alignment for wheel rakes. Structured inspections prevent uneven raking and soil contamination.","cite":"ASABE EP496.3 – Machinery Management; Vermeer Operator Manual","target":"Component inspection -> identified wear -> prevented soil contamination"},
    {"label":"Quality-Focused Raking Norms","type":"CULTURE","evidence":"B","description":"Build team norms that prioritize windrow quality over raking speed, recognizing that aggressive raking creates soil contamination and leaf loss that reduce hay value far more than the time saved. Quality norms shift operator priorities appropriately.","cite":"Journal of Extension, Vol. 51, 2013 – Forage Quality and Harvest Management","target":"Quality-first norms -> patient raking -> preserved hay value"},
    {"label":"Windrow Moisture Monitoring Probe","type":"TOOLS","evidence":"A","description":"Equip raking crews with calibrated windrow moisture probes to verify optimal raking moisture (40-50% for most forages). Objective measurement prevents premature raking that causes excessive leaf shatter and late raking that delays baling.","cite":"ASABE S358.3 – Moisture Measurement in Forages","target":"Moisture verification -> optimal raking timing -> minimized leaf loss"}
  ],
  practices: [
    {"label":"Moisture-Timed Raking Strategy","type":"STRATEGY","evidence":"A","description":"Schedule raking operations when windrow moisture is 40-50%, typically early morning with dew present, to minimize leaf shatter while maintaining stem pliability. Moisture-timed raking preserves 5-10% more leaf material than mid-day dry raking.","cite":"University of Kentucky AGR-62 – Quality Hay Production; ASABE S424.1","target":"Moisture-timed raking -> 5-10% leaf retention gain -> higher RFV hay"},
    {"label":"Rake Type Selection Coaching","type":"COACHING","evidence":"B","description":"Coach managers on matching rake type to operation scale and forage type: rotary rakes for high-volume grass operations, wheel rakes for gentle legume handling, and parallel-bar rakes for premium dairy hay. Correct rake selection prevents quality-capacity tradeoffs.","cite":"Penn State Extension – Hay Equipment Selection Guide","target":"Correct rake selection -> optimized quality-capacity balance -> matched operation needs"},
    {"label":"Raking Pattern and Direction SOP","type":"STRUCTURAL","evidence":"A","description":"Document field-specific raking patterns that align windrows with baler pickup width, minimize turning losses, and avoid raking soil into windrows on uneven terrain. Standardized patterns reduce operator variability and field-to-field inconsistency.","cite":"NRCS CPS 512 – Forage Harvest Management; ASABE EP496.3","target":"Standardized patterns -> consistent windrows -> efficient baler operation"},
    {"label":"Gentle Handling Team Standards","type":"CULTURE","evidence":"B","description":"Establish team expectations that raking is performed at appropriate ground speeds with proper tine height, not as a race. Cultural emphasis on gentle crop handling throughout the hay chain preserves the quality built during mowing and conditioning.","cite":"Hay & Forage Grower Magazine, 2019 – Reducing Harvest Chain Losses","target":"Gentle handling standards -> preserved crop quality -> maintained feed value"},
    {"label":"Rake Performance GPS Tracker","type":"TOOLS","evidence":"B","description":"Deploy GPS tracking on rakes to log ground speed, acres raked per hour, and field coverage patterns. Performance data identifies operators exceeding target speeds or creating irregular patterns that compromise windrow uniformity.","cite":"Applied Engineering in Agriculture, Vol. 34(3), 2018 – Fleet Tracking in Forage Operations","target":"GPS tracking -> speed monitoring -> enforced quality-conscious operation"}
  ],
  technology: [
    {"label":"Merger Rake Adoption Strategy","type":"STRATEGY","evidence":"B","description":"Evaluate belt merger systems as alternatives to traditional rakes for high-value legume operations where leaf retention is critical. Belt mergers handle crop without tine impact, preserving 3-5% more leaf material compared to aggressive rotary rakes.","cite":"Transactions of the ASABE, Vol. 60(4), 2017 – Forage Merger Performance","target":"Belt merger evaluation -> gentler handling -> 3-5% additional leaf preservation"},
    {"label":"Advanced Rake Technology Coaching","type":"COACHING","evidence":"C","description":"Train operators on emerging rake technologies including GPS-guided windrow placement, variable-speed rotary drives, and automated tine height adjustment. Technology awareness enables informed evaluation of upgrade opportunities.","cite":"Applied Engineering in Agriculture, Vol. 35(6), 2019 – Emerging Forage Equipment Tech","target":"Technology awareness -> informed evaluation -> targeted upgrades"},
    {"label":"Rake Fleet Data Integration","type":"STRUCTURAL","evidence":"B","description":"Integrate rake operational data with mowing and baling records to create complete harvest chain analytics. End-to-end data visibility reveals how raking timing and technique impact downstream baler performance and forage moisture outcomes.","cite":"ASABE/ISO 11783 – Agricultural Data Networks","target":"Chain integration -> end-to-end visibility -> optimized harvest sequence"},
    {"label":"Continuous Improvement Raking Culture","type":"CULTURE","evidence":"C","description":"Encourage operators to experiment with rake settings on small test areas and measure the forage quality impact before applying changes field-wide. A controlled experimentation mindset drives incremental improvement without risking whole-field quality.","cite":"Precision Agriculture, Vol. 19, 2018 – On-Farm Experimentation Methods","target":"Controlled experimentation -> measured improvements -> evidence-based changes"},
    {"label":"Windrow Width and Density Sensors","type":"TOOLS","evidence":"C","description":"Evaluate emerging sensor systems that measure windrow cross-section density and width in real time behind the rake. Automated windrow quality feedback would enable closed-loop control of raking intensity and travel speed.","cite":"Biosystems Engineering, Vol. 190, 2020 – Windrow Sensing Technology","target":"Windrow sensors -> real-time feedback -> automated quality optimization"}
  ],
  economics: [
    {"label":"Raking Leaf Loss Economic Impact","type":"STRATEGY","evidence":"A","description":"Quantify the economic cost of raking-induced leaf loss using forage test data and current hay market prices. In alfalfa, each 1% leaf loss can reduce value by $3-5/ton, creating compelling justification for gentler raking equipment and practices.","cite":"ASABE D497.7; University of Wisconsin Extension – Hay Quality Economics","target":"Leaf loss valuation -> investment justification -> net positive hay value"},
    {"label":"Rake Operating Cost Coaching","type":"COACHING","evidence":"B","description":"Coach operators on the full cost of rake ownership including depreciation, tine replacement, bearing maintenance, and fuel consumption. Understanding true operating costs supports appropriate custom rate setting and lease vs. buy decisions.","cite":"Kansas State University MF-842 – Farm Machinery Costs","target":"Operating cost awareness -> fair custom rates -> adequate capital recovery"},
    {"label":"Rake Fleet Sizing Analysis","type":"STRUCTURAL","evidence":"A","description":"Model rake fleet capacity against mowing output and baling capacity to prevent raking from becoming the harvest chain bottleneck. Fleet sizing analysis ensures rake capacity matches the windowed weather opportunity without over-investment.","cite":"ASABE D497.7; ASABE EP496.3 – Machinery Management","target":"Fleet sizing -> eliminated bottleneck -> matched chain capacity"},
    {"label":"Harvest Chain Cost Visibility","type":"CULTURE","evidence":"B","description":"Share per-ton raking costs alongside mowing and baling costs to build awareness of total harvest chain economics. Visible cost breakdowns motivate efficiency improvements at each stage rather than optimizing one stage at another's expense.","cite":"North Dakota State University EC1260 – Custom Farm Work Rates","target":"Cost visibility -> chain-wide optimization -> total cost reduction"},
    {"label":"Custom Raking Rate Spreadsheet","type":"TOOLS","evidence":"A","description":"Implement custom rate calculators specific to rake type and operating conditions, incorporating ground speed, acreage capacity, and forage density variables. Accurate rate tools ensure raking services cover costs while remaining competitive.","cite":"ASABE D497.7 – Agricultural Machinery Management Data","target":"Rate calculator -> accurate pricing -> sustainable custom raking business"}
  ]
});

// 7. Round Balers
addTreatments('p2_agri_machinery_hayforage_roundbalers.json', {
  monitoring: [
    {"label":"Bale Density and Shape Monitoring","type":"STRATEGY","evidence":"A","description":"Implement systematic bale density measurement using bale weight scales and dimension checks against target specifications. Monitoring density consistency identifies chamber pressure and belt tension issues before they produce unmarketable bales.","cite":"ASABE S432 – Standard Test Procedure for Round Balers","target":"Density monitoring -> pressure adjustment -> consistent marketable bales"},
    {"label":"Bale Wrap and Twine Quality Coaching","type":"COACHING","evidence":"B","description":"Train operators on evaluating net wrap coverage, twine spacing adequacy, and plastic wrap stretch consistency. Proper wrap assessment skills prevent storage losses from inadequate bale protection that can exceed 15% dry matter in outdoor storage.","cite":"University of Wisconsin Extension A1577 – Round Bale Storage Losses","target":"Wrap quality skills -> adequate protection -> storage losses under 5%"},
    {"label":"Baler Component Inspection Checklist","type":"STRUCTURAL","evidence":"A","description":"Establish inspection protocols covering belts or chains, pickup tines, starter rolls, tailgate latches, and wrap system components at defined bale-count intervals. Systematic inspection prevents mid-field failures during time-critical baling windows.","cite":"ASABE EP496.3 – Machinery Management; Vermeer/New Holland Maintenance Guides","target":"Systematic inspection -> prevented failures -> uninterrupted baling"},
    {"label":"Bale Quality Accountability Culture","type":"CULTURE","evidence":"B","description":"Establish that every bale produced is a reflection of operator diligence by tracking bale quality metrics per operator. When quality data is transparent, operators self-correct on chamber pressure settings, pickup speed, and moisture monitoring.","cite":"Journal of Extension, Vol. 52, 2014 – Hay Quality Management Culture","target":"Quality accountability -> self-correction -> consistently high-quality bales"},
    {"label":"Bale Moisture and Weight Scale","type":"TOOLS","evidence":"A","description":"Equip balers with integrated moisture sensors and bale weight scales that log per-bale data. Real-time moisture and weight information prevents baling at excessive moisture (fire risk) and ensures consistent density for market or feeding requirements.","cite":"ASABE S358.3 – Moisture Measurement; Bale Baron Scale Documentation","target":"Per-bale data -> moisture/density control -> safe marketable product"}
  ],
  practices: [
    {"label":"Moisture-Gated Baling Protocol","type":"STRATEGY","evidence":"A","description":"Establish firm moisture thresholds for baling initiation (under 18% for dry hay, 40-60% for baleage) with mandatory probe checks before and during baling runs. Moisture discipline prevents spontaneous combustion risk and fermentation quality failures.","cite":"NRCS CPS 512 – Forage Harvest Management; ASABE S358.3","target":"Moisture gating -> fire prevention -> safe storage outcomes"},
    {"label":"Windrow Matching and Speed Coaching","type":"COACHING","evidence":"B","description":"Coach operators on matching ground speed and pickup width to windrow size for optimal chamber filling. Consistent feeding produces uniform bale cores, prevents lopsided bales, and reduces belt and chain wear from uneven loading.","cite":"Penn State Extension – Round Baler Operation Guide; Vermeer Operator Training","target":"Matched feeding -> uniform bale cores -> reduced component wear"},
    {"label":"Bale Storage and Handling SOP","type":"STRUCTURAL","evidence":"A","description":"Document standardized bale storage protocols including site selection, orientation, spacing, and bottom barrier requirements to minimize ground contact losses. Proper storage SOPs preserve 90%+ of baled forage dry matter through the feeding season.","cite":"NRCS CPS 713 – Waste Storage Facility (adapted); University of Arkansas FSA3051","target":"Storage SOPs -> minimized ground contact -> 90%+ dry matter retention"},
    {"label":"Baling Timeliness Team Coordination","type":"CULTURE","evidence":"B","description":"Build team norms that treat baling windows as crew-wide priorities requiring coordinated mowing, raking, and baling schedules. When the whole team understands weather-window urgency, response times improve and forage quality is captured consistently.","cite":"Hay & Forage Grower, 2018 – Harvest Crew Coordination","target":"Team coordination -> rapid response -> captured weather windows"},
    {"label":"Bale Preservative Applicator","type":"TOOLS","evidence":"A","description":"Deploy propionic acid-based bale preservative applicators for situations when baling at slightly elevated moisture (18-25%) is necessary to capture a weather window. Preservative application extends safe baling moisture range by 4-6 percentage points.","cite":"Journal of Dairy Science, Vol. 97, 2014 – Hay Preservative Efficacy; ASABE S424.1","target":"Preservative application -> extended moisture range -> captured weather windows"}
  ],
  technology: [
    {"label":"Variable Chamber Pressure Strategy","type":"STRATEGY","evidence":"B","description":"Adopt variable chamber balers with programmable density profiles that increase core pressure and taper toward the outer layers. Variable density technology improves bale stability, reduces storage deformation, and optimizes wrapping material usage.","cite":"Transactions of the ASABE, Vol. 61(6), 2018 – Variable Chamber Baler Performance","target":"Variable density -> improved stability -> reduced storage deformation"},
    {"label":"Baler Technology Feature Training","type":"COACHING","evidence":"B","description":"Provide in-depth training on advanced baler features including automatic moisture-based density adjustment, CropCutter integration, and net wrap optimization settings. Full feature utilization ensures the operation captures the value of technology investments.","cite":"Applied Engineering in Agriculture, Vol. 34(4), 2018 – Advanced Baler Training","target":"Feature mastery -> full technology utilization -> maximum investment return"},
    {"label":"Bale Tracking and Inventory System","type":"STRUCTURAL","evidence":"B","description":"Implement RFID or GPS-tagged bale tracking systems that log bale location, moisture at baling, and forage source field. Digital inventory management prevents bale shrink from lost inventory and enables first-in-first-out feeding programs.","cite":"Computers and Electronics in Agriculture, Vol. 160, 2019 – Bale Tracking Systems","target":"Digital tracking -> zero inventory shrink -> optimized feeding sequence"},
    {"label":"Technology-Embracing Forage Culture","type":"CULTURE","evidence":"C","description":"Position the operation as a forage technology leader that leverages data from baling through feeding. Cultural identity as an innovative forage operation attracts skilled operators and builds customer confidence in product quality.","cite":"Precision Agriculture, Vol. 20, 2019 – Innovation Culture in Agriculture","target":"Innovation identity -> operator attraction -> customer confidence"},
    {"label":"Bale Documentation Camera System","type":"TOOLS","evidence":"C","description":"Install camera systems monitoring bale formation, wrap application, and ejection quality in real time. Visual documentation enables remote quality checks and provides evidence for warranty claims or customer quality disputes.","cite":"Biosystems Engineering, Vol. 192, 2020 – Visual Monitoring in Hay Operations","target":"Camera monitoring -> quality documentation -> dispute resolution capability"}
  ],
  economics: [
    {"label":"Bale Loss Cost Quantification","type":"STRATEGY","evidence":"A","description":"Calculate the economic impact of bale storage losses, handling damage, and moisture-related spoilage at current hay market prices. Quantified loss costs often justify investment in improved storage facilities, wrap systems, or moisture monitoring equipment.","cite":"ASABE D497.7; University of Wisconsin Extension A1577 – Bale Storage Economics","target":"Loss quantification -> justified storage investment -> recovered revenue"},
    {"label":"Baler Ownership Cost Coaching","type":"COACHING","evidence":"B","description":"Coach operators on total baler ownership costs including depreciation, belt/chain replacement, pickup tine costs, and wrap material consumption. Accurate cost knowledge supports informed decisions on baler replacement cycles and custom baling rates.","cite":"Kansas State University MF-842 – Farm Machinery Costs","target":"Total cost knowledge -> informed replacement -> profitable custom rates"},
    {"label":"Bale Marketing Quality Standards","type":"STRUCTURAL","evidence":"A","description":"Develop quality grading standards for bales including density targets, moisture maximums, and forage test requirements for different market channels. Standardized quality grades enable premium pricing and reduce buyer negotiation friction.","cite":"USDA AMS – Hay Quality Designation Guidelines; Hay Market Reports","target":"Quality standards -> premium pricing -> reduced negotiation friction"},
    {"label":"Value-Focused Baling Mindset","type":"CULTURE","evidence":"B","description":"Shift cultural focus from bales-per-hour metrics to value-per-bale thinking that accounts for density, moisture, forage quality, and wrap integrity. Value-focused operations consistently outperform volume-focused operations in net revenue per ton.","cite":"Journal of the ASFMRA, 2019 – Hay Enterprise Profitability Factors","target":"Value-per-bale focus -> quality consistency -> higher net revenue per ton"},
    {"label":"Baling Enterprise Budget Tool","type":"TOOLS","evidence":"A","description":"Implement enterprise budgets tracking per-bale costs including equipment, labor, wrap/twine, fuel, and preservatives across fields and cuttings. Granular cost data identifies which fields and cuttings generate positive margins and which should be custom-baled.","cite":"ASABE D497.7; University of Kentucky – Hay Enterprise Budgets","target":"Per-bale budgets -> margin visibility -> informed make-vs-buy decisions"}
  ]
});

// 8. Square Balers
addTreatments('p2_agri_machinery_hayforage_squarebalers.json', {
  monitoring: [
    {"label":"Bale Dimension and Density Tracking","type":"STRATEGY","evidence":"A","description":"Monitor bale weight, length, and density consistency using integrated scales and dimension measurements at regular intervals. Tracking density trends identifies plunger timing, feed rate, and chamber pressure issues before they produce inconsistent bales.","cite":"ASABE S433 – Rectangular Baler Test Procedure","target":"Density tracking -> early drift detection -> consistent bale specifications"},
    {"label":"Knotter Function Inspection Coaching","type":"COACHING","evidence":"B","description":"Train operators on pre-shift knotter inspection including bill hook sharpness, twine disc alignment, trip mechanism function, and twine tension settings. Knotter-related failures are the primary cause of small square baler downtime and missed twine ties.","cite":"University of Wisconsin Extension – Square Baler Maintenance; New Holland Manuals","target":"Knotter inspection skills -> reduced missed ties -> minimized downtime"},
    {"label":"Baler Mechanical Inspection Protocol","type":"STRUCTURAL","evidence":"A","description":"Establish 100-bale and 1000-bale inspection schedules covering plunger knife sharpness, pickup tine integrity, auger finger condition, and chamber rail wear. Interval-based inspection prevents progressive wear from causing catastrophic component failure.","cite":"ASABE EP496.3 – Machinery Management; Case IH Maintenance Schedules","target":"Interval inspections -> progressive wear detection -> prevented catastrophic failure"},
    {"label":"Premium Bale Pride Culture","type":"CULTURE","evidence":"B","description":"Foster operator pride in producing consistently tied, dense, square-cornered bales that stack securely and present well to retail hay customers. Premium bale appearance directly impacts market pricing and customer retention in small-bale markets.","cite":"Hay & Forage Grower, 2019 – Small Square Bale Marketing","target":"Bale pride -> consistent quality -> premium pricing and customer retention"},
    {"label":"Bale Count and Weight Monitor","type":"TOOLS","evidence":"A","description":"Install electronic bale counters with integrated weight sensors logging per-bale data and cumulative production statistics. Automated counting and weighing enables accurate inventory management, load planning, and per-bale cost tracking.","cite":"ASABE S433; Ag Leader Bale Weight Documentation","target":"Automated monitoring -> accurate inventory -> precise cost-per-bale tracking"}
  ],
  practices: [
    {"label":"Feed Rate and Plunger Load Matching","type":"STRATEGY","evidence":"A","description":"Establish ground speed targets that maintain consistent windrow feeding rates matched to plunger stroke capacity. Over-feeding causes plunger overload and missed knotter trips, while under-feeding produces loose, poorly shaped bales.","cite":"ASABE S433; Penn State Extension – Square Baler Operation","target":"Feed rate matching -> consistent plunger load -> uniform bale quality"},
    {"label":"Twine Selection and Tension Coaching","type":"COACHING","evidence":"B","description":"Coach operators on selecting appropriate twine strength for bale density and size, and on setting tension arms to achieve firm ties without twine breakage. Proper twine management prevents both loose bales and excessive knotter failure rates.","cite":"University of Kentucky AGR-62 – Hay Production; Twine Manufacturer Guidelines","target":"Correct twine management -> firm ties -> reduced breakage and loose bales"},
    {"label":"Bale Handling and Stacking SOP","type":"STRUCTURAL","evidence":"A","description":"Document standardized stacking patterns, transport procedures, and storage configurations that prevent bale deformation, moisture wicking, and structural collapse. Proper handling SOPs protect the value created during baling through the storage period.","cite":"NRCS CPS 713 (adapted); University of Arkansas FSA3051 – Hay Storage","target":"Handling SOPs -> prevented deformation -> preserved market-quality bales"},
    {"label":"Customer Quality Communication","type":"CULTURE","evidence":"B","description":"Build a culture of proactive quality communication with hay customers, sharing forage test results, bale weights, and harvest date information. Transparent quality communication builds trust and supports premium pricing in competitive small-bale markets.","cite":"Journal of Extension, Vol. 54, 2016 – Hay Marketing Best Practices","target":"Quality transparency -> customer trust -> premium market positioning"},
    {"label":"Plunger Knife Sharpening System","type":"TOOLS","evidence":"A","description":"Maintain a field-serviceable knife sharpening or replacement system to restore cutting edge quality when bales show ragged or uneven chamber fill. Sharp plunger knives reduce PTO load, improve bale appearance, and extend baler component life.","cite":"ASABE S346 – Cutting Component Standards; New Holland Operator Manual","target":"Sharp knives -> reduced PTO load -> improved bale quality and baler longevity"}
  ],
  technology: [
    {"label":"Large Square Baler Automation Strategy","type":"STRATEGY","evidence":"B","description":"Evaluate large square baler automation features including auto-density adjustment, pre-cut systems, and auto-tie monitoring for operations transitioning from small to large square bale format. Automation reduces operator skill requirements and improves consistency.","cite":"Transactions of the ASABE, Vol. 62(2), 2019 – Large Square Baler Technology","target":"Automation evaluation -> informed format transition -> consistent large-bale quality"},
    {"label":"Pre-Cut System Operation Training","type":"COACHING","evidence":"B","description":"Train operators on pre-cut knife system operation, adjustment, and maintenance for large square balers. Proper pre-cut length settings improve bale density, animal intake, and TMR mixing characteristics while affecting baler throughput.","cite":"Applied Engineering in Agriculture, Vol. 35(1), 2019 – Pre-Cut Hay Baler Performance","target":"Pre-cut mastery -> optimized cut length -> improved feed processing"},
    {"label":"Bale Tracking RFID Infrastructure","type":"STRUCTURAL","evidence":"B","description":"Deploy RFID tag insertion systems that embed identification tags during baling, linking each bale to field source, moisture, and production date. RFID infrastructure enables automated inventory management and complete traceability for commercial hay sales.","cite":"Computers and Electronics in Agriculture, Vol. 165, 2019 – RFID Bale Tracking","target":"RFID tagging -> automated inventory -> complete bale traceability"},
    {"label":"Precision Hay Innovation Mindset","type":"CULTURE","evidence":"C","description":"Encourage the team to view hay production as a precision agriculture enterprise where technology investments in baling, storage, and marketing generate measurable returns. Precision mindset drives adoption of data-informed practices across the hay chain.","cite":"Precision Agriculture, Vol. 21, 2020 – Precision Forage Management","target":"Precision mindset -> data-informed practices -> measured improvement"},
    {"label":"Baler Diagnostic Telematics System","type":"TOOLS","evidence":"B","description":"Deploy telematics systems monitoring plunger load, knotter success rate, hydraulic pressure, and PTO torque in real time. Remote diagnostic capability enables dealer support and predictive maintenance scheduling based on actual usage patterns.","cite":"ASABE X629 – Onboard Diagnostics; CNH Connected Solutions","target":"Telematics diagnostics -> predictive maintenance -> minimized unplanned downtime"}
  ],
  economics: [
    {"label":"Small vs. Large Square Economic Analysis","type":"STRATEGY","evidence":"A","description":"Conduct breakeven analysis comparing small and large square bale production costs, market prices, and customer accessibility. Format economics vary significantly by region and market channel, making data-driven format selection essential for profitability.","cite":"ASABE D497.7; North Dakota State University EC1260 – Custom Rates","target":"Format comparison -> data-driven selection -> maximized market margin"},
    {"label":"Custom Baling Profitability Coaching","type":"COACHING","evidence":"B","description":"Coach custom baling operators on calculating fully loaded per-bale costs including twine, fuel, labor, repairs, depreciation, and travel time. Accurate cost knowledge prevents unprofitable custom rates that subsidize customer operations.","cite":"Kansas State University MF-842 – Farm Machinery Costs","target":"Full cost awareness -> profitable custom rates -> sustainable baling business"},
    {"label":"Hay Market Channel Framework","type":"STRUCTURAL","evidence":"A","description":"Develop formalized market channel strategies matching bale format, quality grade, and volume to specific customer segments (dairy, horse, export, retail). Channel frameworks ensure production decisions align with highest-value market opportunities.","cite":"USDA AMS – Hay Market Reports; Journal of the ASFMRA, 2018","target":"Channel strategy -> matched production -> highest-value market access"},
    {"label":"Quality Premium Pursuit Culture","type":"CULTURE","evidence":"B","description":"Orient the team around capturing quality premiums through superior bale appearance, consistent density, and certified forage test results. Premium-focused operations earn $20-40/ton premiums in horse and dairy hay markets.","cite":"Hay & Forage Grower, 2019 – Premium Hay Marketing Strategies","target":"Premium pursuit -> superior quality -> $20-40/ton market premiums"},
    {"label":"Baling Cost Per Ton Calculator","type":"TOOLS","evidence":"A","description":"Implement per-ton baling cost calculators tracking all direct and indirect costs by bale format and field conditions. Cost-per-ton tools enable accurate comparison across production methods and support competitive custom rate negotiations.","cite":"ASABE D497.7 – Agricultural Machinery Management Data","target":"Per-ton costing -> accurate comparisons -> informed business decisions"}
  ]
});

// 9. Rotary Mowers
addTreatments('p2_agri_machinery_implements_rotarymowers.json', {
  monitoring: [
    {"label":"Blade Condition Assessment Schedule","type":"STRATEGY","evidence":"A","description":"Implement systematic blade inspection measuring edge sharpness, balance, and bolt torque at 10-hour operating intervals. Monitoring blade condition prevents uneven cutting, excessive vibration, and the safety hazards of thrown blade fragments.","cite":"ASABE S396.2 – Rotary Mower Performance Standards; OSHA 1928 Agricultural Safety","target":"Blade monitoring -> balanced cutting -> prevented vibration damage and safety hazards"},
    {"label":"Cut Quality Field Evaluation Coaching","type":"COACHING","evidence":"B","description":"Train operators to evaluate cut quality by inspecting stubble height uniformity, stem tearing versus clean cutting, and scalping on uneven terrain. Visual cut quality assessment identifies blade dullness and deck height issues requiring immediate correction.","cite":"University of Arkansas FSA1013 – Rotary Mower Management","target":"Cut quality skills -> identified issues -> immediate correction"},
    {"label":"Pre-Use Safety and Function Checklist","type":"STRUCTURAL","evidence":"A","description":"Establish mandatory pre-operation checklists covering PTO shield integrity, blade bolt torque, deck condition, wheel bearing play, and three-point hitch pin security. Pre-use checks prevent the serious safety incidents common with rotary mowing equipment.","cite":"ASABE S361.1 – Safety for Agricultural Equipment; OSHA Agricultural Standards","target":"Safety checklist -> hazard prevention -> protected operators and bystanders"},
    {"label":"Maintenance Reporting Culture","type":"CULTURE","evidence":"B","description":"Normalize immediate reporting of blade damage, unusual vibration, or deck strikes rather than continuing operation. A culture where equipment issues are reported promptly prevents compounding damage and maintains safe operating conditions.","cite":"NIOSH 2018 – Agricultural Equipment Safety Best Practices","target":"Prompt reporting -> prevented compounding damage -> maintained safety"},
    {"label":"Vibration Monitoring Sensor","type":"TOOLS","evidence":"B","description":"Deploy vibration sensors on mower deck spindles to detect blade imbalance, bearing wear, and gearbox issues before they cause structural damage. Continuous vibration monitoring extends component life and prevents catastrophic deck failures.","cite":"Biosystems Engineering, Vol. 175, 2018 – Vibration Analysis in Mowing Equipment","target":"Vibration sensing -> early detection -> extended component life"}
  ],
  practices: [
    {"label":"Cutting Height Optimization Strategy","type":"STRATEGY","evidence":"A","description":"Establish cutting height targets based on land use: 3-4 inches for improved pastures to maintain stand health, 6+ inches for native grass areas per NRCS guidelines, and variable heights for roadside or conservation mowing. Height management balances productivity with vegetation persistence.","cite":"NRCS CPS 528 – Prescribed Grazing; NRCS CPS 314 – Brush Management","target":"Height optimization -> stand persistence -> balanced productivity and conservation"},
    {"label":"Terrain and Obstacle Awareness Coaching","type":"COACHING","evidence":"B","description":"Coach operators on pre-mowing field scouting for rocks, stumps, metal debris, and terrain hazards. Obstacle awareness prevents blade damage, thrown-object injuries, and costly deck repairs that exceed the value of time saved by skipping reconnaissance.","cite":"ASABE S361.1 – Safety Standards; University Extension – Safe Mowing Practices","target":"Obstacle awareness -> prevented blade damage -> reduced repair costs and injuries"},
    {"label":"Seasonal Mowing Schedule SOP","type":"STRUCTURAL","evidence":"A","description":"Document mowing schedules aligned with vegetation growth patterns, wildlife nesting seasons, and weed seed-head timing. Ecologically timed mowing reduces weed pressure, protects ground-nesting species, and maximizes forage regrowth potential.","cite":"NRCS CPS 647 – Early Successional Habitat; NRCS CPS 528 – Prescribed Grazing","target":"Timed mowing -> weed reduction -> wildlife protection + forage benefit"},
    {"label":"Multi-Use Mowing Stewardship","type":"CULTURE","evidence":"B","description":"Build awareness that rotary mowing serves multiple functions including weed management, pasture renovation, firebreak maintenance, and aesthetic upkeep. Multi-purpose thinking ensures mowing decisions consider all stakeholder values, not just visual appearance.","cite":"NRCS CPS 314 – Brush Management; Conservation Biology, Vol. 32, 2018","target":"Multi-purpose awareness -> holistic mowing decisions -> balanced outcomes"},
    {"label":"Blade Sharpening and Balancing Kit","type":"TOOLS","evidence":"A","description":"Equip maintenance shops with blade sharpening grinders and static balancing cones for on-site blade service. Sharp, balanced blades reduce fuel consumption by 10-15%, improve cut quality, and extend spindle bearing and gearbox life.","cite":"ASABE S396.2 – Mower Performance; Kansas State University – Mower Maintenance","target":"Sharp balanced blades -> 10-15% fuel savings -> extended component life"}
  ],
  technology: [
    {"label":"GPS-Guided Mowing Optimization","type":"STRATEGY","evidence":"B","description":"Implement GPS guidance for rotary mowing operations to optimize mowing patterns, minimize overlap, and document area coverage for billing or compliance reporting. GPS guidance reduces fuel waste and provides verifiable mowing records.","cite":"Computers and Electronics in Agriculture, Vol. 150, 2018 – GPS-Guided Vegetation Management","target":"GPS guidance -> minimized overlap -> verified coverage records"},
    {"label":"Autonomous Mowing Technology Awareness","type":"COACHING","evidence":"C","description":"Introduce operators to emerging autonomous and robotic mowing technologies applicable to large-area vegetation management. Understanding automation trends helps operations plan for future labor efficiency and technology integration.","cite":"Biosystems Engineering, Vol. 200, 2020 – Autonomous Agricultural Mowing Systems","target":"Technology awareness -> future planning -> prepared for automation integration"},
    {"label":"Fleet Telematics for Mowing Operations","type":"STRUCTURAL","evidence":"B","description":"Deploy telematics tracking on mowing fleets to monitor engine hours, fuel consumption, area covered, and maintenance intervals. Fleet data enables accurate cost allocation, preventive maintenance scheduling, and utilization optimization.","cite":"ASABE/ISO 11783 – Agricultural Equipment Data Networks","target":"Fleet telematics -> accurate cost allocation -> optimized utilization"},
    {"label":"Technology-Forward Grounds Management","type":"CULTURE","evidence":"C","description":"Position the mowing operation as technology-progressive by piloting GPS tracking, automated blade monitoring, and digital work order systems. Early adoption in vegetation management builds organizational capacity for larger precision agriculture technologies.","cite":"Journal of Extension, Vol. 56, 2018 – Technology Adoption Pathways","target":"Progressive piloting -> built capability -> readiness for advanced tech"},
    {"label":"Deck Height Sensing System","type":"TOOLS","evidence":"B","description":"Install ultrasonic or mechanical deck height sensors providing real-time cutting height feedback to the operator. Automated height monitoring prevents scalping on high spots and insufficient cutting in depressions across irregular terrain.","cite":"Applied Engineering in Agriculture, Vol. 34(6), 2018 – Height Control in Mowing","target":"Height sensing -> terrain-responsive cutting -> uniform results across fields"}
  ],
  economics: [
    {"label":"Mowing Cost Per Acre Analysis","type":"STRATEGY","evidence":"A","description":"Calculate fully loaded per-acre mowing costs including depreciation, fuel, blades, labor, and travel to inform pricing for custom mowing and internal cost allocation. Accurate cost data prevents subsidizing mowing with other enterprise revenues.","cite":"ASABE D497.7 – Agricultural Machinery Management Data","target":"Per-acre costing -> accurate pricing -> prevented cross-enterprise subsidies"},
    {"label":"Buy vs. Hire Decision Coaching","type":"COACHING","evidence":"B","description":"Coach managers on breakeven analysis for owning rotary mowers versus hiring custom mowing services, incorporating annual hours of use, maintenance capability, and timeliness requirements. Breakeven analysis prevents uneconomic equipment purchases.","cite":"Kansas State University MF-842 – Farm Machinery Costs","target":"Breakeven analysis -> informed ownership decisions -> optimized capital allocation"},
    {"label":"Mowing Contract Specification Framework","type":"STRUCTURAL","evidence":"A","description":"Develop standardized mowing service contracts specifying cutting height, frequency, area boundaries, obstruction liability, and quality standards. Clear contracts reduce disputes and ensure service expectations are mutually understood.","cite":"North Dakota State University EC1260 – Custom Work Rates","target":"Standard contracts -> clear expectations -> reduced disputes"},
    {"label":"Cost Transparency in Vegetation Management","type":"CULTURE","evidence":"B","description":"Share mowing cost data across management to build understanding of vegetation management as a necessary operating expense rather than discretionary spending. Cost transparency supports appropriate budgeting and prevents deferred maintenance.","cite":"Journal of the ASFMRA, 2019 – Farm Infrastructure Cost Management","target":"Cost transparency -> appropriate budgeting -> prevented deferred maintenance"},
    {"label":"Mowing Equipment Cost Tracker","type":"TOOLS","evidence":"A","description":"Implement digital tracking systems logging per-machine costs including fuel receipts, blade purchases, maintenance labor, and repair parts. Machine-level cost data identifies high-maintenance units and validates replacement timing decisions.","cite":"ASABE D497.7 – Agricultural Machinery Management Data","target":"Machine-level tracking -> identified cost outliers -> justified replacement timing"}
  ]
});

console.log('Batch 1 complete: 9 files processed');
