const fs = require('fs');
const path = require('path');
const DIR = path.join(__dirname, '..', 'assets', 'data', 'domains');

function addTreatments(filename, treatments) {
  const fp = path.join(DIR, filename);
  const data = JSON.parse(fs.readFileSync(fp, 'utf8'));
  data.activations.forEach((act) => {
    const group = act.group;
    let key = group === 'diagnostics' ? 'monitoring' : group === 'practices' ? 'practices' : group === 'innovation' ? 'technology' : 'economics';
    act.treatments = treatments[key];
  });
  fs.writeFileSync(fp, JSON.stringify(data, null, 2) + '\n');
  console.log('OK ' + filename);
}

// 10. Blade & Scrapers
addTreatments('p2_agri_machinery_implements_bladescrapers.json', {
  monitoring: [
    {"label":"Cutting Edge Wear Measurement Protocol","type":"STRATEGY","evidence":"A","description":"Implement scheduled measurement of blade cutting edge thickness and scraper shoe wear using depth gauges at defined operating-hour intervals. Quantified wear tracking enables proactive edge replacement before grading quality deteriorates.","cite":"ASABE EP486 – Earthmoving Equipment Standards; Caterpillar Operator Manual","target":"Wear measurement -> predictive replacement -> maintained grading quality"},
    {"label":"Grade Quality Visual Assessment Coaching","type":"COACHING","evidence":"B","description":"Train operators to evaluate finished grade quality by checking crown consistency, drainage slope uniformity, and surface smoothness. Visual assessment skills enable real-time blade angle and depth corrections during grading passes.","cite":"NRCS CPS 560 – Access Road; NRCS CPS 362 – Diversion Construction","target":"Grade assessment skills -> real-time corrections -> specified surface quality"},
    {"label":"Pre-Operation Equipment Checklist","type":"STRUCTURAL","evidence":"A","description":"Establish inspection protocols covering cutting edge bolts, moldboard condition, hydraulic cylinder integrity, and hitch pin security before each use session. Systematic pre-checks prevent mid-job failures and maintain operator safety.","cite":"ASABE S361.1 – Safety Standards; OSHA Construction Equipment Guidelines","target":"Pre-operation checks -> prevented failures -> maintained safety"},
    {"label":"Grade-Right-First-Time Culture","type":"CULTURE","evidence":"B","description":"Foster operator pride in achieving specification-grade surfaces on the first pass by emphasizing that rework wastes fuel, time, and equipment life. First-pass quality culture motivates careful blade angle setting and speed management.","cite":"Journal of Extension, Vol. 50, 2012 – Equipment Operator Best Practices","target":"First-pass quality -> eliminated rework -> reduced fuel and time waste"},
    {"label":"Laser Grade Control System","type":"TOOLS","evidence":"A","description":"Deploy laser-guided or GPS-based grade control systems that automatically maintain blade elevation relative to design grade. Automated grade control achieves sub-inch accuracy and eliminates the variability inherent in manual blade operation.","cite":"ASABE S561 – GPS Guidance Standards; Topcon and Trimble Grade Control Documentation","target":"Automated grade control -> sub-inch accuracy -> consistent design-grade surfaces"}
  ],
  practices: [
    {"label":"Soil Condition-Based Operation Strategy","type":"STRATEGY","evidence":"A","description":"Schedule blade and scraper work based on optimal soil moisture conditions that allow clean cutting without excessive soil smearing or dust generation. Moisture-timed operations achieve better surface finish with less fuel consumption and equipment wear.","cite":"NRCS CPS 560 – Access Road; NRCS Engineering Field Handbook Ch. 4","target":"Moisture-timed work -> clean cutting -> better finish with less wear"},
    {"label":"Multi-Pass Grading Technique Coaching","type":"COACHING","evidence":"B","description":"Coach operators on progressive grading techniques using light initial passes to establish grade, followed by finish passes with adjusted blade angles. Multi-pass methodology prevents overcutting, maintains subgrade integrity, and produces smoother surfaces.","cite":"University Extension – Road Maintenance Guide; NRCS CPS 560","target":"Progressive technique -> prevented overcutting -> smooth finished surfaces"},
    {"label":"Drainage-Integrated Grading SOP","type":"STRUCTURAL","evidence":"A","description":"Document grading procedures that maintain positive drainage slopes, crowned road surfaces, and functional ditch profiles per NRCS engineering standards. Drainage-integrated SOPs prevent the standing water problems that cause rapid road deterioration.","cite":"NRCS CPS 560 – Access Road; NRCS CPS 362 – Diversion; NRCS EFH Ch. 14","target":"Drainage integration -> eliminated standing water -> extended road surface life"},
    {"label":"Road Stewardship Mindset","type":"CULTURE","evidence":"B","description":"Build team awareness that proper blade work is infrastructure maintenance, not just dirt moving. When operators understand that well-maintained roads reduce vehicle damage, improve safety, and preserve property value, they invest more care in grading quality.","cite":"National Association of County Engineers – Road Maintenance Standards","target":"Stewardship mindset -> careful grading -> protected infrastructure investment"},
    {"label":"Blade Cutting Edge Inventory Kit","type":"TOOLS","evidence":"A","description":"Maintain on-site inventory of replacement cutting edges, end bits, and mounting hardware sized to the operation's blade and scraper equipment. Ready parts availability enables same-day edge replacement when wear measurements indicate the need.","cite":"ASABE EP486 – Earthmoving Standards; Caterpillar Parts Manual","target":"Parts availability -> same-day replacement -> minimized quality-degraded operating hours"}
  ],
  technology: [
    {"label":"GPS Grade Design Integration","type":"STRATEGY","evidence":"B","description":"Adopt GPS-based grade design systems that translate survey data into blade control coordinates, enabling operators to execute complex grade profiles from in-cab displays. Design integration eliminates staking requirements and reduces survey crew dependency.","cite":"Computers and Electronics in Agriculture, Vol. 155, 2018 – GPS in Earthmoving","target":"Design integration -> eliminated staking -> reduced survey dependency"},
    {"label":"Grade Control Technology Training","type":"COACHING","evidence":"B","description":"Provide hands-on training on laser and GPS grade control system operation including calibration procedures, reference station setup, and troubleshooting common signal issues. Technology proficiency maximizes the accuracy benefits of automated systems.","cite":"Applied Engineering in Agriculture, Vol. 34(5), 2018 – Machine Control Training","target":"Technology proficiency -> maximized accuracy -> consistent design execution"},
    {"label":"Digital As-Built Documentation","type":"STRUCTURAL","evidence":"B","description":"Implement GPS-based as-built documentation that records actual finished grades for comparison against design specifications. Digital as-built records provide compliance verification for conservation practice certification and contractor payment authorization.","cite":"NRCS Engineering Technical Note – GPS Survey Standards; Trimble Documentation","target":"Digital as-built -> compliance verification -> streamlined certification"},
    {"label":"Precision Earthwork Culture","type":"CULTURE","evidence":"C","description":"Build team identity around precision earthmoving where technology-enabled accuracy is a point of professional pride. Precision culture motivates operators to maintain grade control equipment and follow calibration protocols consistently.","cite":"Journal of Extension, Vol. 55, 2017 – Technology Pride in Agricultural Operations","target":"Precision identity -> maintained equipment -> consistent calibration compliance"},
    {"label":"3D Machine Control Platform","type":"TOOLS","evidence":"B","description":"Evaluate 3D machine control platforms that provide real-time blade position display in three dimensions relative to design surfaces. Full 3D control enables complex grading without grade stakes and reduces experienced-operator dependency.","cite":"ASABE S561; Trimble Earthworks and Topcon 3D-MC Documentation","target":"3D control -> complex grading capability -> reduced skill dependency"}
  ],
  economics: [
    {"label":"Road Maintenance Cost-Benefit Analysis","type":"STRATEGY","evidence":"A","description":"Model the total cost of road maintenance including grading, material addition, and drainage upkeep against the cost of road deterioration including vehicle damage, access delays, and safety incidents. Cost-benefit analysis justifies proactive maintenance investment.","cite":"ASABE D497.7; National Association of County Engineers – Road Cost Models","target":"Cost-benefit modeling -> justified proactive maintenance -> reduced total road costs"},
    {"label":"Equipment Sizing and Utilization Coaching","type":"COACHING","evidence":"B","description":"Coach managers on matching blade and scraper size to tractor horsepower, typical job scope, and annual utilization hours for optimal cost efficiency. Oversized equipment wastes capital; undersized equipment wastes labor and fuel on repeated passes.","cite":"Kansas State University MF-842 – Farm Machinery Costs; ASABE D497.7","target":"Correct sizing -> optimal cost efficiency -> balanced capital and operating costs"},
    {"label":"Grading Service Rate Framework","type":"STRUCTURAL","evidence":"A","description":"Develop rate structures for internal and custom grading services based on equipment costs, fuel consumption, operator labor, and cutting edge replacement frequency. Standardized rates ensure cost recovery and prevent subsidized services.","cite":"North Dakota State University EC1260 – Custom Farm Work Rates","target":"Standardized rates -> full cost recovery -> sustainable grading services"},
    {"label":"Infrastructure Investment Value Culture","type":"CULTURE","evidence":"B","description":"Build management awareness that road and pad infrastructure represents significant farm capital requiring systematic maintenance to preserve value. Infrastructure-aware culture prevents the deferred maintenance that causes expensive reconstruction.","cite":"Journal of the ASFMRA, 2018 – Farm Infrastructure Valuation","target":"Infrastructure awareness -> systematic maintenance -> preserved capital value"},
    {"label":"Grading Cost Per Hour Calculator","type":"TOOLS","evidence":"A","description":"Implement cost-per-hour calculators for blade and scraper operations incorporating depreciation, cutting edge wear, fuel, hydraulic fluid, and operator labor. Hourly cost data supports accurate job quoting and internal cost allocation.","cite":"ASABE D497.7 – Agricultural Machinery Management Data","target":"Hourly cost tracking -> accurate quoting -> proper cost allocation"}
  ]
});

// 11. Post Hole Diggers
addTreatments('p2_agri_machinery_implements_postholediggers.json', {
  monitoring: [
    {"label":"Auger Bit Condition Assessment","type":"STRATEGY","evidence":"A","description":"Implement regular inspection of auger cutting teeth, pilot bit condition, and flight wear against manufacturer replacement specifications. Worn auger components increase required drilling force, stress PTO drivetrains, and produce oversized, irregular holes.","cite":"ASABE EP496.3 – Machinery Management; Danuser Auger Maintenance Guide","target":"Auger inspection -> timely tooth replacement -> clean consistent holes"},
    {"label":"Soil Condition Evaluation Coaching","type":"COACHING","evidence":"B","description":"Train operators to assess soil type, moisture, and rock content before selecting auger diameter and drilling speed. Pre-drilling soil evaluation prevents auger damage on hidden rock, reduces stalling events, and produces cleaner holes in variable soils.","cite":"NRCS Engineering Field Handbook Ch. 4 – Geology and Soils","target":"Soil assessment skills -> prevented auger damage -> cleaner holes in variable soils"},
    {"label":"PTO Driveline Safety Inspection","type":"STRUCTURAL","evidence":"A","description":"Establish mandatory pre-use inspection of PTO shaft shielding, shear bolt integrity, slip clutch adjustment, and three-point hitch pin security. PTO driveline failures on post hole diggers are a leading cause of serious farm injuries.","cite":"ASABE S361.1 – Safety Standards; OSHA 1928 – Agricultural Safety","target":"Driveline inspection -> shielding verification -> prevented PTO entanglement injuries"},
    {"label":"Safety-First Digging Culture","type":"CULTURE","evidence":"A","description":"Establish an absolute rule that no person stands within the swing arc of the auger during operation, and that PTO engagement only occurs with the operator seated. Zero-tolerance safety norms prevent the catastrophic injuries unique to post hole digger operations.","cite":"NIOSH 2018 – Agricultural Equipment Safety; ASABE S361.1","target":"Zero-tolerance safety -> prevented entanglement -> protected operators"},
    {"label":"Auger Torque and Depth Gauge","type":"TOOLS","evidence":"B","description":"Install torque limiters and depth markers on post hole digger masts to provide objective measurement of drilling resistance and achieved hole depth. Quantified depth and torque data ensure consistent post-setting depth across fence lines.","cite":"Applied Engineering in Agriculture, Vol. 33(4), 2017 – Fence Post Equipment","target":"Depth and torque measurement -> consistent hole specs -> uniform fence quality"}
  ],
  practices: [
    {"label":"Fence Line Layout Planning Strategy","type":"STRATEGY","evidence":"A","description":"Complete fence line survey and hole location marking before mobilizing drilling equipment, including utility locate verification and corner/brace post identification. Pre-planned layouts prevent field-change delays and ensure code-compliant utility clearances.","cite":"NRCS CPS 382 – Fence; NRCS CPS 614 – Watering Facility (related layouts)","target":"Pre-planned layout -> eliminated rework -> code-compliant fence installation"},
    {"label":"Auger Speed and Feed Rate Coaching","type":"COACHING","evidence":"B","description":"Coach operators on matching PTO speed and downward feed rate to soil conditions: slower speeds in rocky or clay soils to prevent stalling, faster rotation in sandy soils with controlled feed to prevent auger walking. Matched technique extends equipment life.","cite":"University of Missouri Extension G1192 – Fence Construction Guide","target":"Matched technique -> prevented stalling -> extended auger and gearbox life"},
    {"label":"Post Depth and Spacing SOP","type":"STRUCTURAL","evidence":"A","description":"Document standard hole depth and spacing requirements for different fence types: 3.5 ft depth for line posts, 4+ ft for corner/brace assemblies, and species-specific depths for high-tensile, barbed, and electric fence configurations per NRCS standards.","cite":"NRCS CPS 382 – Fence; Midwest Plan Service MWPS-1 – Fencing Systems","target":"Documented standards -> correct depths -> structurally sound fence installations"},
    {"label":"Quality Fence Building Pride","type":"CULTURE","evidence":"B","description":"Foster operator pride in producing straight, properly spaced, and correctly depth-set fence post holes that enable quality fence construction. Well-drilled holes are the foundation of fences that last 20+ years without structural remediation.","cite":"Journal of Extension, Vol. 49, 2011 – Fence Construction Best Practices","target":"Quality pride -> precise holes -> fences lasting 20+ years"},
    {"label":"Rock Detection Probe Rod","type":"TOOLS","evidence":"A","description":"Equip fence crews with probe rods for pre-drilling rock detection at planned hole locations. Probing identifies subsurface rock that requires alternative drilling approaches or hole relocation, preventing auger damage and excessive downtime.","cite":"NRCS Engineering Field Handbook Ch. 4; Fence Industry Best Practices","target":"Rock probing -> identified obstructions -> prevented auger damage and delays"}
  ],
  technology: [
    {"label":"Hydraulic Post Driver Integration","type":"STRATEGY","evidence":"B","description":"Evaluate hydraulic post driver systems as alternatives to augered holes for steel T-posts and small-diameter wood posts. Post drivers eliminate spoil handling, reduce soil disturbance, and increase installation rates by 3-5x versus augering and backfilling.","cite":"Transactions of the ASABE, Vol. 59(6), 2016 – Post Installation Methods","target":"Post driver evaluation -> reduced soil disturbance -> 3-5x faster installation"},
    {"label":"Alternative Installation Method Training","type":"COACHING","evidence":"B","description":"Train crews on the full range of post installation technologies including hydraulic drivers, screw-in anchors, and pneumatic tools to match installation method to soil conditions and post type. Method versatility prevents one-tool-for-all-jobs inefficiency.","cite":"Applied Engineering in Agriculture, Vol. 33(2), 2017 – Post Installation Technologies","target":"Method versatility -> matched technique -> efficient installation across conditions"},
    {"label":"GPS Fence Line Mapping System","type":"STRUCTURAL","evidence":"B","description":"Implement GPS-based fence line mapping that records post locations, fence type, and installation date for maintenance planning and property boundary documentation. Digital fence inventories support depreciation tracking and replacement scheduling.","cite":"Computers and Electronics in Agriculture, Vol. 145, 2018 – Farm Infrastructure Mapping","target":"GPS mapping -> digital inventory -> planned maintenance and replacement"},
    {"label":"Innovation in Fence Infrastructure","type":"CULTURE","evidence":"C","description":"Encourage evaluation of new fence post materials (composite, fiberglass), installation methods (vibration-driven), and monitoring technologies (fence tension sensors) to improve long-term fence infrastructure performance and reduce labor requirements.","cite":"Journal of Extension, Vol. 57, 2019 – Fencing Technology Advances","target":"Material and method innovation -> improved durability -> reduced lifecycle labor"},
    {"label":"Skid Steer Auger Attachment","type":"TOOLS","evidence":"A","description":"Deploy skid steer-mounted hydraulic auger attachments with planetary drive heads for high-torque drilling in difficult soils. Skid steer augers provide more consistent power delivery, faster repositioning, and better operator protection than PTO-driven units.","cite":"ASABE EP496.3; Bobcat and Caterpillar Attachment Specifications","target":"Hydraulic auger -> consistent power -> faster, safer drilling"}
  ],
  economics: [
    {"label":"Fence Installation Cost Modeling","type":"STRATEGY","evidence":"A","description":"Develop comprehensive fence installation cost models including post hole drilling, post materials, wire or rail, labor, and equipment depreciation per linear foot. Accurate cost modeling supports budgeting for NRCS-funded conservation fence projects.","cite":"NRCS CPS 382 – Fence; ASABE D497.7 – Machinery Management Data","target":"Cost modeling -> accurate project budgets -> funded conservation fencing"},
    {"label":"Drill vs. Drive Economic Coaching","type":"COACHING","evidence":"B","description":"Coach managers on cost comparison between augered hole installation and driven post methods accounting for labor rates, equipment costs, soil conditions, and post type requirements. Method economics vary significantly by soil type and fence design.","cite":"Kansas State University MF-842 – Farm Machinery Costs","target":"Method comparison -> soil-appropriate selection -> minimized installation cost"},
    {"label":"NRCS Cost-Share Alignment Framework","type":"STRUCTURAL","evidence":"A","description":"Develop project planning frameworks that align fence installation practices with NRCS EQIP cost-share payment schedules and practice standards. Proper alignment ensures maximum cost-share reimbursement and compliance with practice certification requirements.","cite":"NRCS CPS 382 – Fence; NRCS EQIP Payment Schedule Documentation","target":"Cost-share alignment -> maximum reimbursement -> compliant installations"},
    {"label":"Fence as Asset Investment Culture","type":"CULTURE","evidence":"B","description":"Build management awareness that fencing represents a 20-30 year capital asset requiring proper installation to achieve full service life. Investment-grade thinking justifies quality materials, proper hole depth, and professional installation over shortcuts.","cite":"Journal of the ASFMRA, 2018 – Farm Infrastructure Valuation","target":"Investment thinking -> quality installation -> full 20-30 year service life"},
    {"label":"Fencing Project Estimator Tool","type":"TOOLS","evidence":"A","description":"Implement digital fencing project estimation tools calculating materials, labor, and equipment costs per rod, with adjustment factors for terrain difficulty, soil conditions, and fence type. Estimation tools support accurate bidding and budget requests.","cite":"ASABE D497.7; NRCS Fence Cost Estimation Worksheets","target":"Digital estimation -> accurate bidding -> reliable project budgets"}
  ]
});

// 12. PTO Generators
addTreatments('p2_agri_machinery_implements_ptogenerators.json', {
  monitoring: [
    {"label":"Output Voltage and Frequency Monitoring","type":"STRATEGY","evidence":"A","description":"Implement regular output voltage and frequency verification using calibrated multimeters under load conditions. Monitoring electrical output stability ensures connected equipment receives clean power within manufacturer tolerances, preventing damage to sensitive electronics.","cite":"ASABE S362.2 – PTO-Driven Generator Standards; NFPA 70 – National Electrical Code","target":"Output monitoring -> verified clean power -> protected connected equipment"},
    {"label":"PTO Speed and Generator Load Coaching","type":"COACHING","evidence":"B","description":"Train operators on maintaining correct PTO speed (540 or 1000 RPM) under varying electrical loads and understanding the relationship between engine RPM, PTO speed, and generator frequency. Speed discipline prevents both undervoltage damage and overvoltage hazards.","cite":"ASABE S362.2; University Extension – PTO Generator Safety","target":"Speed discipline -> stable frequency -> prevented voltage damage"},
    {"label":"Generator Maintenance Inspection Schedule","type":"STRUCTURAL","evidence":"A","description":"Establish inspection protocols covering brush wear, bearing condition, winding insulation resistance, output receptacle integrity, and PTO driveline shielding at 50-hour operating intervals. Scheduled electrical inspections prevent progressive failures and shock hazards.","cite":"ASABE EP496.3 – Machinery Management; NFPA 70 – Electrical Safety","target":"Scheduled inspection -> detected degradation -> prevented shock hazards"},
    {"label":"Electrical Safety Awareness Culture","type":"CULTURE","evidence":"A","description":"Establish non-negotiable safety protocols including proper grounding, load balancing, and weather protection for PTO generator operations. Electrical safety culture prevents the electrocution and fire risks inherent in field-deployed generating equipment.","cite":"OSHA 1910.269 – Electrical Power Generation; NIOSH Agricultural Electrical Safety","target":"Safety culture -> enforced grounding -> prevented electrocution and fire"},
    {"label":"Power Quality Analyzer","type":"TOOLS","evidence":"B","description":"Deploy portable power quality analyzers measuring voltage waveform distortion, frequency stability, and power factor under operating loads. Power quality data identifies generator issues invisible to basic voltage meters that can damage sensitive equipment.","cite":"IEEE 1159 – Power Quality Monitoring; ASABE S362.2","target":"Quality analysis -> detected waveform issues -> protected sensitive loads"}
  ],
  practices: [
    {"label":"Load Management Planning Strategy","type":"STRATEGY","evidence":"A","description":"Calculate total connected load requirements before generator deployment, ensuring generator capacity exceeds peak demand by minimum 20% safety margin. Load planning prevents overloaded generators that produce poor power quality and accelerated wear.","cite":"ASABE S362.2 – Generator Capacity Standards; NEC Article 702","target":"Load planning -> adequate capacity margin -> reliable power quality"},
    {"label":"Safe Connection Procedure Coaching","type":"COACHING","evidence":"B","description":"Coach operators on proper connection sequencing: establish ground first, verify PTO speed, confirm voltage before connecting loads, and disconnect loads before PTO disengagement. Correct sequencing prevents arc flash, voltage transients, and equipment damage.","cite":"NFPA 70 – National Electrical Code; OSHA Electrical Safety Standards","target":"Correct sequencing -> prevented arc flash -> safe load connections"},
    {"label":"Emergency Power Deployment SOP","type":"STRUCTURAL","evidence":"A","description":"Document emergency power deployment protocols specifying generator sizing for critical loads (livestock ventilation, milk cooling, grain drying), cable routing requirements, and transfer switching procedures. Emergency SOPs ensure reliable backup power when grid power fails.","cite":"NRCS CPS 372 – Combustion System; ASABE EP460 – Livestock Ventilation Emergency Power","target":"Emergency SOPs -> reliable backup power -> protected livestock and stored products"},
    {"label":"Power Reliability Preparedness","type":"CULTURE","evidence":"B","description":"Build organizational preparedness for power outages through regular generator testing, maintained fuel reserves, and practiced deployment procedures. Preparedness culture ensures that when emergencies occur, power restoration is rapid and reliable.","cite":"Journal of Extension, Vol. 51, 2013 – Farm Emergency Preparedness","target":"Preparedness culture -> rapid deployment -> minimized outage impacts"},
    {"label":"PTO Generator Load Bank Tester","type":"TOOLS","evidence":"B","description":"Maintain a portable load bank for annual generator capacity testing under controlled load conditions. Load bank testing verifies rated capacity is achievable before emergency situations demand peak performance from infrequently used generators.","cite":"ASABE S362.2; IEEE 446 – Emergency and Standby Power Systems","target":"Load bank testing -> verified capacity -> confirmed emergency readiness"}
  ],
  technology: [
    {"label":"Automatic Voltage Regulation Upgrade","type":"STRATEGY","evidence":"B","description":"Retrofit or specify PTO generators with automatic voltage regulators (AVR) that maintain stable output despite PTO speed fluctuations. AVR technology produces power quality suitable for electronic controls, computers, and variable-frequency drives.","cite":"IEEE 446 – Emergency Power Systems; ASABE S362.2","target":"AVR retrofit -> stable output -> safe power for electronics"},
    {"label":"Inverter Generator Technology Coaching","type":"COACHING","evidence":"C","description":"Introduce operators to inverter-type PTO generators that produce clean sine-wave power through electronic conversion. Understanding inverter technology enables informed decisions about powering sensitive precision agriculture electronics from tractor PTO sources.","cite":"Applied Engineering in Agriculture, Vol. 35(3), 2019 – Power Quality in Farm Applications","target":"Inverter awareness -> informed selection -> clean power for precision electronics"},
    {"label":"Integrated Power Management System","type":"STRUCTURAL","evidence":"B","description":"Deploy power management systems that automatically shed non-critical loads when generator capacity is approached, preventing overload-induced voltage collapse. Automated load management protects critical circuits without requiring constant operator monitoring.","cite":"IEEE 1547 – Distributed Resources Interconnection; NEC Article 702","target":"Load management system -> automatic protection -> maintained critical power"},
    {"label":"Technology-Enabled Power Resilience","type":"CULTURE","evidence":"C","description":"Build awareness that modern farm operations depend heavily on reliable electrical power and that generator technology investments directly protect revenue streams from livestock operations, grain storage, and dairy processing.","cite":"Journal of Extension, Vol. 56, 2018 – Farm Power Infrastructure","target":"Power awareness -> proactive investment -> protected revenue streams"},
    {"label":"Remote Generator Monitoring System","type":"TOOLS","evidence":"C","description":"Evaluate remote monitoring systems that provide real-time generator output, fuel level, and operating temperature data via cellular or WiFi connectivity. Remote monitoring enables off-site supervision of unmanned generator operations during extended outages.","cite":"Biosystems Engineering, Vol. 190, 2020 – Remote Farm Equipment Monitoring","target":"Remote monitoring -> off-site supervision -> assured continuous operation"}
  ],
  economics: [
    {"label":"Outage Cost-Avoidance Analysis","type":"STRATEGY","evidence":"A","description":"Quantify the economic losses from power outages including livestock mortality, spoiled milk, grain quality degradation, and production downtime to justify PTO generator investment. Outage cost analysis often shows generator ROI within a single avoided event.","cite":"ASABE EP460 – Emergency Ventilation Power; University Extension – Outage Cost Estimates","target":"Outage cost quantification -> justified investment -> ROI within first avoided event"},
    {"label":"Generator Sizing Economics Coaching","type":"COACHING","evidence":"B","description":"Coach managers on matching generator capacity to critical load requirements without oversizing, which wastes capital, or undersizing, which risks equipment damage. Right-sizing coaching balances investment cost against protection adequacy.","cite":"Kansas State University MF-842 – Farm Machinery Costs; ASABE S362.2","target":"Right-sizing guidance -> balanced investment -> adequate protection at minimum cost"},
    {"label":"Backup Power Investment Plan","type":"STRUCTURAL","evidence":"A","description":"Develop multi-year backup power plans incorporating generator capacity, transfer switch installation, critical circuit identification, and fuel storage requirements. Structured plans ensure comprehensive coverage without reactive over-spending after events.","cite":"NRCS CPS 372; ASABE EP460; NEC Article 702","target":"Structured planning -> comprehensive coverage -> prevented reactive over-spending"},
    {"label":"Power Resilience Valuation Culture","type":"CULTURE","evidence":"B","description":"Build management appreciation that backup power capability has quantifiable value in protecting biological assets (livestock), perishable products (milk, grain), and time-critical processes (ventilation, irrigation). Value awareness supports maintenance investment.","cite":"Journal of the ASFMRA, 2019 – Farm Risk Management Infrastructure","target":"Value appreciation -> maintained readiness -> protected high-value assets"},
    {"label":"Generator Operating Cost Calculator","type":"TOOLS","evidence":"A","description":"Implement operating cost calculators tracking fuel consumption, maintenance costs, and depreciation per hour of generator operation. Cost data enables accurate comparison between PTO generators, standby diesel units, and utility backup service options.","cite":"ASABE D497.7 – Agricultural Machinery Management Data","target":"Cost tracking -> technology comparison -> optimal backup power selection"}
  ]
});

// 13. Skid Steer Loaders
addTreatments('p2_agri_machinery_materialhandl_skidsteerloaders.json', {
  monitoring: [
    {"label":"Hydraulic System Performance Monitoring","type":"STRATEGY","evidence":"A","description":"Implement regular hydraulic pressure and flow testing at defined hour intervals to detect pump wear, valve degradation, and system contamination. Hydraulic health monitoring prevents the progressive power loss that reduces skid steer productivity before operators notice.","cite":"ASABE EP496.3 – Machinery Management; SAE J1116 – Skid Steer Loader Standards","target":"Hydraulic testing -> early pump wear detection -> maintained lifting capacity"},
    {"label":"Daily Walk-Around Inspection Coaching","type":"COACHING","evidence":"B","description":"Train operators on comprehensive daily walk-around inspections covering tire/track condition, hydraulic hose routing, attachment pin security, and cab safety features. Consistent daily inspections catch issues when they are inexpensive to fix.","cite":"OSHA 1926.602 – Material Handling Equipment; SAE J1388 – Skid Steer Safety","target":"Daily inspection habit -> early issue detection -> inexpensive corrections"},
    {"label":"Service Interval Tracking System","type":"STRUCTURAL","evidence":"A","description":"Establish hour-based service tracking for engine oil, hydraulic fluid, filters, drive components, and undercarriage wear items using digital maintenance management systems. Structured interval tracking prevents both over-maintenance waste and under-maintenance failures.","cite":"ASABE EP496.3; Caterpillar/Bobcat Maintenance Schedules","target":"Interval tracking -> optimized maintenance timing -> minimized total lifecycle cost"},
    {"label":"Operator Care Ownership Culture","type":"CULTURE","evidence":"B","description":"Foster operator ownership of machine condition by assigning specific units to individuals and tracking maintenance compliance and damage incidents per operator. Personal accountability motivates careful operation and diligent daily inspection completion.","cite":"Journal of Extension, Vol. 53, 2015 – Equipment Operator Accountability","target":"Personal ownership -> careful operation -> reduced damage and downtime"},
    {"label":"Telematics Fleet Monitoring Platform","type":"TOOLS","evidence":"A","description":"Deploy OEM telematics systems (Cat Product Link, Bobcat Machine IQ) providing real-time engine parameters, utilization hours, fault codes, and geolocation. Fleet telematics enables proactive maintenance scheduling and theft prevention.","cite":"SAE J1939 – Vehicle Network Communications; OEM Telematics Documentation","target":"Telematics monitoring -> proactive maintenance -> minimized unplanned downtime"}
  ],
  practices: [
    {"label":"Attachment Matching Strategy","type":"STRATEGY","evidence":"A","description":"Develop decision matrices matching skid steer rated operating capacity and hydraulic flow to attachment requirements for buckets, forks, augers, grapples, and brooms. Proper matching prevents overloading that causes tipping incidents and accelerated machine wear.","cite":"SAE J1116 – Skid Steer Standards; OSHA Tip-Over Prevention Guidelines","target":"Attachment matching -> prevented overloading -> safe stable operation"},
    {"label":"Load Chart and Stability Coaching","type":"COACHING","evidence":"B","description":"Train operators on reading and applying rated operating capacity charts accounting for attachment weight, load center distance, and terrain slope. Load chart mastery prevents the tipping incidents that are the leading cause of skid steer operator fatalities.","cite":"OSHA 1926.602; SAE J1388 – Skid Steer Operator Safety","target":"Load chart mastery -> prevented tipping -> protected operator lives"},
    {"label":"Site-Specific Operating Procedures","type":"STRUCTURAL","evidence":"A","description":"Document site-specific operating procedures for common tasks including feed bunk cleaning, manure loading, snow removal, and material staging. Task-specific SOPs include travel routes, speed limits, and attachment changeover requirements for each work area.","cite":"NRCS CPS 313 – Waste Storage Facility; OSHA Agricultural Equipment Standards","target":"Task-specific SOPs -> consistent safe operation -> prevented site-specific hazards"},
    {"label":"Respect the Machine Mindset","type":"CULTURE","evidence":"A","description":"Build a culture that respects skid steer power-to-weight limitations and tipping risk through regular safety briefings and incident review. Overconfidence with skid steers is a major injury driver; cultural respect counters dangerous complacency.","cite":"NIOSH 2018 – Preventing Skid Steer Loader Deaths; OSHA Fatal Facts","target":"Respectful operation -> countered complacency -> prevented tip-over fatalities"},
    {"label":"Quick-Attach Coupling System","type":"TOOLS","evidence":"A","description":"Equip skid steers with universal quick-attach systems compatible with all operation attachments, enabling single-operator attachment changes in under 2 minutes. Efficient attachment changes maximize machine versatility and minimize changeover downtime.","cite":"SAE J2513 – Skid Steer Quick Coupler Standards","target":"Quick-attach system -> 2-minute changeovers -> maximized daily versatility"}
  ],
  technology: [
    {"label":"Track Machine Adoption Strategy","type":"STRATEGY","evidence":"B","description":"Evaluate compact track loader alternatives to wheeled skid steers for operations with significant soft-ground or slope work. Track machines distribute ground pressure over larger areas, reducing soil compaction and improving traction on loose or wet surfaces.","cite":"SAE J1116; Transactions of the ASABE, Vol. 62(1), 2019 – Compact Loader Comparison","target":"Track evaluation -> reduced soil compaction -> improved soft-ground performance"},
    {"label":"Advanced Control System Training","type":"COACHING","evidence":"B","description":"Train operators on advanced hydraulic control features including proportional auxiliary hydraulics, ride control, and selectable joystick patterns. Mastery of advanced controls enables smoother operation, reduced material spillage, and decreased operator fatigue.","cite":"Applied Engineering in Agriculture, Vol. 35(5), 2019 – Hydraulic Control Systems","target":"Control mastery -> smoother operation -> reduced spillage and operator fatigue"},
    {"label":"Precision Grading Attachment Integration","type":"STRUCTURAL","evidence":"B","description":"Integrate laser or GPS-guided grading attachments with skid steer hydraulic systems for precision earthwork on pad construction, feedlot grading, and conservation practices. Precision attachments expand skid steer utility into traditionally dozer-only work.","cite":"ASABE S561 – GPS Guidance; Trimble Skid Steer Grade Control Documentation","target":"Precision integration -> expanded capability -> reduced dozer dependency"},
    {"label":"Multi-Function Equipment Appreciation","type":"CULTURE","evidence":"B","description":"Build team appreciation for skid steers as the most versatile machines in the equipment fleet, deserving the same maintenance investment as primary tractors. Versatility appreciation counters the tendency to defer maintenance on 'utility' equipment.","cite":"Equipment World Magazine, 2019 – Skid Steer ROI Optimization","target":"Versatility appreciation -> proper maintenance investment -> reliable availability"},
    {"label":"Machine Weighing and Load Scale","type":"TOOLS","evidence":"B","description":"Install bucket or fork payload scales that provide real-time load weight display in the operator cab. Onboard weighing enables precise material loading for feed mixing, fertilizer application, and truck loading without separate scale infrastructure.","cite":"SAE J1116; Trimble Payload Weighing Documentation","target":"Onboard weighing -> precise loading -> eliminated scale-house trips"}
  ],
  economics: [
    {"label":"Skid Steer Fleet Utilization Analysis","type":"STRATEGY","evidence":"A","description":"Track utilization hours and task allocation across the skid steer fleet to identify over-investment in idle machines or under-investment causing operational bottlenecks. Utilization analysis optimizes fleet size for actual operational demand patterns.","cite":"ASABE D497.7 – Machinery Management; SAE J1116","target":"Utilization analysis -> right-sized fleet -> optimized capital allocation"},
    {"label":"Lease vs. Buy Decision Coaching","type":"COACHING","evidence":"B","description":"Coach managers on lease versus purchase analysis for skid steers incorporating annual utilization hours, tax implications, maintenance capability, and technology refresh cycles. Lease-buy optimization can reduce effective annual costs by 10-15%.","cite":"Kansas State University MF-842 – Farm Machinery Costs","target":"Lease-buy analysis -> optimized acquisition -> 10-15% annual cost reduction"},
    {"label":"Attachment Investment Priority Plan","type":"STRUCTURAL","evidence":"A","description":"Develop prioritized attachment investment plans ranking attachment ROI by frequency of use, labor replacement value, and alternative cost (rental or manual labor). Structured planning ensures attachment investments generate maximum productivity return.","cite":"ASABE D497.7; North Dakota State University EC1260","target":"Prioritized investment -> maximum productivity per attachment dollar -> net labor savings"},
    {"label":"Machine Cost Awareness Culture","type":"CULTURE","evidence":"B","description":"Share hourly operating costs of skid steer loaders including depreciation, fuel, maintenance, and tire/track replacement across all users. Cost awareness discourages unnecessary idling, abusive operation, and failure to report maintenance issues promptly.","cite":"Journal of the ASFMRA, 2019 – Equipment Cost Communication","target":"Cost awareness -> reduced abuse -> extended machine life and lower costs"},
    {"label":"Skid Steer Cost Per Hour Dashboard","type":"TOOLS","evidence":"A","description":"Implement hourly cost tracking dashboards integrating fuel consumption, maintenance records, and depreciation for each skid steer unit. Per-unit cost visibility identifies machines requiring replacement and validates fleet management decisions.","cite":"ASABE D497.7 – Agricultural Machinery Management Data","target":"Unit cost dashboards -> replacement identification -> validated fleet decisions"}
  ]
});

// 14. Telehandlers
addTreatments('p2_agri_machinery_materialhandl_telehandlers.json', {
  monitoring: [
    {"label":"Boom and Hydraulic Cylinder Inspection","type":"STRATEGY","evidence":"A","description":"Implement scheduled boom section wear inspection and hydraulic cylinder seal integrity checks at manufacturer-specified intervals. Monitoring boom component condition prevents progressive failures that create sudden load-drop hazards during elevated operations.","cite":"ASABE EP496.3 – Machinery Management; JCB/CAT Telehandler Maintenance Guides","target":"Boom inspection -> detected seal wear -> prevented sudden load-drop hazards"},
    {"label":"Load Moment Indicator Training","type":"COACHING","evidence":"A","description":"Train all operators on load moment indicator (LMI) system interpretation, including understanding load chart derating for boom angle, extension, and attachment weight. LMI proficiency prevents the overloading that causes the majority of telehandler tip-over incidents.","cite":"ANSI/ITSDF B56.6 – Rough Terrain Forklift Safety; OSHA 1926.602","target":"LMI proficiency -> prevented overloading -> eliminated tip-over incidents"},
    {"label":"Stability System Verification Checklist","type":"STRUCTURAL","evidence":"A","description":"Establish pre-shift stability system verification covering tire pressure, frame level indicators, stabilizer leg function, and load moment system calibration. Stability checks ensure safety systems are functional before elevated material handling begins.","cite":"ANSI B56.6; OSHA Powered Industrial Truck Standards","target":"Stability verification -> functional safety systems -> safe elevated operations"},
    {"label":"Elevated Work Safety Culture","type":"CULTURE","evidence":"A","description":"Build an organizational culture where telehandler stability limits are never exceeded regardless of time pressure. Non-negotiable stability culture prevents the 'just one more load' mentality that causes the fatal tip-over incidents documented by OSHA.","cite":"OSHA Fatal Facts – Telehandler Tip-Over Incidents; NIOSH 2018","target":"Non-negotiable limits -> prevented pressure-driven overreach -> protected lives"},
    {"label":"Telematics Stability Monitoring","type":"TOOLS","evidence":"B","description":"Deploy telematics systems that log load moment indicator activations, boom overextension warnings, and stability alerts. Monitoring data identifies operators who routinely approach stability limits, enabling targeted retraining before incidents occur.","cite":"SAE J1939; JCB LiveLink/CAT Product Link Documentation","target":"Event logging -> identified risk patterns -> targeted retraining"}
  ],
  practices: [
    {"label":"Attachment-Specific Load Chart Protocol","type":"STRATEGY","evidence":"A","description":"Develop and post attachment-specific load charts for every telehandler-attachment combination used on the operation (forks, buckets, bale clamps, man baskets). Each attachment changes the machine's rated capacity and stability envelope.","cite":"ANSI/ITSDF B56.6 – Rough Terrain Forklifts; OSHA 1926.602","target":"Attachment-specific charts -> accurate capacity knowledge -> safe loading per attachment"},
    {"label":"Rough Terrain Operation Coaching","type":"COACHING","evidence":"B","description":"Coach operators on terrain assessment and approach techniques for telehandler operations on slopes, soft ground, and uneven surfaces. Understanding how terrain affects stability boundaries prevents tip-over on the varied surfaces common in agricultural settings.","cite":"OSHA Rough Terrain Forklift Safety Guide; ANSI B56.6","target":"Terrain assessment skills -> slope-adjusted operation -> prevented terrain-related tip-over"},
    {"label":"Material Staging Area SOP","type":"STRUCTURAL","evidence":"A","description":"Document material staging area standards specifying ground preparation requirements, traffic flow patterns, stack height limits, and clear zones around telehandler operating areas. Organized staging prevents struck-by incidents and material toppling.","cite":"OSHA 1926.250 – Material Storage; NRCS CPS 313 – Waste Storage (adapted)","target":"Staging standards -> organized areas -> prevented struck-by incidents"},
    {"label":"Respect for Reach Equipment","type":"CULTURE","evidence":"B","description":"Build cultural recognition that telehandlers operating at full boom extension are the most stability-sensitive machines in the fleet. Elevated awareness counters the false confidence that comes from everyday loader-mode operation at ground level.","cite":"NIOSH 2018 – Preventing Tip-Over Deaths; OSHA Emphasis Program Data","target":"Heightened awareness -> respected limitations -> prevented complacency incidents"},
    {"label":"Digital Load Chart Reference System","type":"TOOLS","evidence":"A","description":"Install digital in-cab load chart displays that show real-time rated capacity based on current boom angle, extension, and attachment selection. Dynamic load charts eliminate the need to reference paper charts and provide continuous capacity awareness.","cite":"ANSI B56.6; JCB SmartPilot Documentation","target":"Dynamic load display -> continuous capacity awareness -> safe real-time decisions"}
  ],
  technology: [
    {"label":"Rotating Telehandler Evaluation","type":"STRATEGY","evidence":"B","description":"Evaluate rotating (360-degree) telehandlers for operations requiring combined reach and rotation capabilities that currently need both a telehandler and a crane. Rotating machines consolidate material handling tasks and reduce equipment fleet requirements.","cite":"Transactions of the ASABE, Vol. 61(4), 2018 – Material Handling Equipment Selection","target":"Rotating evaluation -> task consolidation -> reduced fleet requirements"},
    {"label":"Advanced Stability System Training","type":"COACHING","evidence":"B","description":"Provide training on advanced telehandler stability features including active stabilization, automatic load-moment compensation, and terrain-responsive boom speed limiting. Technology understanding ensures operators trust and utilize stability automation.","cite":"Applied Engineering in Agriculture, Vol. 36(2), 2020 – Telehandler Safety Technology","target":"Technology understanding -> utilized automation -> enhanced stability protection"},
    {"label":"Fleet Telematics Integration","type":"STRUCTURAL","evidence":"B","description":"Integrate telehandler telematics with farm management systems for centralized utilization tracking, maintenance scheduling, and safety event monitoring. Unified fleet data enables comparative analysis across material handling equipment types.","cite":"SAE J1939; ASABE/ISO 11783 – Agricultural Data Networks","target":"Integrated telematics -> centralized management -> optimized fleet coordination"},
    {"label":"Technology-Enabled Safety Priority","type":"CULTURE","evidence":"B","description":"Embrace telehandler safety technology as an investment in human life rather than a productivity constraint. Cultural framing of stability systems as life-saving equipment prevents operator attempts to override or disable safety features.","cite":"OSHA Safety and Health Topics – Telehandlers; NIOSH Farm Safety Program","target":"Safety-first framing -> respected safety systems -> protected operators"},
    {"label":"Camera and Proximity Alert System","type":"TOOLS","evidence":"B","description":"Install multi-camera systems with proximity warning alerts for blind spots around telehandlers during both travel and material handling operations. Camera systems reduce struck-by incidents in congested farmstead environments.","cite":"SAE J2802 – Machine Visibility; OSHA Struck-By Prevention","target":"Camera systems -> blind spot elimination -> prevented struck-by incidents"}
  ],
  economics: [
    {"label":"Telehandler vs. Wheel Loader ROI","type":"STRATEGY","evidence":"A","description":"Conduct comparative ROI analysis between telehandlers and wheel loaders for the operation's specific material handling tasks, accounting for reach capability, attachment versatility, and utilization hours. Task-specific analysis prevents mismatched equipment investment.","cite":"ASABE D497.7; Equipment World – Telehandler vs. Loader Economics","target":"Comparative ROI -> task-matched selection -> maximized handling productivity per dollar"},
    {"label":"Total Cost of Ownership Coaching","type":"COACHING","evidence":"B","description":"Coach managers on telehandler total cost of ownership including higher tire costs, boom maintenance, and specialized technician requirements compared to simpler wheel loaders. TCO awareness prevents sticker-price decisions that ignore lifecycle costs.","cite":"Kansas State University MF-842 – Farm Machinery Costs","target":"TCO awareness -> lifecycle-informed decisions -> minimized total ownership cost"},
    {"label":"Rental vs. Purchase Analysis Framework","type":"STRUCTURAL","evidence":"A","description":"Develop rental-purchase decision frameworks for telehandlers based on annual utilization hours, peak-demand patterns, and maintenance infrastructure. Many agricultural operations benefit from peak-season rental rather than year-round ownership of specialized reach equipment.","cite":"North Dakota State University EC1260; ASABE D497.7","target":"Rental-purchase analysis -> demand-matched acquisition -> reduced idle capital"},
    {"label":"Equipment Utilization Accountability","type":"CULTURE","evidence":"B","description":"Track and share telehandler utilization rates across the operation to build awareness of per-hour ownership costs and motivate efficient scheduling. Visible utilization data encourages task batching and multi-use planning that improves asset productivity.","cite":"Journal of the ASFMRA, 2019 – Equipment Utilization Management","target":"Utilization visibility -> efficient scheduling -> improved asset productivity"},
    {"label":"Material Handling Cost Tracker","type":"TOOLS","evidence":"A","description":"Implement per-task cost tracking for telehandler operations including fuel, operator time, tire wear, and maintenance allocation. Task-level costing reveals which material handling activities justify telehandler use versus simpler, lower-cost alternatives.","cite":"ASABE D497.7 – Agricultural Machinery Management Data","target":"Task-level costing -> justified equipment assignment -> optimized handling costs"}
  ]
});

// 15. Conveyor Systems
addTreatments('p2_agri_machinery_materialhandl_conveyorsystems.json', {
  monitoring: [
    {"label":"Belt Tracking and Tension Monitoring","type":"STRATEGY","evidence":"A","description":"Implement scheduled belt tracking checks and tension measurements using deflection gauges at manufacturer-specified intervals. Monitoring belt alignment and tension prevents the edge damage, material spillage, and drive roller wear caused by misalignment.","cite":"CEMA – Conveyor Equipment Manufacturers Association Belt Book; ASABE EP496.3","target":"Tracking checks -> prevented misalignment -> eliminated edge damage and spillage"},
    {"label":"Roller and Idler Inspection Coaching","type":"COACHING","evidence":"B","description":"Train maintenance personnel to identify bearing noise, roller seizure, and idler misalignment through visual and auditory inspection techniques. Early detection of roller failures prevents belt damage and unexpected conveyor shutdowns during critical material flow.","cite":"CEMA Belt Book 7th Edition – Conveyor Maintenance","target":"Detection skills -> early roller replacement -> prevented belt damage"},
    {"label":"Conveyor Safety Guard Audit System","type":"STRUCTURAL","evidence":"A","description":"Establish quarterly audits of all conveyor guards, emergency stops, pull-cord switches, and pinch-point protection devices. Systematic guard auditing ensures compliance with safety standards and prevents the severe entanglement injuries common at conveyor nip points.","cite":"OSHA 1910.219 – Mechanical Power Transmission; ANSI/CEMA 102 – Conveyor Safety","target":"Guard auditing -> maintained protection -> prevented entanglement injuries"},
    {"label":"Never Reach Into Running Equipment Culture","type":"CULTURE","evidence":"A","description":"Establish absolute prohibition on reaching into, across, or under running conveyor systems, with lockout/tagout required for any belt service. Entanglement in agricultural conveyors causes amputations and fatalities every year; cultural enforcement prevents them.","cite":"OSHA 1910.147 – Lockout/Tagout; NIOSH – Conveyor Entanglement Prevention","target":"Absolute prohibition -> enforced lockout -> prevented amputations and fatalities"},
    {"label":"Belt Speed and Load Sensor System","type":"TOOLS","evidence":"B","description":"Deploy belt speed sensors and load cells that continuously monitor conveyor throughput and detect belt slippage, overloading, or material buildup conditions. Automated monitoring enables real-time capacity management and prevents drive component overload.","cite":"CEMA Belt Book; Applied Engineering in Agriculture, Vol. 34(1), 2018","target":"Speed/load monitoring -> detected overload -> prevented drive failure"}
  ],
  practices: [
    {"label":"Material Flow Rate Optimization","type":"STRATEGY","evidence":"A","description":"Match conveyor belt speed and feeder rate to downstream processing capacity to maintain steady material flow without surge loading or starvation. Flow rate optimization prevents equipment damage at transfer points and maintains consistent processing quality.","cite":"CEMA Belt Book – Flow Rate Design; ASABE EP496.3","target":"Flow optimization -> steady material delivery -> consistent processing quality"},
    {"label":"Transfer Point Management Coaching","type":"COACHING","evidence":"B","description":"Coach operators on managing material transfer points including chute angle adjustment, impact bed maintenance, and skirting seal inspection. Properly managed transfer points reduce dust, spillage, and material degradation at belt-to-belt transitions.","cite":"CEMA Transfer Point Design Guide; Martin Engineering Foundations","target":"Transfer management -> reduced spillage -> minimized material degradation"},
    {"label":"Conveyor Lockout/Tagout SOP","type":"STRUCTURAL","evidence":"A","description":"Document comprehensive lockout/tagout procedures specific to each conveyor system including energy isolation points, verification procedures, and group lockout protocols for multi-person maintenance. LOTO compliance prevents the uncontrolled starts that cause fatal entanglement.","cite":"OSHA 1910.147 – Control of Hazardous Energy; ANSI Z244.1","target":"LOTO procedures -> isolation verification -> prevented uncontrolled starts"},
    {"label":"Clean Worksite Standards","type":"CULTURE","evidence":"B","description":"Maintain standards for clean conveyor areas including regular spillage cleanup, walkway clearance, and accumulation prevention at transfer points. Clean conveyor environments reduce slip/trip hazards, prevent material contamination, and indicate maintenance diligence.","cite":"OSHA 1910.22 – Walking-Working Surfaces; CEMA Maintenance Standards","target":"Clean standards -> reduced hazards -> indicated maintenance quality"},
    {"label":"Conveyor Belt Splicing Kit","type":"TOOLS","evidence":"A","description":"Maintain on-site belt splicing equipment and trained personnel for emergency belt repair capability. Field splicing capability restores conveyor operation in hours rather than the days required to order and install replacement belts.","cite":"CEMA Belt Book – Splicing Methods; Flexco Splicing Equipment Documentation","target":"On-site splicing -> hours vs. days recovery -> minimized flow interruption"}
  ],
  technology: [
    {"label":"Automated Material Routing Strategy","type":"STRATEGY","evidence":"B","description":"Implement programmable diverter gates and automated routing systems that direct material to multiple destinations based on product type, bin level, or processing requirements. Automated routing reduces manual intervention and enables continuous unattended operation.","cite":"Computers and Electronics in Agriculture, Vol. 160, 2019 – Automated Material Handling","target":"Automated routing -> reduced manual intervention -> continuous operation"},
    {"label":"Conveyor Automation System Training","type":"COACHING","evidence":"B","description":"Train operators on programmable logic controller (PLC) interfaces, sequence start/stop procedures, and alarm response protocols for automated conveyor systems. Automation literacy enables effective system operation and appropriate troubleshooting.","cite":"Applied Engineering in Agriculture, Vol. 35(4), 2019 – PLC Training for Agriculture","target":"Automation literacy -> effective operation -> appropriate troubleshooting"},
    {"label":"Integrated Conveyor Monitoring Architecture","type":"STRUCTURAL","evidence":"B","description":"Deploy centralized monitoring systems connecting all conveyor drives, sensors, and safety devices to a single operator interface. Integrated monitoring provides complete material handling visibility and enables coordinated system management from one location.","cite":"ASABE/ISO 11783; CEMA Monitoring Systems Guide","target":"Centralized monitoring -> complete visibility -> coordinated management"},
    {"label":"Continuous Improvement in Material Flow","type":"CULTURE","evidence":"C","description":"Encourage maintenance teams to identify and propose improvements to conveyor system efficiency including speed optimization, transfer point upgrades, and dust control enhancements. Continuous improvement culture drives incremental gains in system reliability.","cite":"Journal of Extension, Vol. 54, 2016 – Maintenance Culture in Agriculture","target":"Improvement proposals -> incremental gains -> sustained reliability improvement"},
    {"label":"Conveyor Health Vibration Analyzer","type":"TOOLS","evidence":"B","description":"Deploy portable vibration analyzers for predictive maintenance of conveyor bearings, gearboxes, and drive motors. Vibration signature analysis identifies developing failures 2-4 weeks before they cause breakdowns, enabling planned replacement.","cite":"CEMA Maintenance Guide; ISO 10816 – Mechanical Vibration Evaluation","target":"Vibration analysis -> 2-4 week failure prediction -> planned replacement"}
  ],
  economics: [
    {"label":"Conveyor System Lifecycle Cost Model","type":"STRATEGY","evidence":"A","description":"Model total lifecycle costs for conveyor systems including installation, energy consumption, belt replacement, bearing maintenance, and eventual decommissioning. Lifecycle models justify investment in quality components that reduce total ownership cost despite higher initial prices.","cite":"CEMA Belt Book – Economic Analysis; ASABE D497.7","target":"Lifecycle modeling -> quality component justification -> lowest total ownership cost"},
    {"label":"Energy Cost Optimization Coaching","type":"COACHING","evidence":"B","description":"Coach facility managers on conveyor energy cost drivers including belt tension, speed selection, and idler resistance. Simple adjustments like proper belt tension and correct speed selection can reduce conveyor energy costs by 10-20%.","cite":"CEMA Energy Guide; DOE – Motor Systems Efficiency","target":"Energy optimization -> 10-20% cost reduction -> improved operating margins"},
    {"label":"Preventive vs. Reactive Maintenance ROI","type":"STRUCTURAL","evidence":"A","description":"Document the cost comparison between preventive maintenance programs and reactive breakdown repair for conveyor systems, including production downtime costs. PM programs typically achieve 3:1 cost savings versus run-to-failure approaches.","cite":"CEMA Maintenance Standards; Reliability Engineering & System Safety Journal, 2018","target":"PM documentation -> 3:1 cost savings -> justified maintenance investment"},
    {"label":"Total Material Handling Cost Awareness","type":"CULTURE","evidence":"B","description":"Share per-ton material handling costs across operations to build awareness of conveyor system economics and motivate efficient utilization, proper maintenance, and waste reduction. Cost transparency drives collective responsibility for system care.","cite":"Journal of the ASFMRA, 2019 – Facility Cost Management","target":"Cost awareness -> collective responsibility -> efficient utilization and care"},
    {"label":"Conveyor Operating Cost Dashboard","type":"TOOLS","evidence":"A","description":"Implement energy monitoring and cost tracking dashboards for conveyor systems displaying kWh consumption, throughput tonnage, and per-ton handling costs. Real-time cost visibility enables immediate response to efficiency degradation.","cite":"CEMA Energy Guide; ASABE D497.7 – Machinery Management Data","target":"Cost dashboards -> efficiency monitoring -> immediate response to degradation"}
  ]
});

// 16. Wheel Loaders
addTreatments('p2_agri_machinery_materialhandl_wheelloaders.json', {
  monitoring: [
    {"label":"Drivetrain and Transmission Monitoring","type":"STRATEGY","evidence":"A","description":"Implement scheduled transmission fluid analysis and torque converter performance testing to detect internal wear before it causes shifting problems or power loss. Transmission monitoring prevents the catastrophic failures that generate $15,000+ repair bills.","cite":"ASABE EP496.3 – Machinery Management; SAE J1013 – Loader Standards","target":"Transmission monitoring -> early wear detection -> prevented catastrophic failures"},
    {"label":"Tire Condition and Pressure Coaching","type":"COACHING","evidence":"B","description":"Train operators to inspect tire sidewall condition, tread depth, and maintain inflation pressures per manufacturer specifications for the specific tire type (bias, radial, or foam-filled). Proper tire management extends tire life 20-30% and maintains machine stability.","cite":"Tire and Rim Association Yearbook; OSHA Powered Industrial Truck Standards","target":"Tire inspection skills -> 20-30% life extension -> maintained stability"},
    {"label":"Loader Bucket Wear Assessment System","type":"STRUCTURAL","evidence":"A","description":"Establish measurement protocols for bucket cutting edge thickness, side cutter wear, and tooth condition at defined hour intervals. Documented bucket wear tracking ensures replacement scheduling aligns with material handling demands and parts availability.","cite":"ASABE EP496.3; Caterpillar Ground Engaging Tool (GET) Wear Guide","target":"Bucket wear tracking -> scheduled replacement -> maintained loading efficiency"},
    {"label":"Fluid Analysis Program Culture","type":"CULTURE","evidence":"B","description":"Normalize regular oil analysis sampling as a standard maintenance practice by sharing results and savings achieved from early problem detection. When operators see that a $25 oil sample prevented a $10,000 repair, fluid analysis compliance improves dramatically.","cite":"Practicing Oil Analysis Magazine; Caterpillar S.O.S. Fluid Analysis","target":"Oil analysis norm -> early detection savings -> reinforced program compliance"},
    {"label":"Engine and Hydraulic Diagnostic Scanner","type":"TOOLS","evidence":"A","description":"Deploy OEM diagnostic scanners (CAT ET, Deere Service Advisor) for reading engine ECU data, hydraulic system parameters, and transmission fault codes. Electronic diagnostics provide definitive troubleshooting that reduces misdiagnosis and unnecessary parts replacement.","cite":"SAE J1939 – Vehicle Diagnostics; OEM Diagnostic Tool Documentation","target":"Electronic diagnostics -> accurate troubleshooting -> eliminated misdiagnosis"}
  ],
  practices: [
    {"label":"Bucket Selection and Fill Factor Strategy","type":"STRATEGY","evidence":"A","description":"Match bucket size and type (general purpose, high-capacity, light material) to the specific material being handled and calculate fill factors for accurate load-out. Correct bucket selection maximizes payload per cycle while preventing material spillage and structural overload.","cite":"SAE J742 – Loader Bucket Rating; ASABE D497.7","target":"Correct bucket selection -> maximized payload -> prevented overload and spillage"},
    {"label":"Efficient Loading Cycle Coaching","type":"COACHING","evidence":"B","description":"Coach operators on V-pattern and modified-V loading techniques that minimize travel distance, reduce tire wear, and increase tons-per-hour throughput. Efficient cycle techniques improve productivity 15-20% over unstructured loading approaches.","cite":"Caterpillar Performance Handbook; ASABE D497.7","target":"Efficient techniques -> 15-20% productivity gain -> reduced tire and fuel costs"},
    {"label":"Stockpile Management SOP","type":"STRUCTURAL","evidence":"A","description":"Document stockpile management procedures specifying material segregation, pile height limits, approach grades, and contamination prevention measures. Organized stockpile management reduces material waste, prevents equipment incidents, and maintains product quality.","cite":"NRCS CPS 313 – Waste Storage; OSHA Stockpile Safety Guidelines","target":"Stockpile SOPs -> reduced waste -> prevented contamination and incidents"},
    {"label":"Smooth Operator Recognition","type":"CULTURE","evidence":"B","description":"Recognize operators who achieve high productivity with smooth, controlled machine operation rather than aggressive high-speed techniques. Smooth operation reduces component wear, fuel consumption, and material spillage while maintaining equivalent throughput.","cite":"Caterpillar Operator Efficiency Guide; Journal of Extension, Vol. 52, 2014","target":"Smooth operation recognition -> reduced wear and fuel -> maintained throughput"},
    {"label":"Onboard Payload Scale System","type":"TOOLS","evidence":"A","description":"Install payload weighing systems that provide per-bucket load weights displayed in the cab. Onboard scales enable precise truck loading to legal weight limits, accurate material tracking, and elimination of trips to stationary scales.","cite":"SAE J742; Trimble/Loadrite Payload Management Documentation","target":"Payload scales -> precise truck loading -> eliminated overweight penalties"}
  ],
  technology: [
    {"label":"Electric Wheel Loader Evaluation","type":"STRATEGY","evidence":"C","description":"Evaluate battery-electric wheel loaders for indoor material handling applications where zero emissions, reduced noise, and lower operating costs offset higher purchase prices. Electric loaders are particularly suited to livestock facility operations.","cite":"Transactions of the ASABE, Vol. 63(2), 2020 – Electric Equipment in Agriculture","target":"Electric evaluation -> zero indoor emissions -> lower operating costs"},
    {"label":"Automated Loading System Awareness","type":"COACHING","evidence":"C","description":"Introduce operators to emerging autonomous and semi-autonomous wheel loader technologies including automated loading cycles, obstacle detection, and remote operation capabilities. Technology awareness prepares operations for future labor efficiency solutions.","cite":"Automation in Construction, Vol. 110, 2020 – Autonomous Loading Systems","target":"Technology awareness -> preparedness -> future labor efficiency"},
    {"label":"Fleet Data Integration Platform","type":"STRUCTURAL","evidence":"B","description":"Connect wheel loader telematics data with farm management systems for integrated fuel tracking, utilization analysis, and maintenance coordination across the entire material handling fleet. Unified data enables cross-machine performance comparison and optimization.","cite":"SAE J1939; ASABE/ISO 11783 – Agricultural Data Networks","target":"Data integration -> cross-machine comparison -> fleet-wide optimization"},
    {"label":"Operator Technology Engagement","type":"CULTURE","evidence":"B","description":"Engage operators in technology evaluation and feedback processes for wheel loader upgrades, building ownership of technology adoption decisions. Operator input improves technology selection and accelerates adoption of beneficial new features.","cite":"Precision Agriculture, Vol. 20, 2019 – Operator Engagement in Technology Adoption","target":"Operator engagement -> improved selection -> accelerated adoption"},
    {"label":"Tire Pressure Monitoring System","type":"TOOLS","evidence":"B","description":"Install tire pressure monitoring systems (TPMS) with in-cab alerts for real-time tire condition tracking. TPMS prevents the sudden blowouts and rim damage that occur when slow leaks go undetected on heavy-loaded wheel loader tires.","cite":"SAE J2657 – TPMS Standards; Tire Industry Association Guidelines","target":"TPMS monitoring -> prevented blowouts -> extended tire and rim life"}
  ],
  economics: [
    {"label":"Loader Fleet Right-Sizing Analysis","type":"STRATEGY","evidence":"A","description":"Analyze wheel loader fleet size against peak and average material handling demand using utilization data and seasonal work patterns. Right-sizing eliminates both idle overcapacity and the costly bottlenecks from undermanned peak-season operations.","cite":"ASABE D497.7 – Machinery Management; Caterpillar Fleet Management Guide","target":"Fleet right-sizing -> eliminated idle capacity -> resolved peak bottlenecks"},
    {"label":"Fuel Efficiency Operator Coaching","type":"COACHING","evidence":"B","description":"Coach operators on fuel-efficient loading techniques including appropriate engine RPM for load weight, minimal idle time, and short-haul speed management. Fuel represents 25-35% of wheel loader operating costs, making efficiency training highly impactful.","cite":"Caterpillar Fuel Efficiency Guide; ASABE D497.7","target":"Fuel efficiency coaching -> 10-15% fuel savings -> significant operating cost reduction"},
    {"label":"Replacement Cycle Optimization Plan","type":"STRUCTURAL","evidence":"A","description":"Develop replacement cycle analysis comparing cumulative maintenance costs, depreciation curves, and productivity trends to identify optimal trade points for wheel loaders. Optimized replacement timing minimizes total lifecycle cost per ton of material handled.","cite":"ASABE D497.7; Kansas State University MF-842","target":"Replacement optimization -> minimized lifecycle cost -> maximum value per ton handled"},
    {"label":"Cost Per Ton Tracking Culture","type":"CULTURE","evidence":"B","description":"Track and share material handling cost per ton across the operation to build awareness of how loader efficiency, fuel management, and maintenance affect the bottom line. Per-ton metrics create clear connections between operator behavior and economic outcomes.","cite":"Journal of the ASFMRA, 2019 – Material Handling Cost Management","target":"Per-ton tracking -> behavior-to-cost connection -> motivated efficiency"},
    {"label":"Wheel Loader TCO Spreadsheet","type":"TOOLS","evidence":"A","description":"Implement total cost of ownership spreadsheets tracking depreciation, fuel, tires, maintenance, and operator costs per machine and per hour. TCO tools support make-versus-buy decisions, fleet planning, and custom rate setting for material handling services.","cite":"ASABE D497.7 – Agricultural Machinery Management Data","target":"TCO spreadsheets -> informed fleet decisions -> profitable custom rates"}
  ]
});

// 17. Service Programs
addTreatments('p2_agri_machinery_partsmaint_serviceprograms.json', {
  monitoring: [
    {"label":"Service Compliance Tracking Protocol","type":"STRATEGY","evidence":"A","description":"Implement digital service compliance tracking monitoring completion rates for scheduled maintenance across all equipment units. Tracking compliance percentages identifies units falling behind schedule and departments with systemic maintenance deferral patterns.","cite":"ASABE EP496.3 – Machinery Management; Fleet Maintenance Magazine Best Practices","target":"Compliance tracking -> identified deferrals -> restored maintenance discipline"},
    {"label":"Technician Service Quality Coaching","type":"COACHING","evidence":"B","description":"Coach service technicians on documenting findings during scheduled maintenance including wear measurements, fluid analysis results, and recommended follow-up actions. Detailed service documentation transforms routine maintenance into predictive intelligence.","cite":"SAE J1930 – Diagnostic Terminology; ASABE EP496.3","target":"Quality documentation -> predictive intelligence -> proactive repairs"},
    {"label":"Service Program Audit System","type":"STRUCTURAL","evidence":"A","description":"Establish quarterly audits of service program execution verifying that scheduled intervals are met, specified procedures are followed, and recommended parts and fluids are used. Audits ensure service programs deliver their designed reliability benefits.","cite":"ISO 55000 – Asset Management; ASABE EP496.3","target":"Program audits -> verified execution -> delivered reliability benefits"},
    {"label":"Preventive Maintenance Value Culture","type":"CULTURE","evidence":"B","description":"Build organizational conviction that preventive maintenance is an investment, not an expense, by sharing data on repair cost avoidance achieved through scheduled service. Value demonstration converts maintenance skeptics into program advocates.","cite":"Reliability Engineering & System Safety, Vol. 183, 2019 – PM Value Demonstration","target":"Value demonstration -> organizational conviction -> sustained PM investment"},
    {"label":"Maintenance Management Software","type":"TOOLS","evidence":"A","description":"Deploy computerized maintenance management systems (CMMS) that automate service scheduling, parts inventory, work order generation, and cost tracking across the equipment fleet. CMMS platforms reduce administrative burden while improving maintenance consistency.","cite":"ISO 55000; ASABE EP496.3; UpKeep/Fiix CMMS Documentation","target":"CMMS deployment -> automated scheduling -> consistent maintenance execution"}
  ],
  practices: [
    {"label":"Tiered Service Interval Strategy","type":"STRATEGY","evidence":"A","description":"Develop tiered service programs with daily operator checks, 250-hour fluid services, 500-hour filter replacements, and annual comprehensive inspections aligned to manufacturer specifications. Tiered intervals balance maintenance thoroughness against operational interruption.","cite":"ASABE EP496.3 – Machinery Management; ASABE D497.7","target":"Tiered intervals -> balanced thoroughness -> minimized operational interruption"},
    {"label":"Operator Daily Service Coaching","type":"COACHING","evidence":"B","description":"Train operators on performing and documenting daily service checks including fluid levels, belt conditions, tire pressures, and unusual sounds or leaks. Operator-level daily service catches 60% of emerging issues at the earliest and cheapest intervention point.","cite":"Caterpillar Daily Inspection Guide; ASABE EP496.3","target":"Daily service skills -> 60% early issue detection -> lowest-cost intervention"},
    {"label":"Seasonal Service Scheduling SOP","type":"STRUCTURAL","evidence":"A","description":"Document seasonal service protocols that complete major maintenance during low-utilization periods, ensuring peak-season readiness. Pre-season preparation schedules, parts pre-ordering, and technician allocation plans prevent harvest-season breakdown crises.","cite":"ASABE D497.7; University Extension – Pre-Season Maintenance Guides","target":"Seasonal scheduling -> peak-season readiness -> prevented harvest breakdowns"},
    {"label":"Maintenance-Conscious Operator Culture","type":"CULTURE","evidence":"B","description":"Build a culture where operators view basic maintenance as part of their job, not someone else's responsibility. When operators own daily service, report issues promptly, and treat machines with care, overall fleet reliability improves measurably.","cite":"Journal of Extension, Vol. 53, 2015 – Operator-Centered Maintenance Culture","target":"Operator ownership -> prompt reporting -> measurably improved fleet reliability"},
    {"label":"Service History Documentation System","type":"TOOLS","evidence":"A","description":"Maintain complete service histories for every equipment unit including all maintenance performed, parts replaced, costs incurred, and downtime recorded. Comprehensive service records support warranty claims, resale value documentation, and fleet replacement planning.","cite":"ASABE EP496.3; ISO 55000 – Asset Management Documentation","target":"Complete records -> supported warranty claims -> informed replacement decisions"}
  ],
  technology: [
    {"label":"Predictive Maintenance Adoption Strategy","type":"STRATEGY","evidence":"B","description":"Transition from time-based to condition-based maintenance using oil analysis trends, vibration monitoring, and telematics fault data to predict component failures. Predictive maintenance reduces unnecessary service while catching failures 2-4 weeks before breakdown.","cite":"Reliability Engineering & System Safety, Vol. 185, 2019 – Predictive Maintenance","target":"Condition-based transition -> reduced unnecessary service -> 2-4 week failure prediction"},
    {"label":"Diagnostic Technology Training","type":"COACHING","evidence":"B","description":"Train technicians on electronic diagnostic tools, telematics data interpretation, and condition monitoring technologies that enable predictive maintenance decisions. Technology-capable technicians transform raw data into actionable maintenance intelligence.","cite":"SAE J1939; Applied Engineering in Agriculture, Vol. 36(3), 2020","target":"Diagnostic training -> data-to-intelligence transformation -> proactive decisions"},
    {"label":"Integrated Maintenance Data Platform","type":"STRUCTURAL","evidence":"B","description":"Deploy cloud-based maintenance platforms integrating CMMS data, telematics feeds, parts supplier catalogs, and fleet utilization metrics. Integrated platforms enable data-driven maintenance optimization impossible with disconnected information systems.","cite":"ISO 55000; SAE J1939; Cloud CMMS Platform Documentation","target":"Data integration -> maintenance optimization -> fleet-wide reliability improvement"},
    {"label":"Continuous Improvement in Maintenance","type":"CULTURE","evidence":"C","description":"Encourage maintenance teams to analyze failure patterns, propose process improvements, and test innovative service approaches on controlled equipment subsets. A culture of continuous improvement drives steady gains in service program effectiveness.","cite":"Total Productive Maintenance Principles; Journal of Extension, Vol. 55, 2017","target":"Improvement culture -> analyzed failures -> steady effectiveness gains"},
    {"label":"Mobile Maintenance Application","type":"TOOLS","evidence":"B","description":"Deploy mobile maintenance apps that enable technicians to access service procedures, log work orders, scan parts barcodes, and record inspection findings from the field. Mobile tools eliminate paperwork delays and improve service documentation completeness.","cite":"CMMS Software Documentation; Applied Engineering in Agriculture, Vol. 35(2), 2019","target":"Mobile apps -> eliminated paperwork -> improved documentation completeness"}
  ],
  economics: [
    {"label":"Maintenance ROI Documentation","type":"STRATEGY","evidence":"A","description":"Quantify service program ROI by tracking prevented breakdowns, extended component life, and preserved resale value against maintenance program costs. Documented ROI justifies maintenance budgets and prevents the false economy of deferred service.","cite":"ASABE D497.7; ISO 55000 – Asset Management Economics","target":"ROI documentation -> justified budgets -> prevented false economy of deferral"},
    {"label":"Maintenance Budget Planning Coaching","type":"COACHING","evidence":"B","description":"Coach farm managers on maintenance budget development using ASABE repair cost factors, fleet age profiles, and historical repair data. Budget-literate managers allocate adequate maintenance funding without requiring crisis-driven emergency spending.","cite":"ASABE D497.7 – Repair Cost Factors; Kansas State University MF-842","target":"Budget literacy -> adequate allocation -> eliminated emergency spending"},
    {"label":"Service Contract Evaluation Framework","type":"STRUCTURAL","evidence":"A","description":"Develop evaluation criteria for dealer service contracts, extended warranties, and maintenance outsourcing proposals comparing coverage scope, exclusions, and total cost against in-house maintenance capability and costs. Structured evaluation prevents unfavorable contracts.","cite":"ASABE D497.7; Equipment Dealer Association Contract Guidelines","target":"Contract evaluation -> informed decisions -> avoided unfavorable agreements"},
    {"label":"Total Cost of Deferral Awareness","type":"CULTURE","evidence":"B","description":"Build awareness that deferred maintenance costs 3-5x more than scheduled maintenance through cascading failures, emergency repairs, and lost productivity. Cost-of-deferral data makes the business case for timely service visible to all decision makers.","cite":"Reliability Engineering & System Safety, Vol. 180, 2018 – Deferral Cost Analysis","target":"Deferral awareness -> timely service -> 3-5x cost avoidance"},
    {"label":"Maintenance Cost Per Hour Tracker","type":"TOOLS","evidence":"A","description":"Implement per-unit maintenance cost tracking as a ratio of repair and maintenance cost to operating hours. Cost-per-hour trends identify equipment approaching replacement thresholds and validate the economic impact of service program changes.","cite":"ASABE D497.7 – Agricultural Machinery Management Data","target":"Per-hour tracking -> replacement threshold identification -> validated program changes"}
  ]
});

// 18. Shop Facilities
addTreatments('p2_agri_machinery_partsmaint_shopfacilities.json', {
  monitoring: [
    {"label":"Shop Safety Inspection Protocol","type":"STRATEGY","evidence":"A","description":"Implement monthly shop safety inspections covering fire extinguisher status, emergency exit access, electrical system integrity, ventilation function, and hazardous material storage compliance. Documented safety inspections maintain OSHA compliance and prevent workplace injuries.","cite":"OSHA 1910 – General Industry Standards; NFPA 30 – Flammable Liquids Code","target":"Safety inspections -> OSHA compliance -> prevented workplace injuries"},
    {"label":"Tool and Equipment Condition Coaching","type":"COACHING","evidence":"B","description":"Train shop personnel on daily inspection of shop tools and equipment including hydraulic jacks, welders, grinders, and compressed air systems. Pre-use inspection prevents the tool failures that cause hand injuries, the most common agricultural shop incident type.","cite":"OSHA 1910.242 – Hand and Portable Powered Tools; NIOSH Tool Safety","target":"Tool inspection skills -> detected defects -> prevented hand injuries"},
    {"label":"Facility Maintenance Schedule System","type":"STRUCTURAL","evidence":"A","description":"Establish maintenance schedules for shop infrastructure including overhead doors, lighting systems, heating/cooling equipment, air compressors, and waste oil management systems. Facility maintenance prevents the environmental violations and code issues that trigger expensive remediation.","cite":"OSHA 1910 – General Industry; EPA SPCC Rule – Oil Storage","target":"Facility maintenance -> prevented violations -> avoided expensive remediation"},
    {"label":"Clean and Organized Shop Culture","type":"CULTURE","evidence":"A","description":"Implement 5S methodology (Sort, Set in order, Shine, Standardize, Sustain) in shop facilities to maintain organization, cleanliness, and visual management. Organized shops reduce tool search time by 30%, decrease accidents, and improve technician morale.","cite":"Lean Manufacturing Principles; OSHA Housekeeping Standards","target":"5S implementation -> 30% reduced search time -> improved safety and morale"},
    {"label":"Environmental Monitoring Equipment","type":"TOOLS","evidence":"B","description":"Install air quality monitors, temperature sensors, and humidity gauges in shop facilities to verify ventilation adequacy during welding, painting, and chemical use activities. Environmental monitoring protects technician health and ensures regulatory compliance.","cite":"OSHA 1910.1000 – Air Contaminants; ACGIH TLV Guidelines","target":"Air monitoring -> verified ventilation -> protected technician health"}
  ],
  practices: [
    {"label":"Shop Layout Optimization Strategy","type":"STRATEGY","evidence":"A","description":"Design shop floor layouts that optimize workflow from equipment intake through diagnosis, repair, and return to service. Efficient layout minimizes machine movement within the shop, reduces handling damage, and improves technician productivity.","cite":"Lean Manufacturing Shop Design; ASABE EP496.3 – Machinery Management","target":"Layout optimization -> minimized movement -> improved technician productivity"},
    {"label":"Welding and Fabrication Skills Coaching","type":"COACHING","evidence":"B","description":"Invest in ongoing welding and fabrication training for shop technicians covering MIG, TIG, and stick welding on common agricultural steel grades. Skilled in-house fabrication capability reduces repair turnaround and enables custom solutions for unique equipment needs.","cite":"AWS D1.1 – Structural Welding Code; ASABE EP454 – Farm Welding Guide","target":"Welding skills -> in-house fabrication -> reduced repair turnaround"},
    {"label":"Parts Inventory Management SOP","type":"STRUCTURAL","evidence":"A","description":"Establish parts inventory management systems with defined reorder points, minimum stock levels for critical items, and organized storage with clear labeling. Systematic parts management prevents the repair delays caused by missing consumables and common replacement parts.","cite":"ASABE EP496.3; Lean Inventory Management Principles","target":"Inventory management -> eliminated stock-outs -> prevented repair delays"},
    {"label":"Professional Shop Standards","type":"CULTURE","evidence":"B","description":"Build professional pride in shop facility quality by maintaining clean work surfaces, organized tool storage, proper lighting, and comfortable working conditions. Professional shop environments attract and retain skilled technicians in competitive agricultural labor markets.","cite":"Farm Bureau Labor Studies, 2019 – Technician Recruitment and Retention","target":"Professional standards -> technician retention -> maintained repair capability"},
    {"label":"Hydraulic Press and Bearing Tools","type":"TOOLS","evidence":"A","description":"Equip shops with hydraulic presses, bearing pullers, induction heaters, and precision measurement tools appropriate for the equipment fleet being serviced. Proper shop tooling enables in-house repairs that would otherwise require expensive dealer service.","cite":"ASABE EP496.3; Snap-on Industrial Catalog – Agricultural Shop Equipment","target":"Proper tooling -> in-house capability -> avoided dealer service costs"}
  ],
  technology: [
    {"label":"Digital Work Order Management","type":"STRATEGY","evidence":"B","description":"Implement digital work order systems that track repair requests from submission through diagnosis, parts ordering, repair completion, and return to service. Digital workflow management eliminates lost paperwork and provides repair status visibility to all stakeholders.","cite":"CMMS Best Practices; ISO 55000 – Asset Management","target":"Digital workflow -> eliminated lost paperwork -> stakeholder visibility"},
    {"label":"Diagnostic Technology Investment Training","type":"COACHING","evidence":"B","description":"Train technicians on modern diagnostic equipment including electronic service tools, oscilloscopes, and thermal imaging cameras that enable faster, more accurate troubleshooting of complex agricultural equipment systems.","cite":"SAE J1939; Applied Engineering in Agriculture, Vol. 35(5), 2019","target":"Diagnostic training -> faster troubleshooting -> reduced repair time"},
    {"label":"Shop Technology Infrastructure Plan","type":"STRUCTURAL","evidence":"B","description":"Develop technology infrastructure plans for shops including WiFi connectivity for service tool laptops, electrical capacity for battery-electric equipment charging, and compressed air systems sized for modern pneumatic tools.","cite":"ASABE EP496.3; Shop Design Engineering Guidelines","target":"Infrastructure planning -> technology readiness -> future-proofed facilities"},
    {"label":"Learning Shop Environment","type":"CULTURE","evidence":"C","description":"Create a learning shop culture where technicians share diagnostic discoveries, attend manufacturer training, and mentor junior staff. Continuous learning environments develop diagnostic expertise that reduces repair costs and keeps pace with equipment complexity.","cite":"Journal of Extension, Vol. 56, 2018 – Agricultural Technician Development","target":"Learning culture -> diagnostic expertise -> kept pace with equipment complexity"},
    {"label":"Overhead Crane or Hoist System","type":"TOOLS","evidence":"A","description":"Install overhead crane or chain hoist systems rated for the heaviest components handled in the shop. Proper lifting equipment prevents the musculoskeletal injuries common in agricultural shops and enables safe handling of engines, transmissions, and headers.","cite":"OSHA 1910.179 – Overhead Cranes; ASME B30.16 – Overhead Hoists","target":"Lifting equipment -> prevented musculoskeletal injuries -> safe heavy component handling"}
  ],
  economics: [
    {"label":"Shop vs. Dealer Repair Cost Analysis","type":"STRATEGY","evidence":"A","description":"Track and compare in-house repair costs against dealer service invoices for equivalent work to quantify the economic value of shop capability. Cost comparisons justify shop facility investment and identify repair types better outsourced to specialists.","cite":"ASABE D497.7; Kansas State University MF-842 – Farm Machinery Costs","target":"Cost comparison -> justified investment -> optimized in-house vs. outsource balance"},
    {"label":"Shop Facility ROI Coaching","type":"COACHING","evidence":"B","description":"Coach managers on calculating shop facility return on investment including building costs, equipment, utility expenses, and technician labor against dealer service savings, reduced downtime value, and equipment life extension benefits.","cite":"Journal of the ASFMRA, 2018 – Farm Building Investment Analysis","target":"ROI calculation -> justified facility investment -> documented savings"},
    {"label":"Shop Capacity Planning Framework","type":"STRUCTURAL","evidence":"A","description":"Develop shop capacity models matching facility size, technician staffing, and tool inventory to the equipment fleet's maintenance and repair demand. Capacity planning ensures the shop can handle peak-season demand without creating maintenance backlogs.","cite":"ASABE EP496.3; Lean Facility Planning Principles","target":"Capacity planning -> met peak demand -> eliminated maintenance backlogs"},
    {"label":"Shop Investment Value Recognition","type":"CULTURE","evidence":"B","description":"Build management recognition that a well-equipped shop is a profit center that reduces total equipment costs, extends machine life, and minimizes downtime. Investment recognition prevents the budget cuts that degrade shop capability and increase total repair costs.","cite":"Farm Equipment Magazine, 2019 – On-Farm Shop Value Analysis","target":"Value recognition -> protected budgets -> sustained shop capability"},
    {"label":"Shop Operating Cost Dashboard","type":"TOOLS","evidence":"A","description":"Implement cost tracking dashboards for shop operations including utilities, consumables, tool replacement, and labor hours allocated to each equipment unit. Operating cost data validates shop efficiency and identifies improvement opportunities.","cite":"ASABE D497.7; CMMS Reporting Capabilities","target":"Cost dashboards -> validated efficiency -> identified improvement opportunities"}
  ]
});

console.log('Batch 2 complete: 9 files processed');
